"""#305 B4: plain-words question and tripwire for each of the 102 parked rows. Written by this seat from each
row's own title and closes_when in knowledge/_state.json (A2's D2 list). The tripwire applies A2's one rule
("reopens when its component or strand is next touched") to the row's own component or strand."""
ROWS = {
'W-51': ("Does a past event found by mining count as a 'catch' toward promoting a check? And promote, wait or park three candidates?", "a check is next put up for promotion"),
'W-63': ("Nine wave-3 components (transaction row, limits meter, split button and six more): promote, rework or delete each? Two may duplicate parts you have.", "any of the nine is next edited or listed in the catalogue"),
'W-71': ("Carousel and image block: promote, rework or delete? Plus an autoplay variant, a hand-drawn arrow and a small type-debt growth.", "carousel or image block is next edited or listed"),
'W-72': ("Calendar and tree: 19 questions, chiefly whether the date picker uses the calendar, and the tree's selection mark.", "calendar, tree or date picker is next edited"),
'W-73': ("Cascader, splitter and QR code: 19 questions, chiefly whether tree and cascader should both exist, and what a QR code does in dark mode.", "any of the three is next edited or listed"),
'W-99x': ("The #214 context strategy: four questions on the advisory line, the lines, two instruments and cutting the boot.", "the window or boot lines next change"),
'W-99y': ("A window band from 200K to 256K, allowed by kind of work: adopt it, keep 256K as the tolerance line, build a recall probe?", "the window lines next change"),
'W-135': ("Photography: the mono caption shade, five over-size image versions, and square edges.", "photography settings or the image block are next touched"),
'W-142': ("Charts: an easing vocabulary, the floating letter key, converting stacked area, and the gutter-fit plan.", "chart animation or stacked area next change"),
'W-143': ("Which parts carry behaviour: five questions (6 gained a script, 34 were judged static).", "a part's behaviour script is next added or changed"),
'W-151': ("Wave-3 alpha: five decisions on parts deliberately not built.", "that wave's components are next picked up"),
'W-152': ("Feedback parts: seven questions, chiefly how a toast is announced to a screen reader.", "the toast or feedback parts are next edited"),
'W-159': ("Promote the citation check? Wire it into the build? What counts for the document-row check?", "the citation or document-row check next changes"),
'W-166': ("Segmented control sizes: five questions (the old large size, a type ramp, label insets 8/12/16/20, two 44px hit-area names, a shared token router).", "the segmented control or the size scale is next touched"),
'W-167': ("CI: what the chain-size check should assert, three registrations in canon globally, and one generator self-test.", "the chain check or canon's globals next change"),
'W-175': ("Chart expansion: stacked-area conversion, which way to back-port, whether the cap ships before an expandable 'Other', and promoting a check.", "stacked charts or the 'Other' bucket next change"),
'W-179': ("How the Memento package copy stays in step (live mirror or authorised once), and how a session that wrapped twice is recorded.", "the Memento package is next re-cut"),
'W-190': ("The pack size ratchet's 427 of slack, and whether the claims folder stays named in two CI places.", "the pack size gate is next touched"),
'W-199': ("Strike 'index bootstrap' from the Memento debt list now it is built? It changes a frozen file.", "the Memento package is next re-cut"),
'W-206': ("May the 30 Getty, EyeEm and Stocksy photographs ship in the pack at all? A licence position, and yours alone. Plus five smaller questions.", "photographs are next put in a release"),
'W-207': ("Gumdrop retrieval addendum: three questions (one earlier question withdrawn).", "Gumdrop retrieval next changes"),
'W-208': ("Console dark caption ground: pick a rung from the ladder, plus six questions.", "console dark captions are next touched"),
'W-209': ("Sparkline, nothing built by measurement: four questions, chiefly the stale queue that misled a fourth lane.", "the sparkline next changes"),
'W-210': ("The capsule shape: which of three readings of your correction? Plus six questions.", "console capsule shapes are next touched"),
'W-211': ("Replay of #219's reports: 12 reds to repair or park, 25 items that could not run, and their questions.", "the replay sweep next runs"),
'W-220': ("Generators: five questions, a dashboard check that can never fail, and a file-name case bug hitting 7 components on Linux.", "a generator next changes"),
'W-221': ("Token health: 16 drifted fallbacks in five generators and a rotting fork ledger, plus questions.", "the token generators next change"),
'W-222': ("A designer's first hour with v1.0.1: 19 findings, 4 blocking. Schedule them, plus questions.", "the pack's first-hour guide next changes"),
'W-224': ("Build time: 12 priced trims to adopt or decline, five questions, and one declared fence breach.", "the build's run time is next worked on"),
'W-225': ("The #220 sitting page: 122 calls, 97 open, never sat.", "you ask for that sitting"),
'W-228': ("CI's first-step red: its questions, chiefly the corner longhand.", "corner radius CSS next changes"),
'W-229': ("Generators: 29 real-defect fork candidates, and a third red, #a8000b, on the error colour.", "the error reds or the fork ledger are next touched"),
'W-230': ("Pack first hour: a duplicate state tool in Gumdrop, and one vocabulary word.", "the pack is next re-cut"),
'W-231': ("Capture gate: the counts form against the repo template, and its questions.", "the capture gate next changes"),
'W-237': ("Promote or park the fallback-drift checker, advisory since #221?", "canon's fallback values next change"),
'W-245': ("The vendored token encoder: frozen-copy purity, and one declaration.", "the encoder or the Gumdrop seed next changes"),
'W-247': ("Which route wires token counting to the fallback encoder? And a delta gate that did not read the shim.", "token counting next changes"),
'W-253': ("Browser gates' third state: questions, including the roster count at regeneration.", "the browser gates next change"),
'W-254': ("Should the delta gate's scope widen? And one cross-Python proof still unproven.", "the package delta gate next changes"),
'W-255': ("The gates group number, and a stale-browser note.", "the gate probe is next regenerated"),
'W-257': ("The narrowed classifier: its questions, read at your ruled 58.", "the gate probe is next regenerated"),
'W-265c': ("Five schema questions: the state-model shape, the with-list shape, four unseated edge types, the provenance word, and where composition lives.", "the meta schema next changes"),
'W-272': ("Gumdrop single source: four questions, including an old v1.0.0 literal in CI and a dry run that rewrites a released page.", "the pack builder next changes"),
'W-273': ("The context system: fix the tier probe, split the harness remainder, add a retrieval ranker. Six questions.", "the boot or the capture gate next changes"),
'W-275': ("The wrap diet: pick one of four readings, plus four questions.", "the wrap is next reworked"),
'W-276': ("A replay sweep: one ruling-shaped red, and a hole in the kind order.", "the replay sweep next runs"),
'W-283': ("Regen against your dashboard: the theme question in the flow, the bento dashboard into canon, eight back-ports.", "the dashboard template next changes"),
'W-286': ("Search's default radius and the chart toolbar's square segmented overrides: six questions.", "search or the chart toolbar is next touched"),
'W-288': ("The floating action button: reveal mode, corner size, summon gesture and three more.", "the floating action button is next edited"),
'W-290': ("Segmented control: seven questions, chiefly the thumb, the zero inset, and wiring the radius generator into CI.", "the segmented control or radius generator is next touched"),
'W-304': ("The cold-start acceptance test: can a cold seat reach your fettled dashboard? You said the design-intent question is not settled.", "the next cold run is scored"),
'W-332': ("v1.0.5 re-stage: four ruling-shaped items and a go or no-go.", "the bento cold test next runs"),
'W-349': ("The designer's-brain plan: twelve questions in its section 8.", "the brain plan gets a version 2"),
'W-350': ("The same twelve questions, from the plan's build brief.", "the brain plan gets a version 2"),
'W-351': ("Principles survey: six questions (evidence grade as a field, grade L as a node type, inoculation, tensions as edges or nodes, which families first, an 'explained by' link).", "principles are next added to the graph"),
'W-352': ("The AI-native SDLC playbook: should anything from it enter Apollo, given it is a copy chain?", "the playbook comes up again"),
'W-358': ("Tensions: edges or nodes? A review page with two readings.", "polarities in the graph next change"),
'W-359': ("Who settles the 21 open tensions, rename 'tension', cap the defaults-used note, typed ruling links.", "polarities in the graph next change"),
'W-368': ("The behaviour address: five questions (grammar, one or a list, a blocking date, events, 14 fallback readings).", "a part's behaviour address next changes"),
'W-370': ("Licensed principle sources: which of 13 families go in, three questions, and one unproven licence.", "a principle family is next added to the graph"),
'W-376': ("The behaviour-address review page: the five questions in its section 06.", "a part's behaviour address next changes"),
'W-381': ("The polarity gate: four unruled escapes, and the legal form for a new or retired polarity.", "the polarity gate next changes"),
'W-389': ("The boot band: which multiplier sets it?", "the boot ceiling next changes"),
'W-391': ("The ritual diet: does the 10-line, 1,200-token cap stand?", "the wrap is next reworked"),
'W-406': ("Nav family: generate the queue line's gap count from the register? Five questions and nine registry lines.", "the navigation parts are next touched"),
'W-408': ("A debt sweep: two questions.", "the memory index cap next changes"),
'W-413': ("Bento row heights: re-rung the rail, or say 'rungs are floors'? And prune one large page render.", "the bento rail next changes"),
'W-416': ("Which of two #218 testimonies stands, or does the reader learn a second-wrap key?", "the wrap record reader next changes"),
'W-417': ("Behaviour populate: two questions, and a 14-meta chart migration to schedule.", "chart metas are next migrated"),
'W-418': ("Rung ladders: three questions, a 4px audit, and whether the container grid is needed at all.", "the bento rail next changes"),
'W-425': ("Glue code or a registered partial? And two gates that contradict on splice against link.", "the receipt or compose gate next changes"),
'W-427': ("Dashboard principles: questions 8 to 16 on the principles page.", "a dashboard principle is next enacted"),
'W-429': ("Density wave: two stale comments, and the Tabs demo width.", "the dashboard template is next edited"),
'W-431': ("The two stale 'only 6 and 3' comments in the template.", "the dashboard template is next edited"),
'W-432': ("The Tabs demo width, and a fold row in the first instrument.", "Tabs or the fold measure is next touched"),
'W-434': ("Rhythm wave: the per-tile row-sum law against the 4+2 wall, and 12 or 6 columns.", "the bento grid next changes"),
'W-435': ("The same row-sum question, and the order of the spans dial.", "the bento grid next changes"),
'W-436': ("Should the dashboard template register the whole chart-fit partial?", "chart fit next changes"),
'W-438': ("Rebuild canon.css or carry rules on the page? And the Tabs demo width, a third time.", "Tabs or chart fit is next touched"),
'W-443': ("Chart fit: where it lives, marks against bars, the 200px floor, the template's registration.", "chart fit next changes"),
'W-446': ("Is 'fits' a fact about the library or about the prompt? One span vocabulary, 6 or 12?", "part tags in the metas next change"),
'W-449': ("The byte gate: which legibility option, A1 or A3, and build or decline one guard.", "the behaviour byte gate next changes"),
'W-452': ("Interchangeability research: seven questions. Merge its vocabulary with the metas' eight tags, or keep two?", "part tags in the metas next change"),
'W-455': ("The status strip and card details probe: four questions.", "the status strip next changes"),
'W-457': ("The same probe's report: four questions, chiefly the carrier budget.", "the status strip next changes"),
'W-458': ("The strip build: the carrier question, and four unproven items.", "the status strip next changes"),
'W-462': ("Roles: six authoring calls unanswered, and three extensions to adopt or not.", "the roles list is next extended"),
'W-465': ("Schema terms: two questions (Q1 and Q3).", "the meta schema next changes"),
'W-466': ("Tagging page A: eight calls on the composing metas.", "part tags in the metas next change"),
'W-467': ("Tagging page B: ten calls on the chart metas.", "part tags in the metas next change"),
'W-510': ("The filter toolbar as a dashboard driver: the wiring names, the one-row collapse at 1400px, and the script size headroom.", "the filter toolbar is next edited"),
'W-100bd': ("Which files ship in the pack?", "the pack is next re-cut"),
'W-100bh': ("Bullet and candlestick charts: three points.", "either chart next changes"),
'W-100bi': ("Butterfly charts: two items, including whether a 2.2px baseline join should be gated.", "the butterfly charts next change"),
'W-100bk': ("A driver that could not reach 12 of 13 pages: how widely should it drive?", "that driver next changes"),
'W-100bm': ("Twelve items collected in the #260 wrap brief.", "the wrap is next reworked"),
'W-99zl': ("Unused per-theme tokens: five questions.", "per-theme tokens are next minted"),
'W-99zm': ("The bento edit rails: does 'every role' reach dials a role has no surface for? Retire an old absence rule?", "the bento editor is built"),
'W-99zn': ("The edit-pass grammar: seven questions.", "the bento editor is built"),
'W-99zq': ("Twelve theme defaults minted (mono caption grey, gallery square, console capsule): seven questions.", "those theme defaults next change"),
'W-99zr': ("The chord layer: five questions, chiefly mono's access to the dark caption chord, which the ruling left to you.", "mono captions next change"),
'W-99zu': ("The v3 manifest: six questions, two of them not on the review page.", "the pack manifest next changes"),
}
GROUPS = [
 ('T7', 'Dashboards, bento and composing a page', 'Closest to the one-shot path and the v1.0.14 cut.'),
 ('T5', 'The graph, rules and principles', 'The brain work now under way.'),
 ('T6', 'Charts', 'The chart engine sets the ceiling on every dashboard.'),
 ('T8', 'Components, tokens and themes', 'Component waves and theme defaults.'),
 ('T3', 'The designer pack and releases', 'What ships, and how the pack is built.'),
 ('T4', 'Gates, CI and checks', 'Instruments and their wiring.'),
 ('T2', 'Wrap, boot and the context window', 'The lines you ruled today sit next to these.'),
 ('T9+T0', 'Research and other', 'Outside reading and review pages.'),
]
FLAGS = [
 ('W-206', 'A licence position only you can take. It does not go stale by waiting.'),
 ('W-304', "The weekend's nine cold runs of the CEO Common prompt are close kin to this test."),
 ('W-272', 'The weekend found the same class again: the pack stamp rewrites three historical rulings (the Run 4a report, finding 1).'),
 ('W-99x', 'You ruled the window and boot lines today (calls 28 and 29); this may already be answered.'),
 ('W-99y', 'The same: call 28 set working 256,000 and hard 300,000.'),
 ('W-275', 'Your comment on call 29: "I want to return to impoving the wrap too at some point".'),
 ('W-265c', 'Sits next to the six schema calls you answered today (calls 14 to 19).'),
]
