"""#307 lane B — the bucket and the plain-words meaning for each of Dave's 78 clicks (lane B's reading, card by card).
kind: close | work | review | park | live.  For work/review: (title, closes_when, group).  group names the report list."""
# wid: (kind, means, [ (title, closes_when, group, owner) ... ])
D = {
'W-253': ('close', "Nothing is left to rule: the v1.0.2 release this report served shipped, the checks-group count it asked about (58) has since moved to 57 and then 60, and its other questions cannot be traced to a ruling.", []),
'W-255': ('close', "Nothing is left to rule: the count was read back at 58 before v1.0.2, and the note about an out-of-date browser was about a build-machine state that is long gone.", []),
'W-257': ('close', "Nothing is left to rule: the recheck it waited on was done before v1.0.2 shipped, and the report's own questions cannot be traced.", []),
'W-254': ('close', "The release check that compares the pack with its frozen copies is NOT widened now, and the cross-Python-version proof is not owed; the check is widened only if a real slip shows up.", []),
'W-211': ('close', "The replay of #219's reports (12 red, 25 could-not-run) is history and is not repaired or parked item by item: today's checks run on every push, so a red that still matters shows up there.", []),
'W-276': ('work', "The search gap the replay sweep found (the carried-items list was left out of search) is handed to Claude to fix; the rest of the sweep closes.",
          [("fix the search gap: the carried-items list is not found by the repo search; close the rest of the #226 replay sweep",
            "a query to knowledge/_memento_search.py returns a carried item from the carried-items list (generated on read since s306-D8), shown in a filed report, and the sweep's other items are closed there with a line each", 'quick', 'claude')]),
'W-220': ('work', "The generators report's five questions are handed to Claude: close any that no longer apply, settle the rest within Dave's rules (the two repairs it asked for were already taken on by the next generator build).",
          [("the #220 generators report's five questions: close those that no longer apply, settle the rest within Dave's rules",
            "each of the five questions in notes/_subreports/2026-08-27-220-audit-L2.md has a written disposition (no longer applies, or settled and what was done) in a filed report", 'quick', 'claude')]),
'W-231': ('close', "Settled by the #294 rule: the counts line is a condition every filed report must meet, in the form the check enforces.", []),
'W-381': ('close', "The four old records the contradiction check let through stay out of scope, as the later ruling on writing rule directions already chose.", []),
'W-100bm': ('close', "The twelve items the #260 wrap collected are not ruled as a set: the ones that matter are on this page as their own cards.", []),
'W-225': ('close', "The #220 sitting page (122 calls, never sat) is retired: this page is its successor and its live calls were carried here as their own cards. The page file stays in the tree as history.", []),
'W-391': ('close', "The start-of-session banner cap (10 lines, 1,200 tokens) stands, as the limits adopted at #306 (s306-D10) keep it.", []),
'W-275': ('close', "The wrap diet's four remaining questions are overtaken by the wrap redesign ruled at #306 (s306-D4), which rebuilds the wrap from one story.", []),
'W-209': ('close', "Settled: the carried items live in their own generated home, a pointer is checked rather than trusted, and at #306 the full carried list became generated on read.", []),
'W-389': ('close', "The start-up cost band's multiplier is ruled at 2.0, the value the check has used since #241.", []),
'W-416': ('work', "The check that stayed red at #245 is to be taught that a session can wrap twice (the report's own pick); nothing already written is changed.",
          [("teach the wrap-reading check that a session can wrap twice (the #245 red), changing nothing already written",
            "the check that went red at #245 on the twice-wrapped session accepts a session with two wrap lines, its selftest plants a twice-wrapped session and passes, and no existing record line is edited", 'checks', 'claude')]),
'W-179': ('close', "Ruled: the package copy is brought into step by hand at each release (the 'authorised once' way, as Dave has done twice), not kept as a live mirror.", []),
'W-273': ('close', "The #225 context-system figures are not pursued now: anything still true is raised when the wrap redesign re-measures start-up cost (W-305wr carries that re-measure).", []),
'W-224': ('close', "The #220 efficiency ledger's trims are not adopted: the prices no longer match the build, and the build is re-priced only if build time starts to hurt.", []),
'W-408': ('close', "Closed: the two questions the #244 debt sweep left are not spelled out on record, so there is nothing to rule.", []),
'W-51': ('park', "The promotion vocabulary is ruled: only LIVE catches count toward a check's promotion bar (s204-D1's 'caught twice'); a mined historical occasion does not. The three candidates named in the #207 addendum are parked until they catch something live.",
          [("write s307-D21's outcome into the candidature record: only live catches count; the three candidates parked as P-307-3",
            "knowledge/_DS-IMPROVEMENTS.md's candidature record carries the ruling (only live catches count) and names the three candidates as parked under P-307-3", 'quick', 'claude')]),
'W-237': ('work', "The var() fallback drift check is promoted: it is made blocking (it caught a real drift on the day it was built).",
          [("promote the var() fallback drift check (knowledge/_render/_gate_fallback_drift_221.py) from advisory to blocking",
            "the check is wired as blocking where the build's gates run, reads green on the current tree, and a planted drift makes it fail (selftest or receipt)", 'checks', 'claude')]),
'W-159': ('work', "The #218 cA report's three open questions are handed to Claude to settle within Dave's rules; none changes anything he sees.",
          [("the #218 cA report's three questions (2-4): settle within Dave's rules",
            "each of the three questions in notes/_subreports/2026-08-25-218-cA-filed-reports.md has a written disposition in a filed report", 'quick', 'claude')]),
'W-167': ('work', "The #219 lane-2 report's three open questions are handed to Claude to settle within Dave's rules; none changes anything he sees.",
          [("the #219 lane-2 CI-drift report's three questions: settle within Dave's rules",
            "each of the three questions in notes/_subreports/2026-08-25-219-lane2-ci-drift.md has a written disposition in a filed report", 'quick', 'claude')]),
'W-221': ('work', "Handed to Claude: confirm the fork list's stale rows were cleaned after the 98-fork triage, and settle the report's other questions.",
          [("confirm the fork list is clean after the #220 98-fork triage; settle the L3 report's other questions",
            "the fork ledger is read and shows no stale rows from the triage (or they are cleaned by addition), and each of the report's questions has a disposition, in a filed report", 'checks', 'claude')]),
'W-449': ('work', "The #250 lane-E questions (how the behaviour byte check reports, and the guard that would cross-check which scripts a part says it uses) are handed to Claude to settle within Dave's rules.",
          [("the #250 lane-E behaviour byte check: settle its options (how it reports; the scripts cross-check guard) within Dave's rules",
            "each open option in notes/_subreports/2026-09-06-250-E-byte-gate-unit.md has a disposition, and any guard built is wired and selftested, in a filed report", 'checks', 'claude')]),
'W-406': ('work', "Yes: the gap count is generated, never hand-typed (the typed '~26' agreed with nothing measured); Claude settles the rest of the #244 lane-A report.",
          [("generate the nav-family gap count instead of typing it; settle the rest of the #244 lane-A report",
            "the count the queue line typed ('about 26 gaps') is generated from the register by a tool and the typed figure is gone from its home, and the report's other questions have a disposition", 'checks', 'claude')]),
'W-190': ('work', "Yes: the packed-gate baseline is re-measured at each release (it was measured on 150 files while the pack ships 138, which leaves slack); Claude settles which folder it reads.",
          [("re-measure the packed-gate baseline at each release cut; settle which folder it reads",
            "the release steps re-measure the baseline on the shipped set at each cut (written into the release runbook or gate), and the folder question has a disposition", 'checks', 'claude')]),
'W-206': ('close', "Settled: the licence question that mattered is ruled (the photographs may ship, web versions only); the smaller questions are not pursued.", []),
'W-99zu': ('work', "The designers' pack ships all 100 guidelines, not a filtered set, and ships the Memento tools in one place only.",
          [("the pack ships all 100 guidelines and one copy of the Memento tools",
            "the next pack cut's manifest lists all 100 guidelines and exactly one copy of the Memento tools, read back from the built zip", 'ds', 'claude')]),
'W-370': ('work', "Shneiderman is kept to a name and a link (no quoted text) until a licence is found; Claude checks the three questions on how much text a pointer-only family may carry.",
          [("keep Shneiderman to a name and a link until a licence is found; check the three text-length questions for pointer-only families",
            "the graph and pack carry no quoted Shneiderman text unless a licence is recorded, and the three questions have a disposition, in a filed report", 'quick', 'claude')]),
'W-199': ('work', "Yes: the Gumdrop index builder, now built, is struck from the frozen owed-list at the next release cut (frozen files change only at a cut).",
          [("strike the built Gumdrop index builder from the frozen owed-list at the next release cut",
            "the next release cut's frozen list no longer names the index builder as owed", 'quick', 'claude')]),
'W-100bd': ('work', "No: the build setting that quietly changes what ships must print what it adds, or be removed.",
          [("the build setting that changes the ship set must print what it adds, or be removed",
            "one build run's output shows the setting printing every file it adds to the ship set, or the setting is gone from the build", 'checks', 'claude')]),
'W-230': ('work', "The pack keeps one copy of the state tool (two copies drift apart); Claude settles the one vocabulary word.",
          [("keep one copy of the state tool in the pack; settle the vocabulary word from the #221 lane-C report",
            "a built pack carries one copy of the state tool, and the word has a disposition, in a filed report", 'ds', 'claude')]),
'W-245': ('close', "Settled: Dave's yes (copy the change word for word into both frozen copies) answers the case it was asked about.", []),
'W-207': ('close', "History: the v1.0.1 fix shipped and the pack has moved on; the three questions are not taken up.", []),
'W-99zr': ('work', "Yes: mono takes console's chord (their neutral greys are identical, so it looks the same); Claude settles the four smaller questions.",
          [("mono takes console's chord; settle the four smaller questions from the #219 lane-C report",
            "mono's theme carries the chord (a render shows it unchanged against console's greys), and the four questions have a disposition, in a filed report", 'ds', 'claude')]),
'W-208': ('review', "Dave will look once at the four themes' dark captions side by side, then the question closes.",
          [("show Dave the four themes' dark captions side by side, once, then close",
            "one page shows the dark caption ground in all four themes side by side (console at neutral 5, #313131, and the proposed lifts), and Dave has seen it and ruled", 'review', 'claude')]),
'W-210': ('close', "Settled: all four caption treatments are legal, readings A and B were rejected, and the default is a rounded image with a clear caption; mono's dark caption has its own card.", []),
'W-99zq': ('close', "Settled: the defaults it asked about (console's capsule, mono's grey caption) were replaced by later defaults Dave ruled.", []),
'W-229': ('live', "The question stays open: Dave wants to check it visually. Not the recommendation (which was to fold the third red into the one error red).", []),
'W-99zl': ('work', "The six unused per-theme mints are handed to Claude to settle within Dave's rules.",
          [("dispose of the six unused per-theme mints within Dave's rules",
            "each of the six has a disposition (wired, retired or declared) in a filed report and the tree matches it", 'ds', 'claude')]),
'W-166': ('work', "Closed: Dave's re-rule covers the sizes; Claude settles the names (a type ramp, the two names for 44px touch areas, a shared token router).",
          [("settle the size names left by the #219 segmented report: a type ramp, the two names for 44px touch areas, the shared token router",
            "each of the three naming questions has a disposition in a filed report and the tree matches it", 'ds', 'claude')]),
'W-290': ('work', "The segmented generator is wired into the build (fix the class, not the patch); Claude settles the five zero-inset shadows.",
          [("wire the segmented generator into the build; settle the five zero-inset shadows",
            "the generator runs as a build step with its output checked, and the five shadows have a disposition, in a filed report", 'ds', 'claude')]),
'W-286': ('work', "Claude checks by render whether the one-source segmented fix swept up the toolbar's square segments; close if they match the rest.",
          [("render the toolbar's segments to check the one-source corner fix reached them; close if they match",
            "a render at the seat shows the toolbar's segment corners match the other segmented members (or the source is fixed), and the four other questions have a disposition", 'ds', 'claude')]),
'W-228': ('work', "How corner radius is written (one shorthand or four values) is handed to Claude to settle within Dave's rules.",
          [("settle how corner radius is written in code (one shorthand or four values) within Dave's rules",
            "the choice is written where the checks read it and the checks agree with it, in a filed report", 'checks', 'claude')]),
'W-418': ('work', "Run the 4px audit (the test Dave set at #245); if it passes, drop the container grid; bento row heights become tokens.",
          [("run the 4px audit; drop the container grid if it passes; make bento row heights tokens",
            "the 4px audit is run and filed; if it passes the container grid is removed and row heights are tokens, and if it fails the failures are put to Dave", 'ds', 'claude')]),
'W-413': ('work', "The image size rule is applied to the 4.36 MB full-page image; Claude trims it.",
          [("apply the image size rule to the 4.36 MB full-page image from #245 lane L4",
            "the image meets the image size rule (trimmed), shown by its size on disk", 'quick', 'claude')]),
'W-72': ('work', "Yes: the date picker uses the calendar (one calendar built once). Dave will see the tree's selection mark and the date picker's ring on a day that is both today and chosen, as pictures.",
          [("the date picker uses the calendar part",
            "the date picker is built on the calendar part (no second calendar), shown by a render and its meta", 'ds', 'claude'),
           ("show Dave, as pictures, the tree's selection mark and the date picker's ring on a day both today and chosen",
            "a page shows both as pictures and Dave has seen it and ruled", 'review', 'claude')]),
'W-73': ('work', "Keep both tree and cascader; the splitter reports a percentage; QR codes stay dark on light in every mode (the theme-following QR code was measured not to scan).",
          [("keep tree and cascader; the splitter reports a percentage; QR codes dark on light in every mode",
            "the splitter's reported value is a percentage and the QR code renders dark on light in every theme and mode, shown by a render; both tree and cascader stay in the library", 'ds', 'claude')]),
'W-63': ('work', "The transaction row becomes a variant of list items. Dave will see the other eight wave-3 parts as pictures.",
          [("make the transaction row a variant of list items",
            "the transaction row exists as a list-items variant (not its own part), shown by the metas and a render", 'ds', 'claude'),
           ("show Dave the other eight wave-3 parts as pictures (promote, rework or delete each)",
            "a page shows the eight as pictures and Dave has seen it and ruled on each", 'review', 'claude')]),
'W-71': ('work', "Image block is promoted; there is no autoplay; the carousel stays as it is (in the library, unpromoted).",
          [("promote image block; no autoplay; carousel stays unpromoted",
            "image block's meta is promoted, the carousel has no autoplay option, and the carousel stays in the library unpromoted", 'ds', 'claude')]),
'W-151': ('review', "Dave asked to see the five parts wave-3 alpha left unbuilt, and the reasons. Not the recommendation (which was to leave them unbuilt until a page needs one).",
          [("show Dave the five parts wave-3 alpha left unbuilt, and the reasons",
            "a page shows the five and the build's reasons for each, and Dave has seen it and ruled", 'review', 'claude')]),
'W-152': ('work', "The toast announces politely for news and at once (assertively) only for errors; Claude settles the six other questions.",
          [("toast announces politely for news, assertively only for errors; settle the six other questions",
            "the toast's live region is polite for news and assertive only for errors (shown in the part and its check), and the six have a disposition", 'ds', 'claude')]),
'W-288': ('work', "The summon gesture is closed as moot (the hot corner replaced it); Claude repairs the three stray body rules and settles the rest.",
          [("repair the FAB overlay's three stray body rules in canon.css; settle the rest (gesture closed as moot)",
            "the three stray body rules are repaired at their source and the demo-vs-shipped gap and notes questions have a disposition, in a filed report", 'ds', 'claude')]),
'W-143': ('close', "Settled: the five behaviour questions are the five Dave ruled the same day.", []),
'W-462': ('close', "Dave's 'go for it' at #252 covers the six calls; an extension to the roles vocabulary is added when a part needs one.", []),
'W-142': ('work', "The stacked area chart is converted (every stacked chart behaves the same); Claude confirms the adopted wave-3 plan is this report's draft.",
          [("convert the stacked area chart; confirm the adopted wave-3 plan is the #218 crank-charts draft",
            "the stacked area chart is converted like the other stacked surfaces, and the plan's identity is confirmed in a filed report", 'charts', 'claude')]),
'W-175': ('work', "Convert stacked area (the same conversion as W-142's row); ship the category cap now and the expandable 'Other' after; Claude settles the rest.",
          [("ship the chart category cap now and the expandable 'Other' after; settle the rest (stacked area rides on W-142's row)",
            "the category cap is shipped in the chart engine, the expandable 'Other' is built after it, and the report's other questions have a disposition", 'charts', 'claude')]),
'W-443': ('work', "Keep the 200px chart floor; register the template in full; Claude settles how marks are told apart from bars.",
          [("keep the 200px chart floor; register the chart template in full; settle how marks are told apart from bars",
            "the floor is kept in the engine, the template is a full registered member, and the marks question has a disposition", 'charts', 'claude')]),
'W-436': ('close', "Yes: the build's registration of the chart template is confirmed; fit stays in the one place Dave chose.", []),
'W-100bi': ('work', "Yes: the butterfly chart's join is checked (it is provable and cheap); Claude settles the other item.",
          [("check the butterfly chart's join; settle the other item from #260 lane F4",
            "a check proves the butterfly's two halves join and runs where the chart checks run, and the other item has a disposition", 'charts', 'claude')]),
'W-100bk': ('work', "The chart check runs on every chart page, with every rule.",
          [("the chart check covers every chart page with every rule",
            "the chart check's output lists every chart page and every rule it ran, with none skipped", 'charts', 'claude')]),
'W-100bh': ('work', "The three points on bullet and candlestick are handed to Claude to settle within Dave's rules.",
          [("settle the three points on the bullet and candlestick charts within Dave's rules",
            "each of the three points in notes/_subreports/2026-09-08-260-F3-bullet-candlestick.md has a disposition in a filed report", 'charts', 'claude')]),
'W-417': ('work', "The build's recommendations are taken (keep the old branch, promote two of the three sentences) and the 14-chart move is scheduled.",
          [("apply the #245 L2-populate recommendations; schedule the 14-chart move",
            "the recommendations are applied and the 14-chart move has its own store row with a closes_when", 'charts', 'claude')]),
'W-304': ('review', "The cold-start acceptance test is run once on the current pack and the result is shown to Dave.",
          [("run the cold-start acceptance test once on the current pack and show Dave",
            "one run on the current pack is filed with its result, and Dave has seen it and ruled", 'review', 'claude')]),
'W-458': ('work', "The above-the-fold signal count is capped at today's count (26 signals of 9 kinds at 1440 wide) so it cannot grow without Dave; he can lower it by eye later.",
          [("cap the dashboard's above-the-fold signals at today's count (26 at 1440 wide)",
            "a check fails when the dashboard shows more than 26 signals above the fold at 1440, wired where the build's checks run, with a selftest", 'dash', 'claude')]),
'W-455': ('close', "Closed: the above-the-fold limit is ruled on its own card (W-458).", []),
'W-457': ('close', "Closed: the above-the-fold limit is ruled on its own card (W-458).", []),
'W-283': ('work', "All eight of Dave's own dashboard improvements are brought back.",
          [("bring back all eight of Dave's dashboard improvements (the #227 regen-vs-Dave diff)",
            "the eight improvements are in the canon dashboard, each shown by a render against his dashboard", 'dash', 'claude')]),
'W-432': ('work', "Yes: the fold row is added (the fold is where Dave judges a dashboard).",
          [("add the fold row to the dashboard measures (#247 lane R)",
            "the fold row is in the dashboard measures and reads on the current page", 'dash', 'claude')]),
'W-427': ('work', "Handed to Claude: match questions 8 to 16 to the 29 enacted dashboard principles, and bring back to Dave only what is left.",
          [("match the #246 principles questions 8-16 to the 29 enacted principles; bring back only what is left",
            "each of questions 8-16 is matched to an enacted principle or listed as left, in a filed report, and anything left is put to Dave", 'dash', 'claude')]),
'W-510': ('close', "Closed: the filter bar's script fits (14,145 of 16,384 bytes), and the size check blocks it if it grows too far.", []),
'W-425': ('work', "Link, don't paste: wiring comes from one source; the two checks that disagree on pasting against linking are made to agree.",
          [("link, don't paste: make the two checks agree on linked wiring",
            "both checks accept linked wiring and refuse pasted copies, shown by each check's run on the current tree", 'checks', 'claude')]),
'W-438': ('work', "The shared stylesheet is rebuilt (a page places parts and never sizes them), rather than carrying the rules on the page.",
          [("rebuild the shared stylesheet so pages carry no sizing rules",
            "the shared stylesheet is rebuilt with the demo widths as real defaults, and the page carries no sizing rules", 'dash', 'claude')]),
'W-429': ('work', "Handed to Claude: fix the two stale comments, check the Tabs render, close.",
          [("fix the two stale comments from #247 W1; render Tabs to confirm the demo-width fault is gone",
            "the two comments are corrected and a render shows the Tabs fault gone", 'quick', 'claude')]),
'W-99zm': ('park', "Parked until the bento editor is built: the rails manifest's two questions only matter once the editor exists.", []),
'W-99zn': ('park', "Parked until the bento editor is built: the edit-pass grammar's seven questions are settled by use once the editor exists.", []),
}
