#!/usr/bin/env python3
"""
gen_foundations_217.py — the LIBRARY's Foundations pages (#217).

WHY IT EXISTS — Dave, 2026-08-22, verbatim:
  "so we need a foundations section in the library with images and logos displayed like the
   photography bento"

WHAT IT WRITES
  showroom/_foundations/photography.html   — the 12 minted web derivatives, bento-laid, each
                                             opening a ZERO-JS popover lightbox
  showroom/_foundations/logos.html         — the 12 exported HSBC marks, each on the ground its
                                             artwork requires
Both are addressed by knowledge/_render/gen_library_214.py, whose Foundations ladder tier
(s215-D4) was drawn empty until this generator existed. That file holds the ONE list of
foundation entries (`FOUNDATIONS`); this file imports it rather than keeping a second copy.

⛔ WHY THE PAGES LIVE IN showroom/_foundations/ AND NOT showroom/
  Two globs decide it, and both are non-recursive:
    · gen_showroom.py's orphan prune globs `showroom/*.html` and DELETES anything with no
      snippet behind it — a foundation page in showroom/ would be pruned on the next run.
    · gen_library_214.collect() globs the same pattern to build one component row per page —
      a foundation page there would be counted as a component.
  A subdirectory is invisible to both. Measured, not assumed (see --selftest bites 1-2).

⛔ NOTHING IS RE-DRAWN — [[specimen-starts-from-reference]]
  Every photograph is an <img> at its committed derivative in knowledge/assets/photography-web/.
  Every mark is an <img> at its exported SVG in knowledge/assets/logos/. No asset is copied,
  renamed, edited or derived from here. The layout vocabulary (`.bx-*` span attributes, the
  popover + invoker-command lightbox) is COPIED from the approved reference Dave pointed at,
  knowledge/_fitness-test/bento-gallery-showcase-v2.html (#216) — not re-invented.
  ⚠ That showcase is itself AWAITING Dave's sign-off. Copying a layout he pointed at is not a
  certification of it, and the sign-off row for these pages says so.

✅ BENTO IS CANON AS OF s217-D2 (#217) — THIS FILE WAS RE-POINTED AT IT
  ⛔ SUPERSEDES the #216 posture recorded here ("bento stays un-minted"): Dave promoted the
  bento to a canon structural component on 2026-08-23. These pages no longer declare a grid,
  a gap, a span vocabulary or responsive bands — they consume `.c-bento` / `.c-bento__grid` /
  `.c-bento__tile` from canon.css (AUTO-BENTO, generated by canon/gen_canon_bento.py) and
  declare TWO instance dials each. The page-local structural CSS went from ~24 lines to 2.
  ⚠ ONE BEHAVIOUR CHANGE, named: the old bands were VIEWPORT media queries; the canon bands
  are CONTAINER queries against the bento's own wall. Inside a narrow library pane the wall
  now collapses, which the pane embed always wanted and the media queries could not do.
  ⚠ The ruled thresholds are not the ones this page used to carry (4.0/1.45/every 5th ->
  6.0/2.6/every 6th from tile 1). The prose is generated from the store, so it says what ran.

✅ THE PHOTOGRAPHY WALL IS role=gallery AS OF s217-D3 (#217)
  It is a page-level photography wall, which is that role's own definition. Three consequences,
  all measured rather than assumed: the RADIUS moves from the container to the TILES; the
  CAPTION BLOCK takes the ruled generous space (86px, three description lines, both derived from
  layout/bento/caption-space, neither restated here); and THE SQUARING PASS NO LONGER RUNS —
  orphans are acceptable in a gallery, so the wall is now ragged where the pictures make it
  ragged, and the run REPORTS that rather than repairing it.
  ⚠ EXEMPT FROM SQUARING IS NOT EXEMPT FROM THE ASPECT MAPPING. `span_for`/`emphasise` still run,
  so portraits are still two rows tall. They are different mechanisms and the exemption must not
  take the second one with it (--selftest bite 21).
  ⚠ THE LOGO WALL CARRIES NO ROLE, deliberately. None was ruled for it, and a bento with no role
  attribute matches no role rule — it keeps the s217-D2 grammar exactly. A role is a decision.

⛔ NO POLICY IS AUTHORED
  The logos page carries only what knowledge/guidelines/logos.md already says plus facts
  MEASURED off the twelve files. The photography page carries only the manifest's own rows.
  No preference ordering, no clearspace rule, no licence interpretation.

EVERY NUMBER ON BOTH PAGES IS MEASURED AT BUILD TIME
  Photography: read from knowledge/_PHOTOGRAPHY-MANIFEST.json (s217-D1), itself generated.
  Logos: viewBox, natural size, byte count and fill inventory read off the SVG bytes here.
  Nothing on either page is typed by hand.

THEME + MODE — the same broadcast the showroom and the library use
  html[data-apollo-theme] + body[data-theme], driven by the page's own header AND by the URL
  fragment, with a `hashchange` listener so a fragment-only navigation re-themes in place
  (without it, the library pane's theme buttons would silently do nothing). `#chrome=0` hides
  the page's own header, exactly as gen_showroom.py's embed contract does.

⛔ NO VAR MAY DANGLE. An undefined custom property renders SILENT BLACK and no gate catches it
  ([[dangling-dataviz-var-renders-silent-black]]). Every `var()` on both pages carries a literal
  fallback, and --selftest bite 7 asserts it over the emitted CSS.

REGENERATE
  python3 knowledge/_render/gen_foundations_217.py
  python3 knowledge/_render/gen_foundations_217.py --check      # in-sync gate
  python3 knowledge/_render/gen_foundations_217.py --selftest
"""
import os as _hg_os, sys as _hg_sys  # noqa: E402 - help gate (#158 write-by-default class)
_hg_d = _hg_os.path.dirname(_hg_os.path.abspath(__file__))
while _hg_d != "/" and not _hg_os.path.exists(_hg_os.path.join(_hg_d, "_helpgate.py")):
    _hg_d = _hg_os.path.dirname(_hg_d)
_hg_sys.path.insert(0, _hg_d)
from _helpgate import help_gate as _help_gate; _help_gate(__doc__, __name__, __file__)

import glob
import html as htmlmod
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
KNOW = os.path.dirname(HERE)
ROOT = os.path.dirname(KNOW)
OUTD = os.path.join(ROOT, "showroom", "_foundations")
PHOTO_MANIFEST = os.path.join(KNOW, "_PHOTOGRAPHY-MANIFEST.json")
PHOTO_WEB = os.path.join(KNOW, "assets", "photography-web")
LOGO_DIR = os.path.join(KNOW, "assets", "logos")

sys.path.insert(0, HERE)
import gen_library_214 as library          # FOUNDATIONS — ONE list, not a second copy
import gen_bento_matrix_217 as matrix      # #217 — the s217-D5 option matrix, its own module

# Relative prefix from showroom/_foundations/<page>.html back to the repo root.
UP = "../../"

# ---------------------------------------------------------------------------
# THE SPAN RULE — ⛔ NO LONGER THIS FILE'S (s217-D2, #217).
# The derivation was promoted to canon with the grammar. `span_for` / `emphasise` now come
# from canon/gen_canon_bento.py, which reads the ruled thresholds out of tokens/layout.json
# (`layout/bento/$spanDerivation`) — so this page and every other bento consumer derive from
# ONE set of numbers. The page's OWN thresholds (4.0 / 1.45 / every 5th) are superseded by
# Dave's ruled ones (6.0 / 2.6 / 1:1.15, every 6th from tile 1); the prose below is generated
# from the store rather than typed, so it cannot drift from what actually ran.
# ⚠ AND IT IS PHOTOGRAPHY ONLY. The aspect thresholds are not wired to the logo wall: logo
# spans come from the artwork's own viewBox by the same call, which is legitimate because a
# logo IS an image with an aspect — but no CARD wall may adopt them (s217-D2).
# ---------------------------------------------------------------------------
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "canon"))
from gen_canon_bento import (params as bento_params, span_for, emphasise,  # noqa: E402
                             square_wall, square_wall_for_role, band_ladder, is_rectangular)

# ⚠ THE PHOTOGRAPHY WALL IS ROLE=GALLERY (s217-D3, #217). It is a page-level photography wall,
# which is the role's own definition — so it takes tile radius, tile spacing, the generous
# caption space, and NO SQUARING. The wall is now ragged where the pictures make it ragged, and
# that is the ruling rather than a regression. ⚠ The LOGO wall is deliberately left with NO role
# attribute: no role has been ruled for it, and a role is a decision, not a default. A bento
# with no role attribute matches no role rule and keeps the s217-D2 grammar exactly.
PHOTO_ROLE = "gallery"

_BP = bento_params()
# The photography wall's INSTANCE column count (`.fx-wall-photo{--bento-columns:4}`) — its
# ladder, not canon's. A wall never renders wider than its own dial.
PHOTO_LADDER = band_ladder(dict(_BP, columns=4))
SPAN_NOTE = ("Tile spans are derived from each image's own aspect ratio, not arranged by eye: "
             "wider than %.0f:1 spans three columns, wider than %.1f:1 spans two, taller than "
             "1:%.2f spans two rows, everything else is a single cell. The thresholds are canon "
             "(ruling s217-D2), read from knowledge/tokens/layout.json."
             % (_BP["aspect3"], _BP["aspect2"], _BP["aspect_tall"]))

# ⚠ MEASURED, and it is why a second rule exists: all twelve committed derivatives are 1600×1067
# — one aspect ratio, so the aspect rule alone assigns every tile the SAME span and the "bento"
# renders as a plain two-up grid. A bento's whole character is mixed emphasis. The emphasis is
# therefore taken from POSITION in the sorted list, which is mechanical (the list is sorted by
# derivative filename) rather than a picked arrangement. The rhythm is now Dave's ruled one.
EMPHASIS_NOTE = ("All twelve derivatives share one aspect ratio, so the aspect rule alone would "
                 "draw a plain grid. Emphasis is taken from position instead — every %dth tile "
                 "in filename order, from tile %d, is promoted to a 2×2 block (s217-D2). "
                 "Position, not preference." % (_BP["emph_every"], _BP["emph_from"]))


def span_attrs(span):
    """(cols, rows) -> the canon tile's span attributes. One place, so a tile can never be
    emitted with a `data-span` word the canon grammar no longer knows."""
    c, r = span
    return ' data-c="%d" data-r="%d"' % (c, r)


# ---------------------------------------------------------------------------
# LOGO MEASUREMENT — read off the bytes, exactly as reviews/LOGOS-2026-08-22-v1.html did.
# ---------------------------------------------------------------------------
VIEWBOX_RE = re.compile(r'viewBox="([^"]+)"')
FILL_RE = re.compile(r'fill="([^"]+)"')
LOGO_ORDER = ["hexagon", "masterbrand", "masterbrand-identifier"]
LOGO_LOCKUP = {
    "hexagon": ("Hexagon", "The HSBC hexagon mark alone."),
    "masterbrand": ("Masterbrand", "Hexagon + the HSBC wordmark."),
    "masterbrand-identifier": (
        "Masterbrand with identifier",
        "The masterbrand plus an “Example identifier” label (a business or division "
        "name), set in Univers Next Light."),
}
GROUND_HEX = {"light": "#FFFFFF", "dark": "#1A1A1A"}


def fill_label(v):
    v = v.strip()
    low = v.lower()
    if low in ("#ffffff", "white", "#fff"):
        return "white", "#FFFFFF"
    if low in ("#000000", "black", "#000"):
        return "black", "#000000"
    return v.upper() if v.startswith("#") else v, v


def read_logos():
    """-> (rows, residuals). Every field measured off the file; nothing typed."""
    rows, missing = [], []
    for lockup in LOGO_ORDER:
        for ground in ("light", "dark"):
            for ink in ("colour", "mono"):
                name = "%s-%s-%s.svg" % (lockup, ground, ink)
                path = os.path.join(LOGO_DIR, name)
                if not os.path.exists(path):
                    missing.append(name)
                    continue
                src = open(path, encoding="utf-8").read()
                vb = VIEWBOX_RE.search(src)
                vbox = vb.group(1).strip() if vb else None
                w = h = None
                if vbox:
                    parts = vbox.split()
                    if len(parts) == 4:
                        try:
                            w, h = float(parts[2]), float(parts[3])
                        except ValueError:
                            w = h = None
                # ⚠ `fill="none"` is a PAINT INSTRUCTION, not a colour, and it has no swatch
                # to draw. Counting it produced an empty chip reading `none ×1` on every tile.
                # It is excluded from the inventory and the inventory says "painted fills".
                counts = {}
                for f in FILL_RE.findall(src):
                    if f.strip().lower() in ("none", "transparent", "currentcolor"):
                        continue
                    lbl, swatch = fill_label(f)
                    key = (lbl, swatch)
                    counts[key] = counts.get(key, 0) + 1
                rows.append({
                    "file": name,
                    "lockup": lockup,
                    "lockup_label": LOGO_LOCKUP[lockup][0],
                    "ground": ground,
                    "ink": ink,
                    "viewbox": vbox or "UNKNOWN",
                    "w": w, "h": h,
                    "bytes": os.path.getsize(path),
                    "fills": [{"label": k[0], "swatch": k[1], "n": n}
                              for k, n in sorted(counts.items(), key=lambda kv: -kv[1])],
                    "span": span_for(w, h),
                })
    return rows, {"missing": missing}


def read_photos():
    """-> (rows, meta, residuals). Rows are the manifest's OWN rows that carry a derivative."""
    if not os.path.exists(PHOTO_MANIFEST):
        return [], {}, {"manifest": "MISSING"}
    d = json.load(open(PHOTO_MANIFEST, encoding="utf-8"))
    rows, missing = [], []
    for r in d.get("rows", []):
        deriv = r.get("derivative")
        if not deriv:
            continue
        if not os.path.exists(os.path.join(PHOTO_WEB, deriv)):
            missing.append(deriv)
            continue
        px = r.get("derivative_px") or ""
        w = h = None
        if "x" in px:
            try:
                w, h = (int(x) for x in px.split("x", 1))
            except ValueError:
                w = h = None
        rows.append({
            "file": deriv,
            "original": r.get("filename"),
            "w": w, "h": h,
            "orientation": r.get("orientation") or "UNKNOWN",
            # ⚠ null in the manifest means the field is ABSENT on the file. It is reported as
            # UNKNOWN here and never defaulted to a plausible sentence.
            "description": r.get("exif_description") or "UNKNOWN",
            "description_basis": r.get("exif_description_basis") or "UNKNOWN",
            "licence": r.get("licence_source") or "UNKNOWN",
            "licence_basis": r.get("licence_source_basis") or "UNKNOWN",
            "bytes": r.get("derivative_bytes") or 0,
            "src_px": "%s×%s" % (r.get("width"), r.get("height")),
            "span": span_for(w, h),
        })
    rows.sort(key=lambda r: r["file"])
    for i, r in enumerate(rows, 1):
        r["span"] = emphasise(r["span"], i)
    # THE SQUARING PASS — RATIFIED s217-D3, and this wall is EXEMPT from it. The policy is
    # ASKED, never re-decided here: `square_wall_for_role` reads role=gallery out of the store
    # and returns the wall untouched, reporting its raggedness as acceptable rather than as a
    # failure. An `if role == "gallery"` in this file would be a second source for a ruled fact.
    # ⚠ The wall is dialled to 4 columns (`.fx-wall-photo`), so its LADDER is 4/3/2/1 — a wall
    # never renders wider than its own dial.
    # ⚠ EXEMPT FROM SQUARING IS NOT EXEMPT FROM THE ASPECT MAPPING. `span_for`/`emphasise` above
    # still run, so portraits are still two rows tall — that mapping IS the "appropriate layout
    # for portrait and landscape images" the gallery role asks for. Different mechanisms.
    squared, srep = square_wall_for_role([r["span"] for r in rows], PHOTO_ROLE,
                                         ladder=PHOTO_LADDER)
    if srep["squared"] and not srep.get("exempt"):
        for r, s in zip(rows, squared):
            r["span"] = s
    return rows, d, {"missing_derivative_file": missing, "squaring": srep}


# ---------------------------------------------------------------------------- chrome
# ⛔ PAGE-LOCAL ONLY. Scoped under `.fx` so nothing here can reach canon, and every var()
# carries a literal fallback so nothing can dangle to silent black.
# ---------------------------------------------------------------------------------------
CSS = """
/* ===========================================================================
   FOUNDATIONS PAGE — page-local styles, declared here, scoped to `.fx`.
   ⛔ NO BENTO STRUCTURE IS DECLARED HERE. The bento was promoted to canon at
   s217-D2 (#217); the container, grid, span vocabulary and responsive bands
   come from canon.css's AUTO-BENTO block. What remains below is TILE CONTENT
   and page chrome, plus two instance dials per wall. The popover +
   invoker-command lightbox is still COPIED from the approved reference
   knowledge/_fitness-test/bento-gallery-showcase-v2.html, not re-drawn.
   ⛔ EVERY var() CARRIES A LITERAL FALLBACK. A custom property that fails to
   resolve renders silent black and no gate catches it — the fallbacks are the
   fence, and --selftest bite 7 is what keeps them there.
   =========================================================================== */
.fx{
  --page:      var(--background-default,#FFFFFF);
  --surface:   var(--surface-raised,#FFFFFF);
  --surface-2: var(--surface-subtle,#F3F3F3);
  --line:      var(--border-subtle,#D7D8D6);
  --line-2:    var(--border-strong,#767676);
  --ink:       var(--text-default,#1A1A1A);
  --ink-2:     var(--text-secondary,#545454);
  --focus:     var(--focus-ring,#1A1A1A);
  --focus-w:   var(--focus-ring-width,2px);
  --radius:    var(--border-radius-surface,0px);
  --radius-ctl:var(--border-radius-control,0px);
  --tap:       var(--target-min,44px);
  --ease:160ms cubic-bezier(.4,0,.2,1);
  --sp-1:4px; --sp-2:8px; --sp-3:12px; --sp-4:16px; --sp-5:24px; --sp-6:32px; --sp-7:48px;
  background:var(--page); color:var(--ink); -webkit-font-smoothing:antialiased;
}
.fx *{box-sizing:border-box;}
.fx :focus-visible{outline:var(--focus-w) solid var(--focus); outline-offset:2px;}
html,body{margin:0;}
body{background:var(--background-default,#FFFFFF);}

/* ⚠ MEASURED 2026-08-22 on reviews/LOGOS-2026-08-22-v1.html and carried here rather than
   re-derived: `body` both CARRIES data-theme and consumed var(--text-default), and in
   supercharge dark the two disagreed (body resolved #FFFFFF, a child resolved #F7F6F4).
   Substituting on a CHILD of the themed element is deterministic in every state probed,
   so the page regions restate the ink. */
.fx, header.app{color:var(--text-default,#1A1A1A);}

/* ---- header: theme + mode, hidden under the library's #chrome=0 embed contract ---- */
header.app{display:flex; flex-wrap:wrap; gap:var(--sp-4); align-items:center;
  padding:var(--sp-3) var(--sp-6); border-bottom:1px solid var(--line);
  background:var(--page); position:sticky; top:0; z-index:10;}
body[data-chrome="0"] header.app{display:none;}
header.app h1{margin:0; white-space:nowrap;}
header.app .spacer{flex:1 1 auto;}
.ctl{display:flex; align-items:center; gap:var(--sp-2); color:var(--ink-2);}
.seg{display:inline-flex; border:1px solid var(--ink); color:var(--ink);
  border-radius:var(--radius-ctl); overflow:hidden;}
.seg button{font-family:inherit; font-size:12px; font-weight:500; letter-spacing:0.06em;
  text-transform:uppercase; padding:7px 12px; border:0; background:transparent; color:inherit;
  cursor:pointer; border-right:1px solid var(--line);}
.seg button:last-child{border-right:0;}
.seg button[aria-pressed="true"]{background:var(--ink); color:var(--page);}

main{padding:var(--sp-6); max-width:1400px;}
section{margin:0 0 var(--sp-7); scroll-margin-top:80px;}
h2{margin:0 0 var(--sp-1);}
p.lede{margin:0 0 var(--sp-5); color:var(--ink-2); max-width:74ch;}
.sublabel{color:var(--ink-2); text-transform:uppercase; letter-spacing:0.14em;
  margin:0 0 var(--sp-3); display:flex; align-items:center; gap:var(--sp-2);}
.sublabel::before{content:''; width:20px; height:1px; background:var(--line);}
.fx a{color:inherit;}
.fx code{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:12px;
  background:var(--surface-2); padding:0 .3em; border-radius:var(--radius-ctl);}

/* ---- THE BENTO GRID — ⛔ NOT DECLARED HERE ANY MORE (s217-D2, #217) ---------------------
   The bento was PROMOTED TO CANON at #217. The container, the grid, the span vocabulary
   (`data-c` / `data-r`), the responsive bands and the container-radius model all come from
   canon.css's AUTO-BENTO block, generated by canon/gen_canon_bento.py out of
   tokens/layout.json (`layout/bento`). ~24 lines of page-local grid left this file and were
   not replaced: the two lines below are the whole remainder, and they are INSTANCE DIALS,
   not structure.
   ⚠ The dials are declared as RULES, never a `style=""` attribute, and the reason is
   measured: the live probe (knowledge/_render/verify_foundations_217.py) resolves every
   property the stylesheet reads against the document, and an inline-only name is invisible
   to it — it read EMPTY in all eight states. An inline custom property also beats container
   queries outright, which would make the canon bands silently inert on this page. */
/* ⚠ `.c-bento.` IN THE SELECTOR IS DELIBERATE (s217-D3). Canon's role rules are (0,2,0); a
   bare `.fx-wall-photo` is (0,1,0) and a role rule would beat it — silently, in one theme, at
   one width. Matching the role's specificity and loading after canon.css settles it on source
   order. The logo wall keeps its bare class because it carries no role. */
.c-bento.fx-wall-photo{--bento-columns:4; --bento-row-unit:180px;}
.fx-wall-logo {--bento-columns:4; --bento-row-unit:210px;}
/* the tiles keep their own content layout — a column, so caption and picture stack */
.fx .c-bento__tile{display:flex; flex-direction:column;}

/* ---- a photograph tile: the whole tile is the lightbox opener ---- */
/* the picture takes the slack row, the caption takes its own height — `1fr auto` rather than a
   flex column, so the image can never push the tile past its grid row */
.px-open{display:grid; grid-template-rows:1fr auto; width:100%; height:100%; padding:0;
  border:1px solid var(--line); background:var(--surface);
  /* s217-D3: under role=gallery the TILE carries the ruled radius, so the opener follows it
     rather than declaring a second, different one. */
  border-radius:inherit;
  overflow:hidden; cursor:pointer; color:inherit; font:inherit; text-align:left;
  transition:transform var(--ease), border-color var(--ease);}
.px-open:hover{transform:scale(1.008); border-color:var(--line-2);}
.px-open:active{transform:scale(.996);}
.px-img{display:block; width:100%; height:100%; min-height:0; object-fit:cover;
  background:var(--surface-2);}
/* ⚠ THE CAPTION'S BLOCK HEIGHT IS CANON'S NOW (s217-D3, `.c-bento__caption` under
   role=gallery): 86px, and the line allowance derived from it. What is left here is the inline
   padding, the colour and the clamp — the ruled numbers are NOT restated, or this page and the
   store would be two sources for one decision. The `,2` fallback is the pre-ruling value, so a
   caption outside a gallery wall still reads sensibly. */
.px-cap{padding-inline:var(--sp-3); color:var(--ink-2); display:flex;
  flex-direction:column; justify-content:center; gap:2px;}
.px-cap .px-desc{display:-webkit-box; -webkit-line-clamp:var(--bento-caption-lines,2);
  -webkit-box-orient:vertical; overflow:hidden;}
.px-cap .px-lic{color:var(--ink-2);}

/* ---- LIGHTBOX — popover + invoker commands. ZERO JavaScript in this component. ---- */
.px-lb{border:1px solid var(--line-2); border-radius:var(--radius); background:var(--page);
  color:var(--ink); padding:var(--sp-4); margin:auto; inset:0;
  max-width:min(92vw,1100px); max-height:92vh; overflow:auto;}
.px-lb::backdrop{background:rgba(0,0,0,.62);}
.px-lb-head{display:flex; justify-content:space-between; align-items:flex-start;
  gap:var(--sp-4); margin-bottom:var(--sp-3);}
.px-lb-x{font:inherit; font-family:inherit; cursor:pointer; min-width:var(--tap);
  min-height:var(--tap); border:1px solid var(--line-2); border-radius:var(--radius-ctl);
  background:transparent; color:var(--ink); padding:0 var(--sp-3);}
.px-lb-x:hover{background:var(--surface-2);}
.px-lb img{display:block; width:100%; height:auto; max-height:66vh; object-fit:contain;
  background:var(--surface-2);}
.px-lb dl{display:grid; grid-template-columns:max-content 1fr; gap:var(--sp-2) var(--sp-4);
  margin:var(--sp-4) 0 0;}
.px-lb dt{color:var(--ink-2); text-transform:uppercase; letter-spacing:0.08em;}
.px-lb dd{margin:0;}

/* ---- a logo tile: the ground is FIXED to the artwork, never themed ---- */
.lg-tile{border:1px solid var(--line); border-radius:var(--radius); overflow:hidden;
  display:grid; grid-template-rows:1fr auto;}
/* ⛔ TILE GROUNDS ARE LITERAL, NOT TOKENS. Measured 2026-08-22: every fill in all twelve SVGs
   is hardcoded, so no logo can follow a theme. A dark mark must never float on a light ground
   to "show" it, and vice versa — so the tile is pinned to the ground its artwork was drawn for,
   in every theme and in both modes. The page chrome follows the theme; the tiles do not. */
.lg-art{display:flex; align-items:center; justify-content:center; min-height:0;
  padding:var(--sp-5);}
.lg-art[data-ground="light"]{background:#FFFFFF;}
.lg-art[data-ground="dark"]{background:#1A1A1A;}
.lg-art img{display:block; max-width:100%; max-height:56px; width:auto; height:auto;}
.lg-cap{padding:var(--sp-3); color:var(--ink-2); display:flex; flex-direction:column; gap:2px;
  border-top:1px solid var(--line); background:var(--surface);}
.lg-cap .lg-name{color:var(--ink);}
.lg-file{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; word-break:break-all;}
.chips{display:flex; flex-wrap:wrap; gap:6px; margin:6px 0 0;}
.chip{display:inline-flex; align-items:center; gap:5px; color:var(--ink-2);
  border:1px solid var(--line); border-radius:var(--radius-ctl); padding:1px 6px;}
.chip i{width:10px; height:10px; display:inline-block; border:1px solid var(--line);}
.chip b{font-weight:500; color:var(--ink);}

/* ---- findings + tables ---- */
.finding{border:1px solid var(--line); border-left-width:4px; padding:var(--sp-4) var(--sp-5);
  margin:var(--sp-4) 0 0; border-radius:var(--radius);}
.finding p{margin:var(--sp-2) 0 0; color:var(--ink-2); max-width:82ch;}
.finding b{color:var(--ink); font-weight:500;}
.tablewrap{overflow-x:auto; border:1px solid var(--line); border-radius:var(--radius);}
table{border-collapse:collapse; width:100%;}
th,td{text-align:left; padding:8px 12px; border-bottom:1px solid var(--line); white-space:nowrap;}
thead th{background:var(--surface-2); font-weight:500; text-transform:uppercase;
  letter-spacing:0.08em;}
tbody tr:last-child td{border-bottom:0;}
td.num{font-variant-numeric:tabular-nums;}
td:first-child{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;}
.notes{max-width:80ch;}
.notes p, .notes ul{color:var(--ink-2);}
.notes ul{padding-left:1.2em;}
.notes li{margin:0 0 var(--sp-2);}
.notes b{color:var(--ink); font-weight:500;}

/* ---- responsive ------------------------------------------------------------------------
   ⛔ THE BENTO BANDS ARE GONE FROM THIS FILE. They are canon now, and they are CONTAINER
   queries against the bento's own wall (1100 / 820 / 520, s217-D2) rather than the three
   viewport media queries that used to sit here. That is a behaviour change as well as a
   deletion: inside a narrow library pane the wall is what collapses, which is what the pane
   embed always wanted. What remains is page chrome, which the VIEWPORT does decide. */
@media (max-width:820px){ main{padding:var(--sp-5) var(--sp-4);} }
@media (prefers-reduced-motion: reduce){
  .fx *,.fx *::before,.fx *::after{transition-duration:.01ms !important;
    animation-duration:.01ms !important;}
}
"""

SCRIPT = """
(function(){
  var THEMES=['mono','legacy','console','supercharge'];
  var state={theme:'mono',mode:'light',chrome:'1'};
  function apply(){
    document.documentElement.setAttribute('data-apollo-theme',state.theme);
    document.body.setAttribute('data-theme',state.mode);
    document.body.setAttribute('data-chrome',state.chrome);
    document.querySelectorAll('#themes button').forEach(function(b){
      b.setAttribute('aria-pressed', String(b.dataset.themeAttr===state.theme)); });
    document.querySelectorAll('#modes button').forEach(function(b){
      b.setAttribute('aria-pressed', String(b.dataset.mode===state.mode)); });
  }
  var t=document.getElementById('themes'), m=document.getElementById('modes');
  if(t) t.addEventListener('click',function(e){
    var b=e.target.closest('button'); if(!b) return; state.theme=b.dataset.themeAttr; apply(); });
  if(m) m.addEventListener('click',function(e){
    var b=e.target.closest('button'); if(!b) return; state.mode=b.dataset.mode; apply(); });
  // A fragment-only navigation does NOT re-run this script, so without the hashchange listener
  // the library pane's theme buttons would silently do nothing (measured on the LOGOS page,
  // 2026-08-22: the second render came back mode=light with m=dark in the address).
  function fromHash(){
    var h={};
    location.hash.replace(/^#/,'').split('&').forEach(function(kv){
      var p=kv.split('='); if(p[0]) h[p[0]]=decodeURIComponent(p[1]||''); });
    if(THEMES.indexOf(h.theme)>=0) state.theme=h.theme;
    if(h.m==='light'||h.m==='dark') state.mode=h.m;
    if(h.chrome==='0'||h.chrome==='1') state.chrome=h.chrome;
    apply();
  }
  window.addEventListener('hashchange',fromHash);
  fromHash();
  // Capability read, REPORTED not asserted: the lightbox is the platform's popover driven by
  // command/commandfor. If this browser lacks either, the note says so rather than the page
  // pretending the control works.
  var cap=document.getElementById('cap');
  if(cap){
    var pop=HTMLElement.prototype.hasOwnProperty('popover');
    var cmd=HTMLButtonElement.prototype.hasOwnProperty('commandForElement');
    cap.textContent = (pop&&cmd) ? 'popover + invoker commands \\u2014 supported in this browser'
      : 'popover ' + (pop?'yes':'no') + ' \\u00b7 invoker commands ' + (cmd?'yes':'no')
        + ' \\u2014 the lightbox needs both';
  }
})();
"""

HEAD = """<!doctype html>
<html lang="en" data-apollo-theme="mono">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>__TITLE__</title>
__SENTINEL__
<link rel="stylesheet" href="__UP__knowledge/canon/type.css">
<link rel="stylesheet" href="__UP__knowledge/canon/canon.css">
<style>__CSS__</style>__EXTRA_CSS__
</head>
<body data-theme="light" data-chrome="1" class="fx__EXTRA_CLASS__">
<header class="app">
  <h1 class="t-ed-heading-4">__H1__</h1>
  <span class="t-ed-caption">__SUBTITLE__</span>
  <span class="spacer"></span>
  <div class="ctl"><span class="t-ed-caption">Theme</span>
    <div class="seg" id="themes" role="group" aria-label="Theme">
      <button type="button" data-theme-attr="mono" aria-pressed="true">Mono</button>
      <button type="button" data-theme-attr="legacy" aria-pressed="false">Legacy</button>
      <button type="button" data-theme-attr="console" aria-pressed="false">Console</button>
      <button type="button" data-theme-attr="supercharge" aria-pressed="false">Supercharge</button>
    </div>
  </div>
  <div class="ctl"><span class="t-ed-caption">Mode</span>
    <div class="seg" id="modes" role="group" aria-label="Light or dark">
      <button type="button" data-mode="light" aria-pressed="true">Light</button>
      <button type="button" data-mode="dark" aria-pressed="false">Dark</button>
    </div>
  </div>
</header>
<main>
"""

TAIL = """</main>
<script>__SCRIPT__</script>__EXTRA_SCRIPT__
</body>
</html>
"""

SENTINEL = "<!-- APOLLO-FOUNDATIONS PAGE (gen_foundations_217.py) -->"


def esc(s):
    return htmlmod.escape(str(s if s is not None else ""), quote=True)


def shell(title, h1, subtitle, body, extra_css="", extra_script="", extra_class=""):
    """THE ONE PAGE SHELL for every Foundations entry.

    ⚠ `extra_css` / `extra_script` / `extra_class` exist for ONE reason (#217, the bento matrix
    explorer): a Foundations entry that is an INSTRUMENT needs its own controller styles and its
    own behaviour, and the alternative was a second shell. A second shell is how the theme
    broadcast, the `#chrome=0` embed contract and the head order fork. The extra blocks are
    ADDITIVE and page-scoped; nothing here reaches canon."""
    return ((HEAD
             .replace("__TITLE__", esc(title))
             .replace("__SENTINEL__", SENTINEL)
             .replace("__UP__", UP)
             .replace("__CSS__", CSS)
             .replace("__EXTRA_CSS__",
                      ("\n<style>%s</style>" % extra_css) if extra_css.strip() else "")
             .replace("__H1__", esc(h1))
             # ⚠ the space is part of the SLOT, not the value: with it in the template every
             # existing page's <body> would gain a trailing space and rewrite on the next run —
             # a diff on two signed-off pages for an addition that does not touch them.
             .replace("__EXTRA_CLASS__", (" %s" % extra_class) if extra_class else "")
             .replace("__SUBTITLE__", subtitle))
            + body + TAIL.replace("__SCRIPT__", SCRIPT)
                         # ⚠ EMITTED ONLY WHEN THERE IS ONE. An empty `<script>` tag would be
                         # invisible to a reader and LOUD to a gate: the photography page's
                         # zero-JavaScript-lightbox bite counts script tags, and a shell that
                         # always emits two would have made that bite unfailable-in-reverse.
                         .replace("__EXTRA_SCRIPT__",
                                  ("\n<script>%s</script>" % extra_script)
                                  if extra_script.strip() else ""))


# ---------------------------------------------------------------------------- photography
def photography_page(rows, meta, residuals):
    counts = (meta or {}).get("counts", {})
    total = counts.get("originals", "UNKNOWN")
    derivs = counts.get("derivatives", len(rows))
    spec = (meta or {}).get("derivative_spec", {})
    tiles, boxes = [], []
    for i, r in enumerate(rows, 1):
        lid = "lb-photo-%d" % i
        desc = r["description"]
        short = desc if len(desc) <= 96 else desc[:95].rsplit(" ", 1)[0] + "…"
        tiles.append(
            '<figure class="c-bento__tile"%s>'
            '<button class="px-open" type="button" command="show-popover" commandfor="%s">'
            '<img class="px-img" src="%sknowledge/assets/photography-web/%s" alt="%s"'
            ' loading="lazy" width="%s" height="%s">'
            '<figcaption class="c-bento__caption px-cap">'
            '<span class="t-ed-caption px-desc">%s</span>'
            '<span class="t-cm-legal px-lic">%s &middot; %s</span>'
            '</figcaption></button></figure>'
            % (span_attrs(r["span"]), lid,
               UP, esc(r["file"]), esc(short if desc != "UNKNOWN" else "Photograph"),
               esc(r["w"] or ""), esc(r["h"] or ""),
               esc(short), esc(r["licence"]), esc(r["w"] and "%s×%s" % (r["w"], r["h"]) or "")))
        boxes.append(
            '<div id="%s" popover class="px-lb fx" aria-label="%s">'
            '<div class="px-lb-head">'
            '<span class="t-ed-body-small">%s</span>'
            '<button class="px-lb-x t-cm-ctl-14" type="button" command="hide-popover"'
            ' commandfor="%s">Close</button></div>'
            '<img src="%sknowledge/assets/photography-web/%s" alt="%s">'
            '<dl class="t-ed-caption">'
            '<dt>Description</dt><dd>%s</dd>'
            '<dt>Basis</dt><dd><code>%s</code></dd>'
            '<dt>Licence source</dt><dd>%s</dd>'
            '<dt>Basis</dt><dd><code>%s</code></dd>'
            '<dt>Original</dt><dd><code>%s</code> &middot; %s</dd>'
            '<dt>Derivative</dt><dd><code>%s</code> &middot; %s×%s &middot; %s KB</dd>'
            '</dl></div>'
            % (lid, esc(short), esc(short), lid, UP, esc(r["file"]),
               esc(short if desc != "UNKNOWN" else "Photograph"),
               esc(desc), esc(r["description_basis"]), esc(r["licence"]),
               esc(r["licence_basis"]), esc(r["original"]), esc(r["src_px"]),
               esc(r["file"]), esc(r["w"]), esc(r["h"]),
               esc(round((r["bytes"] or 0) / 1024))))

    missing = residuals.get("missing_derivative_file") or []
    body = """
  <section id="intro">
    <h2 class="t-ed-heading-3">Photography</h2>
    <p class="t-ed-body lede">A Foundations tier entry, not a component. The %d photographs below
      are the <b>committed web derivatives</b> in <code>knowledge/assets/photography-web/</code> —
      the whole set is <b>%s originals</b>, which stay NON-REPO behind the #211 <code>.gitignore</code>
      fence; a derivative is minted on demand for the photograph a page actually uses
      (ruling <code>s217-D1</code>). Derivative spec: max edge %s px, target %s KB, %s, %s.
      Every caption is the photograph's own EXIF description and its derived licence source,
      copied verbatim from <code>knowledge/_PHOTOGRAPHY-MANIFEST.json</code> — nothing is inferred
      and nothing is typed here. <code>UNKNOWN</code> means the field is absent on the file.</p>
    <p class="t-ed-body-small lede">%s Open any tile for the full description, both bases, and the
      measured sizes. <span id="cap"></span></p>
    <p class="t-ed-body-small lede">%s</p>
  </section>

  <section id="bento">
    <div class="sublabel t-ed-caption">The bento &mdash; %d derivatives</div>
    <div class="c-bento fx-wall-photo" data-bento-role="gallery"><div class="c-bento__grid">
%s
    </div></div>
  </section>

  <section id="notes" class="notes">
    <h2 class="t-ed-heading-4">What this page is, and is not</h2>
    <ul class="t-ed-body-small">
      <li><b>Nothing is re-drawn.</b> Every photograph is an <code>&lt;img&gt;</code> at its
        committed derivative. The layout vocabulary and the zero-JavaScript lightbox are copied
        from <code>knowledge/_fitness-test/bento-gallery-showcase-v2.html</code> (#216) &mdash;
        <b>which is itself awaiting Dave's sign-off</b>. Copying a layout he pointed at is not a
        certification of it.</li>
      <li><b>No preference ordering.</b> The %d photographs carrying derivatives are specimen
        picks for the Image-block and Carousel pages; picking a specimen is not a ruling and
        Dave swaps by eye. Tile order is the derivative filename, ascending.</li>
      <li><b>No tags, keywords or categories.</b> The tagging approach is unruled (#211 owed
        item 3) and no meaning is inferred from the description text.</li>
      <li><b>Page-local styles only.</b> Dave parked structural bento components at #216, so this
        page mints no canon component and edits no canon rule. Every rule it ships is in its own
        head, scoped to <code>.fx</code>.</li>
      <li><b>The lightbox ships no JavaScript.</b> It is the platform's <code>popover</code>
        driven by <code>command</code> / <code>commandfor</code> on the button. The only script
        on the page is the theme/mode chrome.</li>
      %s
    </ul>
  </section>
""" % (len(rows), esc(total), esc(spec.get("max_edge_px", "UNKNOWN")),
       esc(spec.get("target_kb", "UNKNOWN")), esc(spec.get("colour", "UNKNOWN")),
       esc(spec.get("format", "UNKNOWN")), esc(SPAN_NOTE), esc(EMPHASIS_NOTE), len(rows),
       "\n".join("      " + t for t in tiles), len(rows),
       ("<li>⚠ <b>%d manifest row(s) name a derivative that is not on disk</b>: %s. Reported, "
        "not hidden, and not drawn.</li>" % (len(missing), esc(", ".join(missing)))) if missing else "")
    return shell("Photography — Apollo library (Foundations)", "Photography",
                 "Foundations &middot; %d derivatives of %s originals" % (len(rows), esc(total)),
                 body + "\n" + "\n".join(boxes) + "\n")


# ---------------------------------------------------------------------------- logos
def logos_page(rows, residuals):
    tiles = []
    for r in rows:
        chips = "".join(
            '<span class="chip t-cm-legal"><i style="background:%s"></i>%s <b>&times;%d</b></span>'
            % (esc(f["swatch"]), esc(f["label"]), f["n"]) for f in r["fills"])
        tiles.append(
            '<figure class="c-bento__tile lg-tile"%s>'
            '<div class="lg-art" data-ground="%s">'
            '<img src="%sknowledge/assets/logos/%s" alt="%s &mdash; %s, on %s">'
            '</div>'
            '<figcaption class="lg-cap">'
            '<span class="t-ed-body-small lg-name">%s &middot; %s &middot; On %s</span>'
            '<span class="t-cm-legal lg-file">%s</span>'
            '<span class="t-cm-legal">viewBox %s &middot; %s bytes &middot; tile ground %s</span>'
            '<span class="chips">%s</span>'
            '</figcaption></figure>'
            % (span_attrs(r["span"]),
               r["ground"], UP, esc(r["file"]), esc(r["lockup_label"]),
               esc("colour" if r["ink"] == "colour" else "monotone"), esc(r["ground"]),
               esc(r["lockup_label"]),
               "Colour" if r["ink"] == "colour" else "Monotone", esc(r["ground"]),
               esc(r["file"]), esc(r["viewbox"]), esc("{:,}".format(r["bytes"])),
               esc(GROUND_HEX[r["ground"]]), chips))

    trows = "".join(
        "<tr><td>%s</td><td>%s</td><td>On %s</td><td>%s</td><td>%s</td>"
        "<td class='num'>%s</td><td>%s</td></tr>"
        % (esc(r["file"]), esc(r["lockup_label"]), esc(r["ground"]),
           "Colour" if r["ink"] == "colour" else "Monotone", esc(r["viewbox"]),
           esc("{:,}".format(r["bytes"])),
           esc(" · ".join("%s×%d" % (f["label"], f["n"]) for f in r["fills"])))
        for r in rows)

    body = """
  <section id="intro">
    <h2 class="t-ed-heading-3">Logos</h2>
    <p class="t-ed-body lede">A Foundations tier entry, not a component. Three lockups, each in
      <b>Colour</b> and <b>Monotone</b>, each in an <b>On light</b> and an <b>On dark</b>
      treatment &mdash; the on-dark artwork is the reverse cut, drawn for dark surfaces. %d files
      in all, in <code>knowledge/assets/logos/</code>. Every fill in every file is hardcoded, so
      <b>no logo follows a theme</b>: each tile is pinned to the ground its artwork was drawn for,
      in all four themes and in both modes. The page chrome follows the theme; the tiles
      deliberately do not.</p>
    <p class="t-ed-body-small lede">%s Every viewBox, byte count and fill inventory below was read
      off the SVG files at build time. Nothing is typed.</p>
  </section>

  <section id="bento">
    <div class="sublabel t-ed-caption">The bento &mdash; %d variants</div>
    <div class="c-bento fx-wall-logo"><div class="c-bento__grid">
%s
    </div></div>
    <div class="finding">
      <div class="t-ed-body-small"><b>&#9888; Measured, not fixed &mdash; the two ON-DARK
        identifier exports carry no identifier label.</b></div>
      <p class="t-ed-body-small">Both dark files are the plain masterbrand artwork on a 795-unit
        viewBox: the label paths are absent, so 480 units (60%% of the box) render empty. The two
        tiles above show the files <b>as they are</b>; the gap is the export's, not the page's.
        Logged as <code>ds-045</code> in <code>knowledge/_DS-IMPROVEMENTS.md</code> &mdash;
        re-exporting is the fix and it is not this page's to make.</p>
    </div>
  </section>

  <section id="inventory">
    <h2 class="t-ed-heading-4">Measured inventory</h2>
    <p class="t-ed-body-small lede">Read off the %d files at build time.</p>
    <div class="tablewrap">
      <table class="t-cm-legal">
        <thead><tr><th>File</th><th>Lockup</th><th>Ground</th><th>Ink</th><th>viewBox</th>
          <th>Bytes</th><th>Painted fills</th></tr></thead>
        <tbody>%s</tbody>
      </table>
    </div>
  </section>

  <section id="notes" class="notes">
    <h2 class="t-ed-heading-4">What the record says</h2>
    <p class="t-ed-body-small">Quoted or paraphrased from
      <code>knowledge/guidelines/logos.md</code>. <b>No usage policy is authored here.</b></p>
    <ul class="t-ed-body-small">
      <li>The detailed logo standard &mdash; usage, structure, behaviours, placement, clear space,
        minimum sizes &mdash; lives on <b>create.hsbc</b>, Foundations and identity &rsaquo; Logos.</li>
      <li>Source: HSBC Common Toolkit (MCP), Foundations &rsaquo; Logos page. Exported 2026-06-17
        by <code>knowledge/assets/logos/_export-logos.py</code>.</li>
      <li><b>No design tokens.</b> The Figma logos page carries none, and none of the %d files
        references one &mdash; which is why the tile grounds are literal.</li>
      <li>Per the icons sourcing rule these exports are <b>internal prototype assets</b>. For
        production and dev handoff, source official artwork from create.hsbc / the UI Centre.</li>
      <li>The crescent is an <b>Apollo-only</b> brand mark and is not part of this set.</li>
      <li>The monotone on-light artwork fills with <b>pure black</b>, not the project ink
        (<code>#1A1A1A</code>, blackest-never-pure-black), and the hexagon red is
        <b><code>#DB0011</code></b>, the brand primitive rather than the two-red law's UI ink.
        Both are brand artwork: <b>surfaced, never swapped</b>.</li>
      <li><b>Page-local styles only.</b> Dave parked structural bento components at #216, so this
        page mints no canon component and edits no canon rule.</li>
      %s
    </ul>
  </section>
""" % (len(rows), esc(SPAN_NOTE), len(rows), "\n".join("      " + t for t in tiles),
       len(rows), trows, len(rows),
       ("<li>⚠ <b>%d expected file(s) missing from disk</b>: %s. Reported, not drawn.</li>"
        % (len(residuals["missing"]), esc(", ".join(residuals["missing"]))))
       if residuals.get("missing") else "")
    return shell("Logos — Apollo library (Foundations)", "Logos",
                 "Foundations &middot; %d variants &middot; exported 2026-06-17" % len(rows),
                 body)


def build():
    prows, pmeta, presid = read_photos()
    lrows, lresid = read_logos()
    # #217 — THE THIRD FOUNDATIONS ENTRY, and the first one that is an INSTRUMENT rather than an
    # inventory: the s217-D5 bento option matrix, live. Its body lives in its own module
    # (gen_bento_matrix_217.py) because it is ~700 lines of controller; the WRITE stays here, so
    # showroom/_foundations/ keeps exactly one writer and one shell.
    mrows = matrix.content()
    pages = {
        "photography.html": photography_page(prows, pmeta, presid),
        "logos.html": logos_page(lrows, lresid),
        "bento.html": matrix.page(shell, mrows),
    }
    return (pages,
            {"photography": prows, "logos": lrows, "bento": mrows["photos"]},
            {"photography": presid, "logos": lresid, "bento": mrows["residuals"]})


# ---------------------------------------------------------------------------- selftest
def selftest():
    import gen_showroom as showroom
    fails, ran = [], []

    def bite(name, got, want):
        ran.append(name)
        if got != want:
            fails.append("%s\n     got:  %r\n     want: %r" % (name, got, want))

    pages, rows, resid = build()
    photo, logos = pages["photography.html"], pages["logos.html"]

    bite("1 · the pages sit OUTSIDE gen_showroom's prune glob (showroom/*.html)",
         [p for p in glob.glob(os.path.join(ROOT, "showroom", "*.html"))
          if os.path.basename(p) in pages], [])
    bite("2 · the pages sit OUTSIDE gen_library_214's component glob (same pattern)",
         os.path.dirname(os.path.join(OUTD, "photography.html")) !=
         os.path.join(ROOT, "showroom"), True)
    bite("3 · every foundation entry in the library's ONE list has a page here",
         sorted(f["file"] for f in library.FOUNDATIONS), sorted(pages))
    bite("4 · nothing is re-drawn — every asset is addressed, none inlined",
         ("<svg" in photo or "<svg" in logos), False)
    bite("5 · the lightbox ships ZERO JavaScript — popover + invoker commands only",
         ('command="show-popover"' in photo and 'commandfor=' in photo
          and photo.count("<script") == 1), True)
    # ⛔ INVERTED AT #217. This bite used to assert the bento stayed UN-MINTED (#216 posture).
    # s217-D2 promoted it, so the bite now asserts the RE-POINT: the pages must consume the
    # canon grammar AND must not have kept a private copy of the structure it replaced. A bite
    # that only checked for the canon class would pass with the old rules still shipping
    # underneath, which is the way a re-point silently becomes an addition.
    css = photo.split("<style>", 1)[1].split("</style>", 1)[0]
    _cssbody = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    # ⚠ Scoped to rules that TARGET a bento — the lightbox's own `display:grid` definition list
    # is not bento structure, and a blanket ban on the grid properties would have said so
    # falsely (caught on the first run of this bite).
    _bento_structure = [
        sel.strip() for sel, decls in re.findall(r"([^{}]+)\{([^{}]*)\}", _cssbody)
        if ("c-bento" in sel or "bx-" in sel)
        and re.search(r"grid-template-columns|grid-auto-rows|grid-auto-flow|gap\s*:|border-radius", decls)
    ]
    bite("6 · the pages CONSUME the canon bento (s217-D2), and declare no structure of their own",
         (("c-bento__grid" in photo and "c-bento__grid" in logos),
          ("bx-grid" in photo + logos + css),
          _bento_structure,
          bool(re.search(r"@container", _cssbody))),
         (True, False, [], False))
    pbody = photo.split("</style>", 1)[1]
    lbody = logos.split("</style>", 1)[1]
    # ⛔ THE DANGLING-VAR FENCE, and the SCOPE of it is the point. A page-local name declared in
    # this same stylesheet cannot dangle — it is defined two lines up. What CAN dangle is a
    # CANON property this page reads but does not own: rename it upstream, or land in a theme
    # that never defines it, and the page renders SILENT BLACK with no gate to catch it
    # ([[dangling-dataviz-var-renders-silent-black]]). So the bite is: every var() whose target
    # this stylesheet does NOT declare must carry a literal fallback.
    # ⚠ comments are STRIPPED first: the fence is about the rules that ship, and a `var(--x)`
    # quoted inside a `/* … */` note is prose. Measuring the raw string read the comment above
    # `.fx, header.app` and reported a dangle that does not exist.
    rules = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    declared = set(re.findall(r"(--[a-z0-9-]+)\s*:", rules))
    bare = sorted({m for m in re.findall(r"var\((--[a-z0-9-]+)\s*\)", rules)
                   if m not in declared})
    bite("7 · ⛔ no FOREIGN var() is read without a literal fallback (silent-black class)",
         bare, [])
    bite("8 · every photograph caption is the manifest's own text, never invented",
         all(esc(r["description"]) in photo or r["description"] == "UNKNOWN"
             for r in rows["photography"]), True)
    bite("9 · the full population is stated on the page, not just the derivative count",
         ("251 originals" in photo and "s217-D1" in photo), True)
    # ⚠ counted over the MARKUP, not the file: the shared stylesheet carries the two
    # `.lg-art[data-ground=…]` selectors on both pages, and counting those measured the CSS.
    bite("10 · logo tile grounds are LITERAL and pinned per variant, never a token",
         (pbody.count('data-ground="'),
          lbody.count('data-ground="light"'), lbody.count('data-ground="dark"')),
         (0, 6, 6))
    bite("11 · a dark mark never floats on a light ground",
         sorted({(r["ground"], GROUND_HEX[r["ground"]]) for r in rows["logos"]}),
         [("dark", "#1A1A1A"), ("light", "#FFFFFF")])
    bite("12 · ds-045 is reported on the page as a measured defect, not silently fixed",
         ("ds-045" in logos and "not this page" in logos), True)
    bite("13 · the theme broadcast is the showroom's, incl. the hashchange re-theme",
         all(s in photo and s in logos
             for s in ["data-apollo-theme", "data-theme", "hashchange", "chrome"]), True)
    bite("14 · the library's #chrome=0 embed contract is honoured (header hides)",
         'body[data-chrome="0"] header.app{display:none;}' in css, True)
    bite("15 · the embed contract this page answers still exists in gen_showroom",
         "h.chrome==='0'" in showroom.PAGE_TMPL, True)
    # ⚠ RE-BASED AT #217 on Dave's ruled thresholds (6.0 / 2.6 / 1:1.15, every 6th from tile 1),
    # which are NOT the ones this page carried before. The expectations below are hand-computed
    # against the ruling, not copied from the function's output — a bite that reads its own
    # subject cannot fail.
    bite("16 · spans are DERIVED from aspect ratio (canon s217-D2), never arranged by hand",
         [span_for(1600, 1067), span_for(1067, 1600), span_for(1000, 1000),
          span_for(795, 85), span_for(1400, 1000), span_for(170, 85), span_for(None, None),
          emphasise((1, 1), 1), emphasise((2, 1), 2), emphasise((1, 2), 7)],
         # 1.50:1 below 2.6 -> 1x1 · portrait -> 1x2 · square -> 1x1 · 9.35:1 -> 3x1 ·
         # 1.40:1 -> 1x1 · 2.00:1 below 2.6 -> 1x1 · unknown -> 1x1 · tile 1 promoted ·
         # tile 2 untouched · a TALL tile keeps its derived aspect even on the rhythm
         [(1, 1), (1, 2), (1, 1), (3, 1), (1, 1), (1, 1), (1, 1), (2, 2), (2, 1), (1, 2)])
    bite("17 · both pages stamp the foundations sentinel",
         (SENTINEL in photo, SENTINEL in logos), (True, True))
    # A hex list would rot on the next fallback edit and prove nothing about hue. This asserts
    # the PROPERTY instead: every colour this page authors is a NEUTRAL (channel spread ≤ 8),
    # so no red and no green can be authored here — the two-red law (s151-D1) and the mono
    # error-ink camp (s149-D1) are settled law about UI ink and are simply not reached.
    hexes = sorted({c.upper() for c in re.findall(r"#[0-9A-Fa-f]{6}", rules)})
    chromatic = [c for c in hexes
                 if max(int(c[1:3], 16), int(c[3:5], 16), int(c[5:7], 16))
                 - min(int(c[1:3], 16), int(c[3:5], 16), int(c[5:7], 16)) > 8]
    bite("18 · every authored colour is a neutral — no red, no green, the two-red law unreached",
         (chromatic, "#000000" in hexes), ([], False))
    bite("19 · every measured logo row reached the inventory table",
         all(r["file"] in logos for r in rows["logos"]), True)
    # --- s217-D3: the role re-point, and the half of the ruling it must NOT have taken ---------
    bite("21 · the photography wall names role=gallery and the logo wall names NO role",
         ('data-bento-role="gallery"' in photo,
          "data-bento-role" in logos),
         (True, False))
    bite("21b · the gallery wall is NOT squared, and its raggedness is REPORTED not repaired",
         ((resid["photography"] or {}).get("squaring", {}).get("exempt"),
          len((resid["photography"] or {}).get("squaring", {}).get("changed") or [])),
         (True, 0))
    # ⚠ THE POSITIVE HALF. Squaring OFF and aspect-mapping ON are DIFFERENT MECHANISMS, and the
    # failure mode of turning one off is quietly taking the other with it. A portrait derivative
    # must still reach the page as a two-row tile.
    bite("21c · portraits are STILL two rows tall — the squaring exemption did not take the "
         "aspect mapping with it",
         (any(r["orientation"] == "portrait" for r in rows["photography"]),
          all(r["span"] == (1, 2) for r in rows["photography"]
              if r["orientation"] == "portrait")),
         (True, True))
    # the caption's ruled numbers must come from canon, never be restated here
    bite("21d · the caption block height and clamp are canon's, not this page's",
         ("min-height" in rules.split(".px-cap{", 1)[1].split("}", 1)[0],
          "var(--bento-caption-lines" in rules,
          'class="c-bento__caption px-cap"' in photo),
         (False, True, True))
    # --- #217 · THE THIRD ENTRY: the s217-D5 bento matrix explorer -----------------------------
    # ⚠ The MATRIX's own rules are probed by gen_bento_matrix_217 --selftest (19 bites). What is
    # asserted HERE is only what this file owns: the shell, the wiring and the blast radius of
    # the extra_css/extra_script addition on the two pages that do NOT use it.
    bento = pages["bento.html"]
    bite("22 · the bento page is drawn through the SAME shell — theme broadcast, embed contract",
         all(s in bento for s in ["data-apollo-theme", "hashchange", 'data-chrome="0"',
                                  SENTINEL]), True)
    bite("22b · the extra-css / extra-script slots reach the bento page and NO other",
         (bento.count("<style>"), bento.count("<script"),
          photo.count("<style>"), photo.count("<script"),
          logos.count("<style>"), logos.count("<script")),
         (2, 2, 1, 1, 1, 1))
    bite("22c · the matrix declares its live controller and its export from ONE state object",
         ("__BM_STATE" in bento and 'id="bm-export"' in bento
          and 'id="bm-stage"' in bento), True)
    bite("22d · the types render as CANON'S ROLES, so no ruled behaviour is re-stated",
         sorted({v.split('"')[1] for v in re.findall(r'data-bento-role="[a-z]+"', bento)}),
         ["brochureware", "dashboard", "gallery"])
    bite("20 · residuals are declared, never defaulted away",
         (resid["photography"].get("missing_derivative_file"), resid["logos"]["missing"]),
         ([], []))

    if fails:
        print("gen_foundations_217 --selftest: %d BITE(S) FAILED" % len(fails))
        for f in fails:
            print("  ❌ " + f)
        sys.exit(1)
    print("gen_foundations_217 --selftest OK — %d bites." % len(ran))
    print("   photography: %d derivative(s) drawn" % len(rows["photography"]))
    print("   logos:       %d variant(s) drawn" % len(rows["logos"]))


def main():
    if "--selftest" in sys.argv:
        return selftest()
    pages, rows, resid = build()
    check = "--check" in sys.argv
    stale = []
    for name, content in sorted(pages.items()):
        path = os.path.join(OUTD, name)
        cur = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if cur != content:
            stale.append(os.path.relpath(path, ROOT))
            if not check:
                os.makedirs(OUTD, exist_ok=True)
                open(path, "w", encoding="utf-8").write(content)
    if check:
        if stale:
            print("gen_foundations_217 --check: OUT OF SYNC — %s\n"
                  "Run: python3 knowledge/_render/gen_foundations_217.py" % stale)
            sys.exit(1)
        print("gen_foundations_217 --check OK — %d page(s) in sync." % len(pages))
        return
    print("gen_foundations_217: %d page(s) -> showroom/_foundations/ (%d written)"
          % (len(pages), len(stale)))
    sq = (resid["photography"] or {}).get("squaring")
    if sq:
        # RATIFIED s217-D3 — and this wall is EXEMPT (role=gallery). Printed every run: an exempt
        # wall's raggedness is REPORTED as acceptable, and a non-exempt wall that could not be
        # squared is a DECLARED RESIDUAL, never a silent ragged edge.
        if sq.get("exempt"):
            state = ("EXEMPT (role=%s, s217-D3) — %s" %
                     (PHOTO_ROLE, "rectangular anyway" if sq["squared"]
                      else "%d hole(s) at %d columns, ruled ACCEPTABLE"
                           % (sq["holes"], sq["at_cols"] or PHOTO_LADDER[0])))
        else:
            state = ("squared" if sq["squared"] else "⛔ NOT SQUARE: %s" % sq["reason"])
        print("   squaring pass (RATIFIED s217-D3): %s — ladder %s, rows %s, %d tile(s) re-spanned"
              % (state, sq["ladder"], " / ".join(str(sq["rows"][c]) for c in sq["ladder"]),
                 len(sq["changed"])))
    print("   photography: %d derivative(s), residual missing-file: %s"
          % (len(rows["photography"]),
             resid["photography"].get("missing_derivative_file") or "none"))
    print("   logos:       %d variant(s), residual missing-file: %s"
          % (len(rows["logos"]), resid["logos"]["missing"] or "none"))


if __name__ == "__main__":
    main()
