"""#309 lane G - build up-is-bad.html: Metric's first three default tiles (rise, fall, no change) COPIED from
knowledge/snippets/Metric.reference.html (never retyped), shown as drawn and with the up-is-bad setting (s309-D5),
light and dark. Every style is canon's (.cn-metric) and type.css; the captions and bands are harness only."""
import re, pathlib
here = pathlib.Path(__file__).parent
snip = pathlib.Path("knowledge/snippets/Metric.reference.html").read_text()
body = snip[snip.index("<body"):]
sprite = re.search(r'<svg[^>]*>\s*(?:<!--.*?-->\s*)?<symbol id="metric-up".*?</svg>', body, re.S).group(0)
tiles = re.findall(r'(    <div class="metric" role="group".*?\n    </div>\n)', body, re.S)
pick = []
for want in ("metric-delta up", "metric-delta down", "metric-delta flat"):
    pick.append(next(t for t in tiles if want in t and 'class="metric-spark"' in t))
def row(cap, bad):
    ts = [t.replace('<div class="metric" role="group"', '<div class="metric up-is-bad" role="group"', 1) if bad else t for t in pick]
    cells = "".join(f'<div><p class="cap t-cm-legal">{c}</p><div class="cn-metric"><div class="board">\n{t}</div></div></div>\n'
                    for c, t in zip(("A rise", "A fall", "No change"), ts))
    return f'<p class="cap t-cm-caption">{cap}</p>\n<div class="trio">\n{cells}</div>\n'
bands = "".join(
    f'<section class="band" data-theme="{m}">\n<p class="cap t-cm-caption">Metric · {m}</p>\n'
    + row("As drawn: colour follows direction (the default)", False)
    + row("With the setting up-is-bad: a rise takes the fall ink, a fall the rise ink", True)
    + "</section>\n" for m in ("light", "dark"))
html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Metric - up is bad (#309 lane G)</title>
<!-- #309 lane G · s309-D5 (a metric may say up is bad) · s309-D6 (the no-change mark at full ink).
     Generated by build_up_is_bad.py from knowledge/snippets/Metric.reference.html (tiles copied, not redrawn);
     every style comes from knowledge/canon/canon.css (.cn-metric) and type.css. No live page uses the setting. -->
<link rel="stylesheet" href="../../../../knowledge/canon/type.css">
<link rel="stylesheet" href="../../../../knowledge/canon/canon.css">
<style>
  body{{margin:0; background:var(--background-default); color:var(--text-default);}}
  .band{{padding:32px 48px; background:var(--background-default); color:var(--text-default);}}
  .trio{{display:grid; grid-template-columns:repeat(3, 300px); gap:32px; margin-bottom:28px;}}
  .cap{{margin:0 0 12px; opacity:.6;}}
  .cn-metric .board{{display:block;}}
</style>
</head>
<body>
{sprite}
{bands}</body>
</html>
"""
(here / "up-is-bad.html").write_text(html)
print("tiles copied", len(pick), "bytes", len(html))
