#!/usr/bin/env bash
# run claude headless with project/memory/skill context stripped (CR #315 cold-run isolation)
exec env -u CLAUDE_PROJECT_UUID -u CLAUDE_PROJECT_TOOL -u SYSTEM_REMINDER_MEMORY_CONTEXT -u CLAUDE_CODE_POST_TURN_MEMORY -u CLAUDE_CODE_POST_TURN_MEMORY_CONFIG \
 -u CCR_SKILL_OVERRIDES -u CLAUDE_CODE_SYNC_SKILLS -u CLAUDE_CODE_SYNC_PLUGINS -u CLAUDE_ADDITIONAL_DIRECTORIES -u CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD \
 -u CLAUDE_CODE_CHILD_SESSION -u CLAUDECODE -u CCR_PRELOAD_CLAUDE -u CLAUDE_CODE_CCR_EARLY_PLUGINS_SYNC -u CLAUDE_CODE_CCR_EARLY_HYDRATE_PREFETCH \
 HOME=/home/claude/cr/home claude "$@"
