#!/usr/bin/env python3
"""#283 wrap, 4b — the FORWARD title only, GENERATED by `_gen_titles.py --session 283` and
written through the mover. The RENAME is delivered in chat and never written here (RULED #28)."""
import sys
from run_ops import run

OLD = "> **TITLE THE NEXT CHAT →** `Apollo - #283: the logo masters and the third dial`"
NEW = "> **TITLE THE NEXT CHAT →** `Apollo - #284: the logo masters, at last`"

OPS = [{"op": "replace", "file": "GOOD-MORNING.md", "find": [OLD], "replace": [NEW]}]

if __name__ == "__main__":
    sys.exit(run("title", OPS, write="--write" in sys.argv, min_bytes=100))
