#!/usr/bin/env python3
"""#283 wrap, 2d — demote #282's ⏱ LATEST DELTA to ⏱ PRIOR and insert #283's, through the mover.
Stack after this op: LATEST #283 + PRIOR #282 + PRIOR #281 = LATEST + 2 PRIOR, the 2d contract.
"""
import sys
from run_ops import run

OLD = ("## ⏱ LATEST DELTA — 2026-09-18 (Fri from `date`) (**#282**, ⚠ **TWO DAYS — opened 2026-09-17, "
       "the last seven commits and this ritual 2026-09-18**, conductor **FABLE 5.1**, **3 OPUS LANE SEATS**, "
       "with this **OPUS 5** wrap sub, DELEGATED — ★★ **THE RULE NOTES LAND, THE LOGO IS RULED, AND THE "
       "GRAPH'S PHILOSOPHY IS PUT**)")
NEWHEAD = OLD.replace("## ⏱ LATEST DELTA", "## ⏱ PRIOR DELTA", 1)

BLOCK = [
"## ⏱ LATEST DELTA — 2026-09-18 (Fri from `date`) (**#283**, ✅ **ONE DAY, NO DATE SPLIT**, conductor **FABLE 5.1**, **NO LANE SEATS — none were cut**, with this **OPUS 5** wrap sub, DELEGATED — ★★ **THE SEAM CHECK IS BORN AND STOPS ITS OWN SESSION; THE DISK IS DIAGNOSED**)",
"",
"*(WHY/HOW: `_DECISION-HISTORY/2026-09-18-283-the-seam-check-is-born-and-the-disk-is-diagnosed.md`. #283 is the session that built an instrument in the morning, was stopped by it in the afternoon, and spent the middle of the day finding out why the disk was full. It ruled once and cut no lanes, and both of those are the point rather than a shortfall.)*",
"",
"- ⛔★★★ **READ `_HANDOFF-134-the-seam-check-is-born-and-the-disk-is-diagnosed.md` FIRST — IT IS NEWER THAN `_CHAIN.md` AND OUTRANKS IT.** It does **NOT** replace `_HANDOFF-130`, `-131`, `-132` or `-133`: every open item on those still stands, and **nothing on them was closed today**. Dave's words verbatim, with the later disk sentences appended at this wrap: `notes/_lanes/283/DAVE-RULINGS-2026-09-18.md`.",
"- ★★ **ONE RULING, 619 → 620, VERIFIED BY SPAN AND NOT RESTATED.** `git show --numstat 107aa44 -- knowledge/_rulings.json` reads **`15  0`** — insertions only, zero deletions — and `json.load` counts **620**. **`s283-D1`** (conductor's own commit): **the lane-seam check is STANDING, every session** — `python3 knowledge/_seam.py` before every lane is cut and after every lane lands, **its FILL line quoted in chat verbatim** against stop **180,000** / tolerated **220,000** / hard **256,000**; the same call reads DISK and cleans the session's own scratch with `/tmp/gitshim` on a keep-list. ⚠ **ADVISORY; blocking is his.** ✅ **`notes/_RULINGS.html` was re-rendered FRESH inside that same commit (`28  10`)** — the #281/#282 stale-page pattern did NOT get a third instance, and `_render_rulings.py --check` reads **FRESH** at this seat.",
"- ★★★ **THE INSTRUMENT FIRED AT ITS FIRST REAL SEAM AND THE CONDUCTOR OBEYED IT — 210,476 real at turn 43, and the per-size logo-masters lane was NOT cut.** That is why the 40 masters are still #284's first move. ⛔ **It is the ruling working, not the session failing**, and it is the first time on the record that a session stopped itself at a seam. ⚠ **n=1. One obeyed advisory is a data point, not a trend** — the three-breach arc (#277 crossed under pressure · #281 read the gauge and overruled it · #282 did not read it at all) is not withdrawn by it, and **what a session should DO at the hard wall is still Dave's question**, put for the fourth wrap running.",
"- ⛔★★ **THE DISK IS THE SESSION'S SECOND STORY AND IT IS FINDINGS — HIS TO RULE ON.** **(a)** The #227/#228 fix **HELD**: `/var/tmp` is empty and the hygiene gate did its job; the record shows the disk clearing exactly twice (#233, and the night before #282), **both times by an external rebuild after hitting 100%, never by anything in the repo**. **(b) Today's cause was OURS — the repo was 9.3 GB on a 9.8 GB disk**: `knowledge/assets/assets (5).zip` **2.5G** duplicating `photography/` 2.5G (both gitignored) · `.git` **2.6G** — **28,991 loose objects never packed against a 63 KB pack, plus 745 `tmp_obj_` stubs (120 MB) from the index-lock class** · `outputs/_render-env-229` **482M** · `_to_delete/` **133M** · three zips 60M. **(c) Dave fixed it on his own Mac, instructed step by step** — two Finder moves and one line, `git gc --prune=now && find .git/objects -name 'tmp_obj_*' -delete` — and it is measured, not assumed: **repo 4.3 GB · `.git` 576 MB · `count-objects` count 0 / size-pack 575,855 KB / garbage 0**, `git status` unchanged, **photography originals kept** (the manifest reads them). ⛔ **(d) AND THE DISK DID NOT RELEASE: 9.1G used / 136 MB free after a FULL app restart** (VM `uptime` 1 min, the same 127 dead session dirs). `/sessions` is a **persistent ext4 volume**; the 4.8 GB residue is **127 `drwxr-x--- nobody:nogroup` session homes, mtimes Sep 9–15, unreadable and unremovable from any session uid, with no `sudo`** — **every session AND every sub-lane gets one**, ~38 MB of pip installs and tokenizer cache each, and the rebuild appears to trigger **at 100%, not on a schedule**. ⛔ **NOT fixable from inside and NOT fixable from his Mac.** His options, neither taken here: **thumbs-down feedback to Anthropic naming the dead-home leak**, or **wait for the next rebuild — now worth ~5 GB of headroom instead of 500 MB, because the repo shrank**. **(e) The one lever inside was pulled** (`85aee08`): `_gate_scratch_hygiene.py` gained SCRATCH_ROOTS `~/tmp` + `~/.cache`, `WRAP_ONLY_ROOTS` `~/.local` under `--wrap`, and **`KEEP = /tmp/gitshim`**.",
"- ✅ **THE 4c/STEP-5 COLLISION #282 MEASURED IS CLOSED, AND VERIFIED AT THIS SEAT RATHER THAN TAKEN ON THE COMMIT MESSAGE.** `_gate_scratch_hygiene.py --clean --wrap` at step 4c removed two entries (`~/tmp/data-gym-cache`, `~/.local/lib`) and printed **`/tmp/gitshim  → KEPT (keep-list)`**; the shim survived and step 5 ran with it. ⛔ **AND THE SIBLING FINDING IS THE ONE WORTH CARRYING: #282's filed report states the collision *\"is now in `_CARRIES.md`\"* and a probe of § `residual → #283` at this seat finds NO item mentioning `gitshim` or step 4c at all.** The collision survived one wrap on a CLAIM rather than on a carry, and it is closed today only because the conductor fixed it from a different direction. ★ **The 2c EXIT CHECK tests PRESENCE for items it can SEE; an item that was never written is invisible to it** [[instrument-without-a-consumer]]. Minted as a NEW carry at `_CARRIES.md` § `residual → #284` ③. ⚠ **The git-lock runbook line itself is UNTOUCHED and still his**, ageing at `[1]`; today's data point on it is that **the shim dies with every VM rebuild** (it was gone at this session's open, after Dave restarted the app) **while the commit script survives without it and leaves an unlinkable `index.lock` warning each time** — `107aa44`, `85aee08`, and this wrap's own commit.",
"- ⚙ **GAUGE, MEASURED AT THIS SEAT against the conductor's own transcript** — the session's top-level window, this wrap seat being a subagent log beneath it, which is what makes the subtraction legal: **FILL 226,084 real over 53 turns** against **221,028 real / 51 turns DECLARED** at the brief cut ⇒ **delta 5,056**, and **both readings describe the same window**, which is the one condition under which that subtraction means anything [[measure-dont-convert-units]]. ⛔ **6,084 OUTSIDE the ≤220,000 tolerance and 46,084 past the ruled 180,000 stop line.** ✅★★ **THE 256,000 HARD LINE WAS NOT BREACHED — the first session in four to stay under it**, with 29,916 to spare. The conductor NAMES the cause rather than leaving it to be inferred: **the disk investigation, where one `git count-objects -vH` printed 745 `tmp_obj_` garbage lines (~60K real) that should have been piped through `grep`**. **BOOT 80,871 real, n=1** against the `s129-D1` floor 70,794 — **+10,077, NOT a re-base**, `BOOT_FIRSTTURN_TK` untouched, n=1 published as n=1, agreeing with the brief to the token — and it is the **EIGHTH** post-diet reading over `BOOT_CEILING_TK` **70,000**. ⛔ **Cutting the boot is his word; raising the literal is forbidden** (`s240-D2`/`s241-D1`, shrink-only) [[gate-must-quote-what-it-forbids]]. ⛔ **NO `subs` LINE IS WRITTEN — no lanes were cut, sub-tokens are 0 across n=0**, and `s214-D5`'s rule against defaulting an absence into a number holds for a zero exactly as it holds for an unknown. ⛔ **NO PACE PANEL WAS ASKED FOR AND NONE IS INVENTED.** ⛔ **`/sessions` 98.6%, 139,712 KB free, measured here.**",
"- ⛔ **SIX BLOCKING GATE FAILS ARE CARRIED IN THE `#243` DECLARED NOT-A-WRAP FORM — THE NINTH CONSECUTIVE WRAP ON THAT PATH.** Every one is another session's append-only testimony in `notes/_GAUGE-LOG.md`: the **boot-drift CEILING BREACH** (7 post-diet readings over `BOOT_CEILING_TK` 70,000 — #275 82,485 · #276 82,494 · #277 83,636 · #278 72,110 · #279 72,447 · #280 75,740 · #281 77,400) and **five boot double-counts** (#243, #264, #272, #273, #274). ⛔ **A wrap may not repair an inherited gate fail**, and this one did not try. ⚠ **A SEVENTH STOOD AT THE OPEN AND WAS THIS SEAT'S OWN — the retrieval index STALE against GM/LS, the #32 defect exactly — CLOSED at 2g, which is where the ritual puts it.** ⛔ **`_validate_roles_resolve.py` READS FAIL(6) and `_validate_lane_ownership.py --selftest` READS 2/3, both INHERITED**; `showroom/` holds **138** top-level `.html` against an inscribed *\"108 stale\"* — both readings stand, neither is rewritten, and it is HIS call. The `SHOWROOM_ACK` this wrap's commit passes acknowledges that standing gap and does not repair it.",
"- ✅★★ **CLOUD MEMORY (step 3) WAS WRITTEN FROM THIS WRAP SUB'S OWN SEAT — n=5, THE FIFTH CONSECUTIVE WRAP TO MEASURE THE RUNBOOK'S \"STRUCTURAL\" SEAT LIMIT FALSE.** `wrap-283-the-seam-check-is-born-and-the-disk-is-diagnosed.md`, **5,118 B**, version `cc777c756e4c`; the index line inserted **newest-first above the #282 line**, `index.md` now **16,099 B of the 49,152 B cap** (32.8%), version `3a4141ab1570`. **The hook was written FIRST regardless** (`notes/_lanes/283/WRAP-MEMORY-HOOK.md`) with the result recorded at its foot, and ⛔ **no placement is owed at the #284 opener.** ⛔ **The runbook's step-3 line still says the store is unreachable from this seat and is NOT edited here — amending a ratified step is Dave's word**, now at its fifth counter-measurement. ★ **Repo is the record, memory is the accelerator — UNCHANGED.**",
"- ⚠ **DECLARED SKIPS AND NOT-DONE AT THIS WRAP, EACH WITH ITS SIZE** (declare-last, and the size is the point). **2c, 2d and 2f ALL RAN, every move through `knowledge/_gm_move.py`** from session-owned, uniquely-named ops files asserted with `os.path.exists` + a size floor IN THE WRITING PROCESS, dry-run first, receipts read back: the **#281 ★ PRIOR banner (12 lines)** rolled to `_GM-ARCHIVE.md` § Batch 2026-09-18 #283 · the **#280 ⏱ PRIOR DELTA (18 lines)** and **#279's `Previous:` chain segment (4,796 chars**, span reconstruction asserted before anything was written) to `_LIVE-STATE-ARCHIVE.md` § Rolled 2026-09-18 #283 · the **#282 stratum** to `notes/_GAUGE-LOG.md` via `roll_2f`. **2e was a NO-OP, 0 lines** — DO-FIRST minted no notice, tombstone or lifecycle tag and nothing was retro-tagged. **2g ran LAST**, after every GM/LS edit was final. ⛔ **NOTHING WAS DROPPED FOR BEING OLD, and the 2c/2d/2f EXIT CHECK is recorded rather than asserted** at `notes/_lanes/283/W/WRAP-REPORT.md`, which also holds the `s271-D4` re-read.",
"- ⚠ **THE CARRY SET IS `_CARRIES.md` § `## residual → #284` (`s225-D2`) — 538 probeable items, THREE new, ZERO strikes.** The ages all moved by one; **no #283 ruling retracted or corrected the CLAIM of any carried item**, so none was struck — `s183-D1`/`s188-D2` license a wording change ONLY to record a retraction, and **a strike that is wrong is worse than an item that is merely stale**. The three new items: the **disk** · the **session that stopped at its own seam check** (a data point beside the hard-wall question, which ages untouched at `[1]`) · the **4c/step-5 collision and the carry that was never minted**. ⚠ **3 NEW INVISIBLE TO THE PROBE, sixth wrap running** — `_AGE_RE` misses `[NEW — 0]`, and the probe reads 538 because #283's seven new items became `[1]` and entered it.",
"",
]

OPS = [
    {"op": "replace", "file": "_LIVE-STATE.md", "find": [OLD], "replace": [NEWHEAD]},
    {"op": "insert", "file": "_LIVE-STATE.md", "at": NEWHEAD, "where": "before", "lines": BLOCK},
]

if __name__ == "__main__":
    sys.exit(run("lsdelta", OPS, write="--write" in sys.argv, min_bytes=4000))
