#!/usr/bin/env python3
"""#311 lane P — write the draft #312 lane briefs, one per job, from the plan page's jobs."""
import pathlib
ROOT = pathlib.Path(__file__).resolve().parents[4]
COMMON = """
## Hard rules (every lane, every seat)
- Repo: `$HOME/mnt/Projects--UX-design` on Dave's Mac through `mcp__remote-devices__device_bash` (never `UX-design--UX-design`); `timeout_ms` up to 178000 on long calls. Text-only lanes may run in the cloud workspace on a /tmp clone; anything that renders runs at the seat: `export TMPDIR=/dev/shm; bash knowledge/_render/ensure_env.sh; source knowledge/_render/seat_env.sh`, drivers with `executable_path=$RENDER_SHELL` (`_drive_chart_engine.py` needs the wrapper `outputs/310/A/drive_wrap.py` until job B fixes its channel).
- Never `git status`. Never `rm` in the mount (`/tmp` is fine, and you MUST clear your own /tmp clone when done; two clones at once is the seat's ceiling, root has 3.7G free). No push: the conductor pushes and reads CI back. Never read or write claude.ai Project memory.
- Commits only by the commit seat named in this brief: `SESSION_N=312 bash knowledge/_git_commit.sh --reconciled --quiet <fresh msgfile> <named paths>` (line 1 WITHOUT a `#312 date —` prefix; named, changed paths only, never a no-op `git add`; re-run with the Memento schematic if it regenerates; msgfile ends with the Co-Authored-By and Claude-Session lines the conductor gives you). After every gate run: `python3 knowledge/_wrap_commit.py unlock --tag 312-<seat>`.
- Pre-push routine before handing paths to the commit seat (worker checklist step 5, `s309-D7`): a /tmp clone, the chunked survey 1:12, 13:55, 56:140, 141:167 with `--include-mutating`, `test_gates`, `_validate_evidence`, the sliced state-contrast sweep when snippets or canon change (about 2 min a slice, three or four slices per call). Never survey on the mount.
- Single writers: `knowledge/canon/canon.css`, the 27 chart receipts, `knowledge/_state.json`, `knowledge/_rulings.json` = job A's commit seat only (it runs the regen serial once per wave; lanes never regenerate). `knowledge/components/*.meta.json` + `meta.schema.json` = job C's schema lane (morning) then job D's consumers lane (afternoon). `_edge_register.json`, `_kg_verbs.json`, `_validate_edges.py`, the explorer builder = job D. `knowledge/_wrap_*.py` + the capture-ritual runbook = job E. `apollo-launchpad/` = job C. `apollo-spider/dist` = job G. Anything else you need to touch that is not yours: stop and say so in your report.
- An inscription is not done until `python3 knowledge/gen_kg_titles.py --write` and `python3 knowledge/_render_rulings.py` run and commit with it. Adding or removing a component meta means re-basing ASSERT-009 in the same change (`notes/_lanes/309/cond/assert009_rebase.py`). A regen that appends to `knowledge/_graph-mark-observations.jsonl` commits it with the schematic. `_build_survey.py` appends to `notes/_BUILD-VERDICT-LOG.jsonl`; restore it from HEAD before any regen. `gen_kg_sources.py` is not in `_wrap_regen.py`'s serial: after meta changes run `--check`, then `--land --ratified s305-D26`.
- Dave rules from plain prose and pictures, never ID codes. Nothing a lane builds "stands" until he has looked where this brief says so; nothing is inscribed without his word. Cite a source for every claim; a number is pasted from a run or not written.
- File your report at `notes/_subreports/2026-10-01-312-<lane>-<topic>.md` with a `COUNTS:` line, a `## Found, not fixed` section and a `## Ruling-shaped questions` heading (even if empty), and a born-closed store row (`s305-D40` form, see W-311a1 in `knowledge/_state.json`; use `_state.add()` via `_state.load()/save()` — `json.dumps(indent=2, ensure_ascii=False)+'\\n'` round-trips the file byte-exact). The conductor reads only your `COUNTS:` line and headline: put the verdict there.
"""

JOBS = {
'A': dict(title="The 78's work, wave one — the shared stylesheet first, then the charts, the dashboard and the settles",
  ask="""Dave answered all 78 reopened questions by hand on Mon 2026-09-28 (`notes/_lanes/307/DAVE-RULINGS-2026-09-28-reopened-78.md`, inscribed `s307-D1..D78`). 42 of those rulings still read `ruled` in `knowledge/_rulings.json` tonight and 38 Claude-owned work rows (`W-307q*`, `W-307y*`) are open. Build them in the proposed order (`_CARRIES.md` § residual → #311, age 3, "does he take the conductor's order?" — he has not said no; the conductor takes it unless his morning message says otherwise).

Order: (1) the shared stylesheet rebuilt so pages carry no sizing rules, together with "link, don't paste" so both checks agree (`s307-D75`/`W-307yd`, `s307-D74`/`W-307yc`); (2) the chart rows `s307-D58..D65` (`W-307qz` stacked area converted, `W-307y1` the category cap now and the expandable Other after, `W-307y2` keep the 200px floor + register the chart template in full, `W-307y3` the butterfly join, `W-307y4` every chart page under every rule, `W-307y5` bullet and candlestick, `W-307y6` the #245 L2-populate recommendations + the 14-chart move); (3) the dashboard rows (`W-307y8` cap the above-the-fold signals at 26 @1440, `W-307y9` bring back all eight of Dave's improvements, `W-307ya` the fold row, `W-307yb` principles Q8–16 matched to the 29 enacted); (4) the settles he handed to Claude within his rules (`W-307q2`, `q5`, `q8`, `qa`, `qb`, `qc`, `qd`, `qe`, `qf`, `qg`, `qh`, `qj`, `qk`, `ql`, `qm`, `qn`, `qo` the 4px audit, `qp`, `qq`, `qs`, `qt`, `qv`, `qx`, `qy` is job B's, `ye`). Lane D's six that need his word (`notes/_subreports/2026-09-28-307-D-quick-18.md`) go to job F's page, not here.

Chore lane, Sonnet: the hit-area advisory regenerated on today's 137 snippets and `_validate_hit_area.py` wired into the CI render job for real (`_HANDOFF-161` item 8: `gates.yml` never names it, its only run is a browserless step); the status stamps the store is behind on — `s308-D16..D19` (built `a7742aee`, `6bb91a0b`), `s308-D39..D44` (built #309 `94ba3c73..bba80abd`), `s310-D2` (built `7bc6b0c5`) stamped enacted with those shas via `_inscribe_ruling.py --set-status`, each checked against the tree first, never by assertion.""",
  lanes="""- A1 · Opus 5.5 · the shared stylesheet + link-don't-paste (`W-307yd`, `W-307yc`). Owns the dashboard shared CSS and the two checks. Goes first; A2–A4 rebase on its paths.
- A2 · Opus 5.5 · charts, family one: stacked area conversion, category cap, template registration (`W-307qz`, `y1`, `y2`).
- A3 · Opus 5.5 · charts, family two: butterfly join, every-page-every-rule, bullet/candlestick, the 14-chart move (`W-307y3`, `y4`, `y5`, `y6`).
- A4 · Opus 5.5 · the dashboard rows (`W-307y8`, `y9`, `ya`, `yb`).
- A5 · Opus 5.5 · settles, components (`W-307qh`, `qj`, `qk`, `ql`, `qm`, `qn`, `qq`, `qs`, `qt`, `qv`, `qx`, `ye`).
- A6 · Opus 5.5 · settles, build and pack (`W-307q2`, `q5`, `q8`, `qa`, `qb`, `qc`, `qd`, `qe`, `qf`, `qg`, `qo` the 4px audit, `qp`).
- A7 · Sonnet · the chore lane (hit-area, stamps).
- AC · Opus 5.5 · THE COMMIT SEAT for jobs A and B: collects named paths, runs the regen serial whole and in order, re-drives the 27 chart receipts when canon moves, restores the verdict log, surveys in a /tmp clone, one commit per wave (midday, evening), hands the sha to the conductor for the push.
- AV1, AV2 · Fable · verifiers at midday and evening; built nothing; for every ruling stamped enacted this wave, find it in the tree and try to make its gate pass with the change reverted. PASS / PASS WITH FIXES / FAIL per ruling.""",
  dave="The order, by 07:30 (silence = the proposed order). Then one review page in the evening: before/after renders for the chart and dashboard rows and the four 'show me' items (`s307-D38` four dark captions side by side, `D49` the tree mark, `D51` the transaction row as a list-items variant, `D53` the five parts and the reasons). Page shell: copy `notes/_REVIEW-311-B-icons-and-supercharge-page-2026-09-30-v1.html` (new localStorage key), pictures inline as `<img>` only, published into the artifact \"Apollo 304 review\" by the conductor.",
  done="Every ruling in scope reads `enacted <sha>` with a receipt, or is named in `## Found, not fixed` with why; rows closed by addition with receipts; the survey green in the clone on the wave sha; CI read back green by the conductor."),
'B': dict(title="The reworks from his picture page — nine parts, the third red, the 29 forks, the loose ends",
  ask="""`s308-D1..D15` (his 08:05 export `notes/_lanes/307/DAVE-RULINGS-2026-09-29-what-you-asked-to-see.md`, inscribed by `notes/_subreports/2026-09-29-308-I-inscribe-15.md`) left twelve work rows, none built:
- `W-308i1` the tree's chosen mark per theme (red in Supercharge and Common, black in Console and Mono); `W-308i2` the today ring inside the chosen square on the calendar, the date picker follows; `W-308i3` the standing-order / Direct Debit row as a list-items variant; `W-308i4` the range slider as Slider's two-handle form; `W-308i5` the rating reworked, not deleted; `W-308i6` the transfer list reworked then promoted; `W-308i7` the split button promoted; `W-308i8` the floating add button reworked then promoted, its three stray body rules in canon.css repaired (`W-307qy`, `s307-D55`); `W-308i9` back to top's reference page reworked then promoted.
- `W-308ia` the third red in mono, #A8000B, investigated on its own (not folded).
- `W-308ib` the 29 colour forks settled within his rules, each checked for halation and contrast (`reviews/_rag_bloom_model.py`; load it as `notes/_lanes/310/C/bloom_options.py` does). Anything not settleable within a ruling on record comes back as a question on the page, not a change.
- `W-308ic` the cold run's three fixes (the rerun itself is job G's).
Loose ends found and not fixed this week, one lane: the banking demo's filters onto one row (`.ftb-row` → `.ftb-primary`, `W-309g3`); the receipt page's blank arrow (`#metric-up` undefined), missing chart script and the splice markers that drop a rule each (`W-309g4`; the one-tile group is his, leave it); the masthead search/account buttons without `.nv-btn` (0×0 SVGs); Template-error's hard-coded `--surface:#1F1F1F` in dark; `snippet_theme_css()` cannot project an option so the showroom panes cannot show one; `_drive_chart_engine.py` hard-codes `channel="chromium"` (take the seat's `$RENDER_SHELL`); the avatar disc 1.03:1 on grey tiles; an `add` subcommand for `knowledge/_state.py` so rows stop being hand-inserted. Sources: `notes/_subreports/2026-09-30-311-A-*.md` and `-311-B-*.md` § Found, not fixed; `_HANDOFF-161` items 3 and 7.""",
  lanes="""- B1 · Fable · tree mark + today ring (`W-308i1`, `i2`), Calendar and Date picker snippets only.
- B2 · Fable · list-items variant for the standing-order row + the rating (`W-308i3`, `i5`).
- B3 · Fable · range slider + transfer list (`W-308i4`, `i6`).
- B4 · Fable · split button, floating add button (+ the three stray rules), back to top (`W-308i7`, `i8`, `i9`).
- B5 · Fable · the 29 forks (`W-308ib`), a table with the pick, the rule cited and the bloom score per fork.
- B6 · Opus 5.5 · the third red (`W-308ia`) and the cold run's three fixes (`W-308ic`).
- B7 · Opus 5.5 · the loose ends lane.
- BV · Fable · verifier: every reworked part rendered in four themes at the seat, before (HEAD~) and after, the manifest contrast pairs re-checked, the promoted parts' registrations checked, canon.css diff explained line by line.
Commit seat: job A's (AC). Lanes hand named paths; they never regenerate canon.""",
  dave="One review page in the evening: every reworked part before and after in the themes where the theme matters, a does-it-stand call each, the forks table, the third-red finding. Nothing stands until he has looked (`s308-D8..D11`: promotion waits on his eye). Same shell and publish route as job A's page.",
  done="Nine parts reworked and rendered; the forks table complete with a pick or a question per fork; the loose ends fixed at source (each with its own line in the report); rows stay open until his eye except the loose ends, which close with receipts."),
'C': dict(title="Launchpad, day one — the schema calls in the tree, then the catalogue, gates as a service and the chooser",
  ask="""Ruled: route B (`s305-D45`), the PoC scope as written (`s305-D46`: the landing dashboard, about 15 parts, mock data, four best-guess roles, two hosts, a record per screen, Jev as a switch off by default `s305-D47`), the name Launchpad under an Apollo eyebrow (`s305-D48`, and off shared material: `W-305n6`, his surprise), money screens data-only (`s305-D49`), the start in October once schema calls 14–19 are in the tree (`s305-D50`), the delivery order hosts first (`s305-D51`), the build-ready test (`s305-D53`). The page: `notes/_PROPOSAL-apollo-mcp-2026-09-26-v2.html` § The proof of concept and § The build path. The probe: `notes/_subreports/2026-09-26-304-R5-mcp-probe.md` (137/137 metas yield an A2UI v0.9.1 entry, 17 ready for run time). The roadmap's October half: `notes/_PLAN-304-roadmap-and-weekend-runs-2026-09-26-v1.html`.

Morning, first: `s305-D17` (a part's own text is a field on the part, not a separate text part), `s305-D18` (four parts side by side are held by the bento wall with a tiles slot that accepts parts by what they provide), `s305-D19` (one rule: data is a setting bound to a data shape; a slot holds parts) and `s305-D58` (the four setting-or-slot names as decided) enacted in `knowledge/components/*.meta.json` and `meta.schema.json`, the schema selftest extended, ASSERT-009 re-based only if a meta count moves, stamped with the sha. Read `s305-D15`/`D16` (enacted) for the form.

Midday, after the schema commit: step one, the catalogue generator (`apollo-launchpad/catalogue/`: from the metas of the ~15 dashboard parts to A2UI v0.9.1 entries with their when-rules, versioned like an API); step three, gates as a service (`apollo-launchpad/gates/`: the existing static checks in `knowledge/_validate_screen.py` and the composition/geometry gates taking a screen in memory and returning a verdict, served as MCP tools over stdio; the render leg deferred, its time measured); step four, the chooser (`apollo-launchpad/chooser/`: a fixed evaluator over the when-rules and the four mock roles' tool grants, returning eligible parts with reasons, with a ranker seam Jev could plug into — Jev itself off and untouched, `s294-D10`). Stretch: step two, the renderer grown from `knowledge/canon/dv-render.js` turning an A2UI screen into canon markup. Nothing in the pack's ship set changes; no new build step is wired.""",
  lanes="""- C0 · Opus 5.5 · the schema lane, 07:30: D17, D18, D19, D58 in the metas and the schema; owns `knowledge/components/*.meta.json` + `meta.schema.json` until its commit (job D's consumers lane waits for it). Paths to the commit seat AC for the midday wave.
- CS · Fable · the build spec, 07:30 (cloud): one page the three build lanes build to — the catalogue's shape for the fifteen parts, the tool surface (names, scopes, the four roles at the tool call, the £500,000 mock limit), the record per screen, the folder layout, the tests each step must pass. Reads the proposal and the R5 probe; invents nothing the proposal did not say.
- C1 · Fable · step one, the catalogue generator (midday, cloud, on the schema sha).
- C3 · Fable · step three, gates as a service (midday, cloud).
- C4 · Fable · step four, the chooser (midday, cloud).
- C2 · Opus 5.5 · step two, the renderer spike (midday, seat for the render check). A stretch: nothing depends on it.
- CV · Fable · verifier, evening: runs the worked example (treasurer and operations analyst, "what needs my attention this morning?") through C1+C4, a bad screen through C3, and reports what proved and what did not. Commit seat AC, evening wave, paths under `apollo-launchpad/` and the C0 metas only.""",
  dave="None tomorrow. A short page in the evening (read, not rule): the worked example as far as it ran, two catalogues with reasons, one gate verdict on a screen in memory, what step two still needs. The name Launchpad never appears on anything shared; the folder name is fine.",
  done="D17/D18/D19/D58 read `enacted <sha>`; `apollo-launchpad/` holds steps one, three and four with selftests green; the verifier's page says what proved; the PoC's estimates in the proposal re-priced from what one day measured."),
'D': dict(title="The edge register, items 5 to 9, and the three tools that should read it",
  ask="""He took all nine edge-definition items (`s308-D16..D28`, `notes/_REVIEW-308-edge-questions-2026-09-29-v1.html`, his 09:26 and 12:13 answers). Lane E built items 1–4 (`a7742aee`, `6bb91a0b`): `knowledge/_edge_register.json` with 65 types, the ends check in `_validate_edges.py`, one direction stored, each type's shape. Owed rows: `W-308ii` one why field required by type (`s308-D20`); `W-308ij` one maker field on every edge replacing authored (`s308-D21`); `W-308ip` the outside-term column beside Apollo's word, the neatest name winning outright (`s308-D22`, `D27`, his "Lets do what is neatest"); `W-308il` the two ruling-to-ruling vocabularies folded into one with conflicts-with (`s308-D23`); `W-308iq` + `W-308in` the five new edges a–e, replaced-by on components and tokens with the version it happened, and a theme node kind (`s308-D24`, `D28`); `W-308ie`'s tail: the meta schema, the verbs map (`_kg_verbs.json`) and the explorer (`_build_kg_explorer.py`) read the register instead of keeping copies. After the edges land: re-run the hand-run Jev link check (`notes/_jev-link-check/jev_link_check.py`, `s305-D55`; never a gate) over the new types so his list of links that look wrong is current, and rebuild the explorer at the seat (107 s).""",
  lanes="""- D1 · Opus 5.5 · why + maker fields, the ends check extended, every existing edge migrated by rule with its maker named (`W-308ii`, `ij`).
- D2 · Opus 5.5 · the outside-term column and the folded ruling-to-ruling vocabulary with conflicts-with (`W-308ip`, `il`).
- D3 · Opus 5.5 · the five new edges, replaced-by with version, the theme node kind (`W-308iq`, `in`).
- D4 · Opus 5.5 · midday, after job C's schema commit: the three consumers read the register (`W-308ie`); owns `meta.schema.json` from then.
- D5 · Sonnet · evening: the Jev re-run (needs the key; stops by name without it, exit 3) and the explorer rebuild; the observations jsonl committed with the schematic.
- DV · Fable · verifier: plants one bad edge per new rule and one good edge per type, expects each caught or kept; explains the node and edge count deltas line by line.
Commit seat AC; paths under `knowledge/_edge_register.json`, `_validate_edges.py`, `_kg_verbs.json`, `gen_kg_*`, `_build_kg_explorer.py`, `notes/_KG-EXPLORER.html`, `_graph-mark-observations.jsonl`.""",
  dave="None. Every item is his click already. The Jev list of links that look wrong is filed for whenever he wants to look; nothing in the graph changes on Jev's word.",
  done="The register carries why, maker, outside term, folded vocabulary, the five edges and the theme kind; the three consumers read it (their copies deleted or generated); the explorer rebuilt; the Jev list current; every W-308i* row above closed with a receipt."),
'E': dict(title="The wrap redesign, phase 3 — one story written once, every view generated",
  ask="""His ask of 2026-09-21 (a faster wrap) became the redesign ruled Mon 2026-09-28: `s306-D4` (the wrap writes the story once, as story plus measured figures; every other view is generated), `s306-D5` (the generated wrap report is the filed report), `s306-D8` (the carried list carries only what changed: new, struck, aging), `s306-D9` (later, the seam check adds his words and the tally to the draft), `s306-D10` (lane U's eleven limits adopted whole, `notes/_subreports/2026-09-28-306-U-rulings-and-bloat.md`), `s306-D6` (three seats at once, joined at the commit). Page: `notes/_DECIDE-306-wrap-redesign-2026-09-28-v1.html`. Row `W-305wr`. Phase 1 (six tools) proven on the #306 wrap and phase 2 (`_ci_readback.py`, the one-wait order) on the #307 opener (`s306-D7`). Lane W1's table (`notes/_subreports/2026-09-28-306-W1-phase1-tools.md`) names phase 3: the prose and memory payload — eight to eleven hand-written files a wrap — become `knowledge/_wrap_views.py`, NOT built.

Build phase 3: a story file (fields for what is measured — from `_wrap_facts.py` — and what is written once), and `_wrap_views.py` generating from it the handoff, the chain banner and delta, the dossier, the wrap report, the memory-hook payload and the carries delta (`s306-D8`), each under its limit from `s306-D10` (the handoff ceiling blocks; the chain takes only banner and delta; the freshness arm checks the newest wrap's views only; one memory file per wrap). Runbook by addition only. Replay it over #309, #310 and #311's real inputs (`notes/_lanes/309..311/W/`, `knowledge/_tmp/wrap310/` where present) and diff against the hand-written views. If phases 4–6 fall out cheaply after 3 is green, name them in the report; do not start them unproven.""",
  lanes="""- E0 · Fable · the design, 07:30: the story file's schema and each view's template, against the eleven limits, from the last three wraps as fixtures; one page the builders build to.
- E1 · Opus 5.5 · `_wrap_views.py` and the story file (`--selftest` over the fixtures, dry run by default).
- E2 · Opus 5.5 · the changed-only carries and the limit gates (`_wrap_carries.py` by addition; the `[NEW — 0]` count defect `_AGE_RE` fixed on the way).
- E3 · Opus 5.5 · the replay over #309/#310/#311, diffs filed.
- EV · Fable · verifier: tries to make a generated view lie about a figure (a mutated FACTS.json must change the view or the gate must go red).
Commit seat AC, evening wave; paths under `knowledge/_wrap_*.py`, `knowledge/_RUNBOOK-capture-ritual.md`, fixtures under `knowledge/_tests/`.""",
  dave="None. The proof is Thursday night's wrap: the wrap seat runs the new path if the replay is green on all three fixtures, the phase-1 path if not. He sees it as a shorter wait for his summary.",
  done="`_wrap_views.py` generates every view from one story with selftests green; the replay diffs are filed and explained; the limits gate; the runbook says which path the wrap seat takes and why; `W-305wr` stays open until a real wrap has run on it."),
'F': dict(title="The pictures he is owed — one page that turns his stalled questions into calls with a recommendation each",
  ask="""274 of the 548 live rows are Dave's and the oldest stall because they need a picture. Draw them, one page, every call with a recommendation, most answerable by a click:
1. Container types — section, division, sector, panel (`W-308iw`, his 18:56 note Tue). Conductor's lean: section yes (a page region mapped to a landmark), panel already defined, division and sector no. Draw section and panel on the real demo.
2. Is the #261 nav family (sidebar-nav, tab-bar) a dashboard tile group? The bento-matrix selftest's bites R6e/R6d are red on it (`s308-D33` enacted in part, `8fe11818`); the selftest is held until he answers. Picture: the family on the dashboard, counted both ways.
3. The ring "set to fill" against the donut meta's "does not stretch" (`s305-D59`, `W-305n2`): his sketch, a 4px-grid scale with upper and lower bands, best size computed at build time. Draw the bands in four themes.
4. The list rule worked on its own (`W-305e1`, he answered Change) and the page-header lock-up (`W-305e3`): two or three drawn options each.
5. The top-nav shell as an IA question (`W-305e2`): top nav, mega menu for multiple levels, what hands over to what — explored rigorously, options drawn.
6. A header component for bento groups; can two intimately linked subjects form one group (`W-305e4`, `W-305e5`).
7. The rails half of call 9: the ramp word and its scope (`W-305w2`, `s305-D10` held).
8. The two token names `surface/section` and `notification/contextual/border/alpha` — accept or rename (`_CARRIES.md` residual, age 5).
9. The dark RAG roundels that paint pure white by policy while the ink softened (lane B's found item 2, `notes/_subreports/2026-09-30-311-B-*.md`).
10. Lane D's six (`notes/_subreports/2026-09-28-307-D-quick-18.md`): the Tabs width (`W-307ye`), a plain 0 corner or a token (`W-307qn`), which size rule trims the #245 image (`W-307qp`), the showroom focus ring as a token (`W-307q8`), the old canon gallery page and the runbook index date (`W-307q2`), which theme a generated fallback follows (`W-307q5`).
Left off on purpose: the interim pressed tile (`s310-D5`, waits on Figma); the §C·2 ruling batch (`W-305h3`, no picture would help).""",
  lanes="""- F1 · Fable · the top-nav shell IA exploration (item 5): options drawn as wireframes on the banking demo, a recommendation, the when-rule it implies.
- F2 · Fable · the list rule and the page-header lock-up (item 4): options drawn, a recommendation each.
- F3 · Opus 5.5 · renders: container types and the nav family on the real demo (items 1, 2), at the seat.
- F4 · Opus 5.5 · renders: the donut bands, the rails ramp, the roundels, the bento group header (items 3, 6, 7, 9), four themes, at the seat.
- F5 · Opus 5.5 · the page: shell copied from `notes/_REVIEW-311-B-icons-and-supercharge-page-2026-09-30-v1.html`, new localStorage key, one call per item with a recommendation, pictures inline as `<img>`, verified at 1440 and 390, Copy as text returns every call. Items 8 and 10 as plain calls.
Midday launch; nothing from the morning is needed. Commit seat AC, evening wave; paths under `notes/`.""",
  dave="The page, when he likes (Friday morning is the natural slot). Nothing is built or inscribed until he answers; every call says a drawn option is not a ruling.",
  done="One page, about twenty calls, each with a recommendation and the row it closes named; verified at both widths; published into the artifact by the conductor."),
'G': dict(title="The re-cut candidate — the designer pack as it stands tonight, built as a candidate and cold-run, so Friday's cut is a click",
  ask="""`s309-D4`, his 07:07 words Wed: "We'll recut towards the end of the week". The frozen v1.0.14 still names Kpi-tile and carries no kinds. Since it: Metric (`s309-D2`), the five kinds, the logos fix (`W-305v2`), the dark tiles (`s310-D3..D6`), the soft white and the tab strip (`s310-D7`, `D8`), the icons and Supercharge's page (`s311-D1`, `D2`, pending his eye), plus whatever jobs A and B land by the last wave. Two rulings ask for the cold run on it: `s307-D66` (run the cold-start once on the current pack and show me) and `s308-D15` (the three fixes — job B's B6 — then the fresh-session run again on the next cut, with Console). The harness: `notes/_lanes/304/R4c/harness/` (score, render, drive, compare) and its briefs under `notes/_lanes/304/R4c/`; it scored candidate 2 against v1.0.13 on 2026-09-27 (`notes/_REVIEW-304-v1013-vs-candidate-2026-09-27-v1.html`). The manifest tool: `_gen_pack_manifest.py`; `READER_SHIPS_FROM` gates the reader. Build the candidate as a candidate, never frozen: the cut is his, through the frozen-release gate on his machine. Restate once on the verdict page the known collision: the store in the pack ships the Launchpad rulings (`W-305v2`; his Sunday word: "they don't get the release, only designers, dont fret").""",
  lanes="""- G1 · Opus 5.5 · evening, after the last wave commit and its CI read-back: the candidate zip from the manifest tool at the last green sha (say which), `--check` first; if a red stands at 20:00 build at the last green sha and say so.
- G2, G3 · Opus 5.5 · two cold starts in fresh sessions (one with Console), the `s308-D15` protocol, scored by the harness against v1.0.14; the pages and receipts filed.
- GV · Fable · judges the render pairs and writes the one-page verdict: cut or not yet, with the score table and what changed since v1.0.14.
Owns `apollo-spider/dist/` (the candidate name carries `-candidate`); touches nothing else. Commit seat AC, final wave; the zip stays untracked as the release zips are.""",
  dave="The cut, Friday, on his machine, through the frozen-release gate. Never unattended. The verdict page is for the click.",
  done="A candidate zip at a named sha, two cold-run receipts, harness scores side by side with v1.0.14, one verdict page with one call."),
'H': dict(title="Studio on paper — the permutation matrix researched, the Assembly and Studio modes drawn as a proposal",
  ask="""Two of his Sunday ideas, noted and never worked: the permutation matrix (`notes/_receipts/2026-09-27-304-sq-permutation-matrix.md`, his 10:35–10:43 words: a matrix of options for a brief with a recommendation, catering for variance in structure and in the agent's decisions, "could it actually be built into apollos decision mechanism", "Okay add the note") and the Assembly/Studio modes (`notes/_receipts/2026-09-27-304-sq-assembly-studio-modes.md`, his 10:54 "the mode selection the first bifurcation would be 'Apollo assembly' and 'Apollo studio' with sub-modes below. What do you think? Can we expand on this", and 10:58: the names stand, Launchpad names the Gen-UI strand). Neither is ruled; both are ideas he asked to be expanded. The #280 matrix that got the explorer layout ruled is the precedent (`notes/_lanes/280/`). Not in scope: the Swiss taste layer — "Not for now but don't let me forget this" (`_CARRIES.md`, age 22) stands.""",
  lanes="""- H1 · Fable · research: morphological analysis and option matrices as decision instruments (Zwicky onward, current practice in design tooling), when a matrix helps and when it is noise (two or three axes, not 81 cells), how the axes are found from a brief (the decisions the agent would otherwise make silently), and a worked example on a real Apollo brief from `notes/_briefs/`; lands on how Explore in Studio would hand a pick to Assembly by promotion.
- H2 · Fable · the modes as a proposal: door at the start or lever mid-work or both; the sub-modes (Assembly: Compose, Adapt, Check, Hand off; Studio: Explore, Sketch, Propose, Review) tested against what the gates do in each; what it would mean for the pack and the generate skill; what is a place not a mode (the record).
- H3 · Opus 5.5 · the proposal page with his decisions overlay (copy the overlay from `notes/_PROPOSAL-apollo-mcp-2026-09-26-v2.html`), nothing decided on it.
Cloud workspace only; no seat. Commit seat AC, final wave; paths under `notes/`. The first job the conductor drops if the all-models line runs hot.""",
  dave="None. One proposal page for whenever he wants to read it.",
  done="Two research reports with sources and dates, one proposal page with calls and recommendations, no ruling touched."),
}

HEAD = """# Lane {L} — #312 — {title}

Draft brief written by #311 lane P (Fable) on 2026-09-30 for the Thursday burn (`notes/_PLAN-311-thursday-burn-2026-10-01-v1.html`, job {L}). The #312 conductor launches it on Dave's yes and may amend lane splits; nothing here is his ruling.

## The ask
{ask}

## Lanes × model, and what each owns
{lanes}

## Dave's one moment
{dave}

## Done when
{done}
"""
for L, j in JOBS.items():
    d = ROOT/'notes/_lanes/312'/L
    d.mkdir(parents=True, exist_ok=True)
    (d/'BRIEF.md').write_text(HEAD.format(L=L, **j) + COMMON)
    print(d/'BRIEF.md', len((d/'BRIEF.md').read_text()))
