#!/usr/bin/env python3
"""
_build_sutherland_fixtures.py — generate the Sutherland acceptance-fixture index.

The gated reference snippets are the acceptance fixtures for the Sutherland React library when its
token JSON lands. This generator distils, per component, the *contract* a Sutherland implementation
must satisfy to be accepted:
  - token bindings (CSS var -> semantic token path) it must reproduce,
  - requiredAria it must include,
  - the PASSING contrast pairs it must preserve (light + dark),
  - the props its API should expose (from the meta),
  - the reference snippet + meta to diff against.

Writes tokens/_manifests/sutherland-fixtures.json (machine) + _SUTHERLAND-FIXTURES.md (human).
Pure derivation from existing snippets/metas — no visual decisions, regenerated each build so it
never goes stale. Non-gating.
"""
import os as _hg_os, sys as _hg_sys  # noqa: E402 - help gate (#158 write-by-default class)
_hg_d = _hg_os.path.dirname(_hg_os.path.abspath(__file__))
while _hg_d != "/" and not _hg_os.path.exists(_hg_os.path.join(_hg_d, "_helpgate.py")):
    _hg_d = _hg_os.path.dirname(_hg_d)
_hg_sys.path.insert(0, _hg_d)
from _helpgate import help_gate as _help_gate; _help_gate(__doc__, __name__, __file__)
import json, glob, os, re

HERE = os.path.dirname(os.path.abspath(__file__))

def load_manifests():
    out = {}
    for f in sorted(glob.glob(os.path.join(HERE, "snippets", "*.reference.html"))):
        m = re.search(r'id="token-manifest"[^>]*>(.*?)</script>', open(f).read(), re.S)
        if not m:
            continue
        man = json.loads(m.group(1))
        comp = man.get("component")
        if comp:
            out[comp] = (os.path.basename(f), man)
    return out

def load_metas():
    out = {}
    for f in glob.glob(os.path.join(HERE, "components", "*.meta.json")):
        b = os.path.basename(f)
        if b.startswith("EXAMPLE"):
            continue
        try:
            d = json.load(open(f))
            out[d.get("name", b)] = (b, d)
        except Exception:
            pass
    return out

def main():
    mans = load_manifests()
    metas = load_metas()
    fixtures = []
    for comp in sorted(mans):
        snip, man = mans[comp]
        meta_file, meta = metas.get(comp, (None, {}))
        fixtures.append({
            "component": comp,
            "category": meta.get("category"),
            "referenceSnippet": f"snippets/{snip}",
            "meta": f"components/{meta_file}" if meta_file else None,
            "contract": {
                "tokenBindings": man.get("vars", {}),
                "requiredAria": man.get("requiredAria", []),
                "contrastPairs": man.get("contrastPairs", []),
                "props": meta.get("props", []),
            },
        })

    idx = {
        "$description": "Sutherland acceptance fixtures — per component, the contract a React implementation must satisfy to match the gated reference. Generated from snippet manifests + metas; regenerated each build.",
        "generated": "by _build_sutherland_fixtures.py",
        "componentCount": len(fixtures),
        "fixtures": fixtures,
    }
    out_json = os.path.join(HERE, "tokens", "_manifests", "sutherland-fixtures.json")
    json.dump(idx, open(out_json, "w"), indent=2, ensure_ascii=False)

    # human summary
    lines = ["# Sutherland acceptance fixtures",
             "",
             f"Generated by `_build_sutherland_fixtures.py` — **{len(fixtures)} components**. "
             "When the Sutherland React JSON lands, each component must reproduce the token bindings, ARIA, and "
             "contrast pairs below (its acceptance test = diff against the gated reference snippet).",
             "",
             "| Component | Category | Token bindings | Req. ARIA | Contrast pairs | Props |",
             "|---|---|--:|--:|--:|--:|"]
    for fx in fixtures:
        c = fx["contract"]
        lines.append(f"| {fx['component']} | {fx['category'] or '—'} | {len(c['tokenBindings'])} | "
                     f"{len(c['requiredAria'])} | {len(c['contrastPairs'])} | {len(c['props'])} |")
    lines += ["",
              "Machine-readable contract: `tokens/_manifests/sutherland-fixtures.json`.",
              "Acceptance = a Sutherland component matches its reference's bindings + ARIA + contrast pairs (light & dark)."]
    open(os.path.join(HERE, "_SUTHERLAND-FIXTURES.md"), "w").write("\n".join(lines) + "\n")

    print(f"sutherland fixtures: {len(fixtures)} component contract(s) -> tokens/_manifests/sutherland-fixtures.json")

if __name__ == "__main__":
    main()
