#!/usr/bin/env python3
"""
Lane records — validate + generate the LS view (O1′ pilot schema case, ruled Dave 2026-07-28 #24).

WHY: #20 floated it and Dave confirmed the point verbatim — "less lets not forget this, thats the
whole point." Lane order lived as prose in GM §C·1 plus read discipline; nothing mechanical
enforced "lane 2 blocked until lane 1 lands". These records make it data: the readable view in
`_LIVE-STATE.md` §🛤 LANES is generated between AUTO-LANES markers (never hand-edited — same
discipline as canon.css / the decision-lifecycle block), and the eager ROUTING LINE in
`GOOD-MORNING.md` §C·1 is checked AGAINST the records at wrap (BLOCKING,
`_capture_gate.py::lane_routing_check`, which IMPORTS this module — one implementation, never a
second copy; the mover≠gate lesson).

DATA CARRIES STATE, PROSE CARRIES WHY. The WHY stays in `notes/_MEMENTO-DECISIONS.md`. This
module refuses what it does not know (ds-016 class): unknown states, unknown fields, dangling
`blocked_by`, a "blocked" lane whose blockers all landed, a "landed" step after a live one —
every miss is LOUD, never enumerate-and-skip.

Run:  python3 knowledge/_gen_lanes.py             # regenerate the LS view (writes only on change)
      python3 knowledge/_gen_lanes.py --check     # build gate: view must equal the records
      python3 knowledge/_gen_lanes.py --selftest  # bites — every refusal proves it can FAIL
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
RECORDS = os.path.join(HERE, "_lanes.json")
LS = os.path.join(REPO, "_LIVE-STATE.md")

MARK_START = "<!-- AUTO-LANES START — generated by knowledge/_gen_lanes.py from knowledge/_lanes.json; never hand-edit between these markers. -->"
MARK_END = "<!-- AUTO-LANES END -->"

LANE_STATES = ("active", "blocked", "steady-state", "landed")
STEP_STATES = ("landed", "active", "queued")
STATE_WORD = {"active": "ACTIVE", "blocked": "BLOCKED",
              "steady-state": "STEADY", "landed": "LANDED"}
STEP_GLYPH = {"landed": "✅", "active": "▶", "queued": "⏳"}
LANE_FIELDS_REQ = ("id", "name", "state", "born", "until", "blocked_by", "sequence", "receipts")
LANE_FIELDS_OPT = ("wrap_scope",)
TOP_KEYS = ("$description", "$schema", "lanes")
LANE_ID_RE = re.compile(r"\blane-[a-z0-9-]+\b")
# line-START anchored (the mover's lesson, re-learned by this check's own FIRST FIRE: GM
# cites "the ⛔ ROUTING line" in five places — a bare substring match found 6 lines and
# elected a MENTION; only the real eager line begins a line with it).
ROUTING_RE = re.compile(r"^\*\*⛔\s*ROUTING\b")


def load_lanes(path=RECORDS):
    """Parse + validate. Returns (lanes, errors) — lanes is None on any error (fail loud)."""
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        return None, [f"{os.path.basename(path)}: unreadable/unparsable ({e}) — fix it, never close blind"]
    return validate_lanes(data)


def validate_lanes(data):
    """Validation half, IO-free (selftest probes call this directly — the sandbox
    delete-guard makes temp files a liability, and validation never needed a disk)."""
    errors = []
    for k in data:
        if k not in TOP_KEYS:
            errors.append(f"unknown top-level key `{k}` — the schema is the contract, register or remove")
    lanes = data.get("lanes")
    if not isinstance(lanes, list) or not lanes:
        return None, errors + ["`lanes` missing/empty — an empty register is a structure change, refuse"]
    ids = [l.get("id") for l in lanes]
    if len(ids) != len(set(ids)):
        errors.append("duplicate lane ids")
    for l in lanes:
        lid = l.get("id", "<no id>")
        for k in l:
            if k not in LANE_FIELDS_REQ + LANE_FIELDS_OPT:
                errors.append(f"{lid}: unknown field `{k}` (never enumerate-and-skip)")
        for k in LANE_FIELDS_REQ:
            if k not in l:
                errors.append(f"{lid}: required field `{k}` missing")
        if l.get("state") not in LANE_STATES:
            errors.append(f"{lid}: unknown lane state `{l.get('state')}` — vocabulary is {LANE_STATES}")
        for b in l.get("blocked_by", []):
            if b not in ids:
                errors.append(f"{lid}: blocked_by `{b}` names no registered lane (dangling guard)")
        blockers_live = [b for b in l.get("blocked_by", [])
                         for bl in lanes if bl.get("id") == b and bl.get("state") != "landed"]
        if blockers_live and l.get("state") != "blocked":
            errors.append(f"{lid}: has live blocker(s) {blockers_live} but state is "
                          f"`{l.get('state')}` — a live guard MEANS blocked")
        if l.get("state") == "blocked" and not l.get("blocked_by"):
            errors.append(f"{lid}: state `blocked` with empty blocked_by — a block needs a named guard")
        if l.get("blocked_by") and not blockers_live and l.get("state") == "blocked":
            errors.append(f"{lid}: every blocker has landed but state is still `blocked` — "
                          f"the record rotted; update the state")
        seen_live = False
        actives = 0
        for s in l.get("sequence", []):
            for k in ("step", "state"):
                if k not in s:
                    errors.append(f"{lid}: sequence entry missing `{k}`")
            if "receipt" not in s:
                errors.append(f"{lid}: sequence entry `{s.get('step', '?')[:40]}` missing `receipt` "
                              f"(null is honest; absent is a hole)")
            st = s.get("state")
            if st not in STEP_STATES:
                errors.append(f"{lid}: unknown step state `{st}` — vocabulary is {STEP_STATES}")
            if st == "active":
                actives += 1
            if st in ("active", "queued"):
                seen_live = True
            elif st == "landed" and seen_live:
                errors.append(f"{lid}: `landed` step after a live one — sequence order is the "
                              f"contract (the lane-order-violation class)")
        if actives > 1:
            errors.append(f"{lid}: {actives} active steps — a sequence has at most one")
    return (None, errors) if errors else (lanes, [])


def render(lanes):
    """Deterministic view — no volatile dates (clean build ⇒ no spurious diff)."""
    out = []
    for l in lanes:
        guard = f" · blocked_by: {', '.join(l['blocked_by'])}" if l["blocked_by"] else ""
        wrap = f" · wraps: `{l['wrap_scope']}`" if l.get("wrap_scope") else ""
        out.append(f"**{STATE_WORD[l['state']]} — `{l['id']}` · {l['name']}**"
                   f" *(born {l['born']}{guard}{wrap})*")
        for s in l["sequence"]:
            r = f" · receipt {s['receipt']}" if s["receipt"] else ""
            out.append(f"- {STEP_GLYPH[s['state']]} {s['step']} — {s['state']}{r}")
        out.append(f"- ⏹ until: {l['until']} · receipts: {l['receipts']}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def spliced(ls_text, block):
    """Replace between markers. Markers missing = None (reachability failure, caller fails loud)."""
    i, j = ls_text.find(MARK_START), ls_text.find(MARK_END)
    if i < 0 or j < 0 or j < i:
        return None
    return ls_text[:i + len(MARK_START)] + "\n" + block + ls_text[j:]


def current_block(ls_text):
    i, j = ls_text.find(MARK_START), ls_text.find(MARK_END)
    if i < 0 or j < 0 or j < i:
        return None
    return ls_text[i + len(MARK_START):j].strip("\n") + "\n"


def routing_expectations(lanes):
    """What the eager GM §C·1 ROUTING line must carry — used by the wrap gate (imported)."""
    return [(l["id"], STATE_WORD[l["state"]]) for l in lanes]


def check_routing_line(gm_text, lanes):
    """The machine-checkable half of 'the ROUTING LINE stays EAGER': exactly one ⛔ ROUTING
    line, every lane on it with the record's state word, no unregistered lane ids, records
    file named. Returns list of issues; [] = green."""
    issues = []
    hits = [ln for ln in gm_text.splitlines() if ROUTING_RE.match(ln)]
    if not hits:
        return ["GM §C·1 eager ROUTING line MISSING (⛔ ROUTING) — externalised records "
                "without the eager pointer is the cold-session-defaults-onto-Apollo failure"]
    if len(hits) > 1:
        issues.append(f"{len(hits)} ⛔ ROUTING lines — the eager line is ONE line")
    line = hits[0]
    known = {l["id"] for l in lanes}
    for lid, word in routing_expectations(lanes):
        if not re.search(rf"\b{word}\s+`?{re.escape(lid)}`?", line):
            issues.append(f"ROUTING line does not carry `{word} {lid}` — line and records "
                          f"disagree; the records are the truth, fix the line (or the record)")
    for tok in set(LANE_ID_RE.findall(line)) - known:
        issues.append(f"ROUTING line names unregistered lane `{tok}` — register it or remove it")
    if "_lanes.json" not in line:
        issues.append("ROUTING line must name the records file (knowledge/_lanes.json) — "
                      "the fetch path is part of the eager contract")
    return issues


def selftest():
    fails = []
    ran = []          # ★ the count is COMPUTED, never a literal — the {17} class, swept #39.
                      # The last bite is inside `if lanes:`, so a literal would over-report
                      # by one on the records-fail path: latent, but the same defect shape.

    def bite(name, cond):
        ran.append(name)
        if not cond:
            fails.append(name)

    good = [{"id": "lane-a", "name": "A", "state": "active", "born": "#1", "until": "done",
             "blocked_by": [], "receipts": "ledger",
             "sequence": [{"step": "s1", "state": "landed", "receipt": "r"},
                          {"step": "s2", "state": "active", "receipt": None}]},
            {"id": "lane-b", "name": "B", "state": "blocked", "born": "#1", "until": "a lands",
             "blocked_by": ["lane-a"], "receipts": "ledger", "sequence": []}]

    def probe(mutate):
        import copy
        d = copy.deepcopy(good)
        mutate(d)
        return validate_lanes({"lanes": d})

    lanes, errs = probe(lambda d: None)
    bite("good fixture loads clean", lanes is not None and errs == [])
    _, errs = probe(lambda d: d[0].update(state="soaring"))
    bite("unknown lane state refuses", any("unknown lane state" in e for e in errs))
    _, errs = probe(lambda d: d[0].update(vibe="good"))
    bite("unknown field refuses", any("unknown field" in e for e in errs))
    _, errs = probe(lambda d: d[1].update(blocked_by=["lane-ghost"]))
    bite("dangling blocked_by refuses", any("dangling" in e for e in errs))
    _, errs = probe(lambda d: d[1].update(state="active"))
    bite("live blocker forces blocked", any("MEANS blocked" in e for e in errs))
    _, errs = probe(lambda d: d[0].update(state="landed"))
    bite("all-blockers-landed refuses stale block", any("rotted" in e for e in errs))
    _, errs = probe(lambda d: d[0]["sequence"].append({"step": "s3", "state": "landed", "receipt": "r"}))
    bite("landed-after-live refuses", any("lane-order-violation" in e for e in errs))
    _, errs = probe(lambda d: d[0]["sequence"][1].pop("receipt"))
    bite("absent receipt field refuses (null is honest, absent is a hole)",
         any("missing `receipt`" in e for e in errs))
    bite("render deterministic", render(good) == render(good))
    bite("markers-missing detected (reachability)", spliced("no markers here", "x") is None)
    text = f"a\n{MARK_START}\nold\n{MARK_END}\nb"
    bite("splice replaces between markers", "old" not in spliced(text, "new\n")
         and "new" in spliced(text, "new\n"))
    gm_good = ("x\n**⛔ ROUTING (records: knowledge/_lanes.json): ACTIVE lane-a · "
               "BLOCKED lane-b (by lane-a).**\ny")
    bite("good routing line quiet", check_routing_line(gm_good, good) == [])
    bite("missing routing line fires", any("MISSING" in i for i in check_routing_line("x", good)))
    bite("a MENTION is not the line (line-START anchor — the first-fire lesson)",
         any("MISSING" in i for i in check_routing_line(
             "> the ⛔ ROUTING line is checked at wrap\nprose about ⛔ ROUTING here", good)))
    bite("state mismatch fires", any("disagree" in i for i in
         check_routing_line(gm_good.replace("BLOCKED lane-b", "ACTIVE lane-b"), good)))
    bite("unregistered lane on line fires", any("unregistered lane" in i for i in
         check_routing_line(gm_good.replace("lane-a ·", "lane-a · STEADY lane-zz ·"), good)))
    bite("records file must be named", any("_lanes.json" in i for i in
         check_routing_line(gm_good.replace("knowledge/_lanes.json", "somewhere"), good)))

    # green control on the REAL records + REAL LS markers
    lanes, errs = load_lanes()
    bite(f"real records load clean (got: {errs[:2]})", lanes is not None)
    if lanes:
        bite("real LS carries the markers (reachability)",
             current_block(open(LS, encoding="utf-8").read()) is not None)

    if fails:
        print("[_gen_lanes selftest] FAIL:")
        for f in fails:
            print(f"  ✗ {f}")
        return 1
    print(f"[_gen_lanes selftest] OK — {len(ran)} bites, every refusal fired, green controls held")
    return 0


def main(argv):
    if "--selftest" in argv:
        return selftest()
    lanes, errs = load_lanes()
    if errs:
        for e in errs:
            print(f"✗ {e}")
        return 1
    block = render(lanes)
    ls_text = open(LS, encoding="utf-8").read()
    cur = current_block(ls_text)
    if cur is None:
        print(f"✗ AUTO-LANES markers missing from _LIVE-STATE.md — the generated section is "
              f"unreachable; restore the §🛤 LANES section (fail-loud, never skip)")
        return 1
    if "--check" in argv:
        if cur != block:
            print("✗ _LIVE-STATE.md §🛤 LANES is out of sync with knowledge/_lanes.json — "
                  "run `python3 knowledge/_gen_lanes.py` (the records are the truth)")
            return 1
        print("✓ lanes view in sync with records")
        return 0
    if cur == block:
        print("✓ lanes view already current (no write)")
        return 0
    with open(LS, "w", encoding="utf-8") as f:
        f.write(spliced(ls_text, block))
    print(f"✓ lanes view regenerated — {len(lanes)} lanes → _LIVE-STATE.md §🛤 LANES")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
