#!/usr/bin/env python3
"""Generate `_CHAIN.md` — the read chain as a FILE, so a cold session can read it cheaply.

WHY THIS EXISTS (#41, measured, Dave's ruling).
-----------------------------------------------
The read chain has been "CUT" since #33 and the cut has never been enforceable, because the
instruction describing it lives *inside the 433-line file it is trying to make cheap*.

    contract price of the chain ......  3,838 tape
    what #41's opener actually paid ... 28,653 harness-tokens

Not carelessness. **`Read` cannot read less than a file.** A session that opens
`GOOD-MORNING.md` pays for all 18,434 tape to discover it should have stopped at line 21.
Five sessions called the chain CUT while every one of them paid full price for it.

⇒ The fix is not a rule and not a discipline. It is a SMALLER FILE. Generate the chain, point
memory at it, and the expensive thing stops being the first thing anyone touches.

WHAT THIS IS NOT
----------------
⚠ **Not the brief's item 1.** That one moves §A and §C out of `GOOD-MORNING.md`, and the survey
at #41 found it blocked by `STAND-004` — a gate that exists *specifically* to stop §A leaving
that file, after §A was eroded in a rewrite on 2026-07-18. Six modules hard-reference GM's
sections by path and the index selftest pins §A's children to `file == "GOOD-MORNING.md"`.
This generator changes **no file, no gate, and no module**. It is additive and reversible by
deleting one file.

⚠ **Not a fourth mechanism.** The Friday brief names "adding a fourth mechanism" as a thing that
will undo the programme. This adds no cap, no block and no judgment: it copies bytes that
already exist into a smaller container. Nothing here can refuse a session anything.

THE ONE RULE THAT KEEPS IT HONEST
---------------------------------
★ **The chain text comes from `_capture_gate.chain_parts` — the same slicer the gate MEASURES
with.** Not a copy of its logic; the function itself. So "the chain is 3,838 tape" and "here is
the chain" can never describe different text. A second slicer here would be the exact drift
class `read_chain_tk`'s own docstring refuses.

⚠ Generated files rot when nothing checks them. `--check` regenerates in memory and compares,
and it is wired into `_build_all.py`, so a stale `_CHAIN.md` fails the build rather than quietly
serving a previous session's record to a cold reader — the #32 defect, which is precisely the
failure mode a chain file is most exposed to.

USAGE
    python3 knowledge/_gen_chain.py              # write _CHAIN.md
    python3 knowledge/_gen_chain.py --check      # exit 1 if _CHAIN.md is stale (build step)
    python3 knowledge/_gen_chain.py --selftest   # the bites
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT_NAME = "_CHAIN.md"

sys.path.insert(0, HERE)

BANNER = """<!-- GENERATED by knowledge/_gen_chain.py — DO NOT HAND-EDIT.
     Edit GOOD-MORNING.md / _LIVE-STATE.md and regenerate; `--check` is a build step. -->

# The read chain — everything a cold session must read, and nothing else

> **This file is GENERATED and it is the whole contract.** It carries `GOOD-MORNING.md`'s header
> and ★ LATEST banner, plus `_LIVE-STATE.md`'s ⏱ LATEST delta — the three things GM-D7-am names
> (CUT #33 on Dave's ruling). **If you have read this file, you have read the chain.**
>
> ⚠ **Do NOT now open `GOOD-MORNING.md` to "check".** It is {gm_tk:,} tape and {gm_pct:.0f}% of it is
> retrieval surface you are not meant to pay for at boot. That reflex is the thing this file
> exists to stop — five sessions called the chain CUT and every one of them paid full price.
>
> ★ **Everything else is RETRIEVAL, never a reading list:**
> `python3 knowledge/_memento_search.py "<q>"` → `--fetch <id>`. §A orientation is `gm:A`
> (a router with 11 children); the queue is `gm:C1`…; the archives, briefs, runbooks and ledgers
> are all indexed. **Ask for what you need; do not read a file to find out whether you need it.**

---
"""

FOOTER = """

---

*(Chain ends. **{chain_tk:,} tape** — the contract price, measured by the same function that
generated this file. `GOOD-MORNING.md` is {gm_tk:,} tape and stays whole for retrieval; you have
paid for {chain_pct:.0f}% of it and that is the intended figure, not a shortfall.)*
"""


def build(repo=ROOT):
    """Return `(text, detail)` for the chain file, or `(None, reason)` on refusal.

    ⚠ REFUSES rather than guesses, inheriting `chain_parts`' posture: a generator that emits an
    empty-but-plausible chain on a parse failure hands a cold session a confident blank, which is
    strictly worse than no file at all. Every failure path returns a REASON.
    """
    try:
        import _capture_gate as cg
    except Exception as e:                                    # pragma: no cover - import guard
        return None, f"_capture_gate unavailable ({e}) — chain NOT generated, not assumed empty"

    gm_path = os.path.join(repo, "GOOD-MORNING.md")
    if not os.path.exists(gm_path):
        return None, "GOOD-MORNING.md is missing — nothing to generate a chain from"
    with open(gm_path, encoding="utf-8") as f:
        gm_text = f.read()
    gm_lines = gm_text.splitlines()

    gm_part, delta, how = cg.chain_parts(repo, gm_lines)
    if gm_part is None:
        return None, how

    gm_tk = cg.measure_tokens(gm_text)[0]
    chain_tk, chain_detail = cg.read_chain_tk(repo, gm_lines)
    if chain_tk is None:
        return None, chain_detail

    body = gm_part if delta is None else gm_part + "\n\n---\n\n" + delta
    # ⚠ Every published figure here is MEASURED with the gate's own tokenizer, never derived from
    # line counts or character lengths. A COUNT IS NOT A MEASUREMENT — the standing lesson.
    gm_part_tk = cg.measure_tokens(gm_part)[0]
    head = BANNER.format(gm_tk=gm_tk, gm_pct=100.0 * (gm_tk - gm_part_tk) / gm_tk if gm_tk else 0.0)
    foot = FOOTER.format(chain_tk=chain_tk, gm_tk=gm_tk,
                         chain_pct=100.0 * chain_tk / gm_tk if gm_tk else 0.0)
    return head + "\n" + body + foot, chain_detail


def write(repo=ROOT):
    text, detail = build(repo)
    if text is None:
        print(f"  ✗ _CHAIN.md NOT generated — {detail}")
        return 1
    out = os.path.join(repo, OUT_NAME)
    with open(out, "w", encoding="utf-8") as f:
        f.write(text)
    try:
        import _capture_gate as cg
        tk = cg.measure_tokens(text)[0]
        print(f"  ✅ {OUT_NAME}: {tk:,} tape · {detail}")
    except Exception:                                          # pragma: no cover
        print(f"  ✅ {OUT_NAME} written · {detail}")
    return 0


def check(repo=ROOT):
    """Determinism check — the `gen_canon_components` pattern.

    ⚠ Compares CONTENT, never mtime. The retrieval index was bitten by exactly this (#32: it
    served a two-session-old record because freshness was judged by timestamp), and a chain file
    is the single artefact where a stale copy does the most damage — it is the FIRST thing read
    and the reader has no reason to doubt it.
    """
    text, detail = build(repo)
    if text is None:
        print(f"  ✗ _CHAIN.md check FAILED — {detail}")
        return 1
    out = os.path.join(repo, OUT_NAME)
    if not os.path.exists(out):
        print(f"  ✗ {OUT_NAME} is MISSING — run `python3 knowledge/_gen_chain.py` and stage it")
        return 1
    with open(out, encoding="utf-8") as f:
        have = f.read()
    if have != text:
        print(f"  ✗ {OUT_NAME} is STALE — it does not match GOOD-MORNING.md / _LIVE-STATE.md as "
              f"they now stand, so a cold session would read a PREVIOUS session's record as if it "
              f"were current. Run `python3 knowledge/_gen_chain.py` and stage the result.")
        return 1
    print(f"  ✅ {OUT_NAME} is FRESH — byte-matches the live chain · {detail}")
    return 0


def selftest():
    """Bites. Selftests are BUILD STEPS here — a gate that ships without one is documentation."""
    import tempfile
    import shutil
    fails = []

    def bite(what, ok):
        print(f"    {'✓' if ok else '✗'} {what}")
        if not ok:
            fails.append(what)

    text, detail = build(ROOT)
    bite("generates against the live repo (no refusal on a healthy tree)", text is not None)

    if text is not None:
        import _capture_gate as cg
        gm_lines = open(os.path.join(ROOT, "GOOD-MORNING.md"), encoding="utf-8").read().splitlines()
        gm_part, delta, _how = cg.chain_parts(ROOT, gm_lines)
        chain_tk, _d = cg.read_chain_tk(ROOT, gm_lines)
        gm_tk = cg.measure_tokens(open(os.path.join(ROOT, "GOOD-MORNING.md"),
                                       encoding="utf-8").read())[0]

        bite("carries the GM header+LATEST term VERBATIM (not a summary of it)", gm_part in text)
        bite("carries the LS ⏱ LATEST delta VERBATIM", delta is None or delta in text)
        # ★ The point of the whole exercise: the file must actually be small. A chain file that
        #   is not much smaller than GM buys nothing and would be worse than nothing, because it
        #   adds a second thing to keep fresh. Assert the CUT, not just the content.
        out_tk = cg.measure_tokens(text)[0]
        bite(f"is materially smaller than GOOD-MORNING.md ({out_tk:,} vs {gm_tk:,} tape, <40%)",
             out_tk < 0.40 * gm_tk)
        bite("published chain figure is the gate's own measurement, not a re-derivation",
             f"{chain_tk:,} tape" in text)
        bite("says GENERATED / DO-NOT-HAND-EDIT at the very top (line 1)",
             text.splitlines()[0].lstrip().startswith("<!-- GENERATED"))
        bite("tells the reader NOT to open GOOD-MORNING.md to check",
             "Do NOT now open" in text)
        bite("names retrieval as the door for everything else", "_memento_search.py" in text)

    # determinism: two builds of an unchanged tree are byte-identical
    t2, _ = build(ROOT)
    bite("DETERMINISTIC — two builds of an unchanged tree are byte-identical", text == t2)

    # --check must FAIL on a stale file, not pass it. The failure class that matters most.
    tmp = tempfile.mkdtemp()
    try:
        for n in ("GOOD-MORNING.md", "_LIVE-STATE.md"):
            src = os.path.join(ROOT, n)
            if os.path.exists(src):
                shutil.copy(src, os.path.join(tmp, n))
        write(tmp)
        bite("--check PASSES on a freshly generated file", check(tmp) == 0)
        with open(os.path.join(tmp, OUT_NAME), "a", encoding="utf-8") as f:
            f.write("\ndrift\n")
        bite("--check FAILS on a hand-edited file (the stale-record class)", check(tmp) == 1)
        os.remove(os.path.join(tmp, OUT_NAME))
        bite("--check FAILS when the file is missing entirely", check(tmp) == 1)
        # refusal: no ★ LATEST banner ⇒ REFUSE, never emit a confident blank
        with open(os.path.join(tmp, "GOOD-MORNING.md"), "w", encoding="utf-8") as f:
            f.write("# nothing here\n")
        t3, r3 = build(tmp)
        bite("REFUSES (with a reason) when GM has no ★ LATEST banner — no cheerful blank",
             t3 is None and isinstance(r3, str) and len(r3) > 20)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    if fails:
        print(f"  ✗ _gen_chain selftest: {len(fails)} bite(s) failed")
        return 1
    print("  ✅ _gen_chain selftest: all bites pass")
    return 0


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(selftest())
    if "--check" in sys.argv:
        sys.exit(check())
    sys.exit(write())
