#!/usr/bin/env python3
"""_memento_search.py — THE MEMENTO DOOR: "what does the record say about X?" (O2′ #25).

Thin door over `knowledge/_search_core.py` (the retrieval spine — matching, ranking,
honest denominators and the two-stage fetch all live THERE; the DS door `_consult.py`
imports the same engine). This door owns the Memento corpus: GM/LS sections · both
archives · the Memento ledger · gauge blocks · briefs · dream proposals · memento
runbooks · lane records — index `knowledge/_memento-index.json`, generated by
`_build_memento_index.py` every build (never hand-edit it).

WHY (ruled Dave 2026-07-28, ledger § Memento-before-Apollo + § ★ #25): the memento tier
was invisible to retrieval — a cold session asking "what did we decide about wraps?" got
amber-contrast rulings from the DS corpus. Retrieval-not-recall now reaches the
project's own memory: quote the record, never reconstruct it.

TWO-STAGE (the ruled shape): stage 1 returns REFS — ids + one-line heads + file:line,
cheap to read, honest denominators; stage 2 `--fetch <id>` prints the record VERBATIM.
A cold session spends tokens on the records it needs, not on the corpus.

Usage:
  python3 knowledge/_memento_search.py "band table amber threshold"   # stage 1: refs
  python3 knowledge/_memento_search.py "lane routing" --all           # no per-group cap
  python3 knowledge/_memento_search.py --fetch lane:lane-1-memento    # stage 2: verbatim
  python3 knowledge/_memento_search.py "query" --json                 # machine-readable
  python3 knowledge/_memento_search.py --selftest                     # known-answer bites

Lexicon: shares knowledge/_consult-lexicon.json (one curation point — a synonym learned
from a real miss serves both doors).
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import _search_core as core
import _graph_edges  # #115 steps 1+3: ADVISORY edge attachment, display-only

INDEX_PATH = os.path.join(HERE, "_memento-index.json")
LEXICON_PATH = os.path.join(HERE, "_consult-lexicon.json")

KIND_ORDER = ["lane", "gm-section", "ls-section", "ledger-section", "runbook-section",
              "gauge-block", "gm-archive-section", "ls-archive-section", "brief", "dream"]
KIND_LABEL = {
    "lane": "lane records",
    "gm-section": "GOOD-MORNING sections",
    "ls-section": "LIVE-STATE sections",
    "ledger-section": "Memento-ledger sections",
    "runbook-section": "runbook sections",
    "gauge-block": "gauge-log blocks",
    "gm-archive-section": "GM-archive sections",
    "ls-archive-section": "LS-archive sections",
    "brief": "briefs",
    "dream": "dream proposals",
}
DEFAULT_CAP = {
    "lane": 3, "gm-section": 3, "ls-section": 3, "ledger-section": 4,
    "runbook-section": 5, "gauge-block": 3, "gm-archive-section": 4,
    "ls-archive-section": 4, "brief": 3, "dream": 3,
}


def load_lexicon():
    if not os.path.exists(LEXICON_PATH):
        return {}
    with open(LEXICON_PATH, encoding="utf-8") as f:
        return json.load(f)


def bucket_for(record):
    return record["kind"] if record["kind"] in KIND_ORDER else None


# #115 step 1 (ADVISORY, decorate hook): attach supersedes/refines/bounds neighbour
# lines to any result whose graph node the mention map (or a direct id match) finds.
# ABSOLUTE CONSTRAINT (brief): this decorate ONLY adds keys to `entry` — it never
# touches `_score`, never reorders, never changes bucket membership or caps. `_search_core.search`
# sorts/caps on the entry AFTER decorate runs, from fields decorate never writes.
def _decorate_edges(entry):
    entry["_graph_neighbours"] = _graph_edges.neighbour_lines(entry)
    # #115 step 3 (MARK-ONLY, separate function/hunk from step 1 above — same decorate
    # call site because both need the one decorate hook, but the two concerns are
    # independent: step 1 can be reverted without touching step 3, and vice versa).
    entry["_graph_superseded"] = _graph_edges.superseded_lines(entry)


def search(query, index, lexicon, all_results=False):
    return core.search(index["records"], query, lexicon, bucket_for, DEFAULT_CAP,
                       all_results=all_results, decorate=_decorate_edges)


def print_human(buckets, totals, query, expanded, all_results):
    print(f'memento: "{query}"')
    if expanded:
        print(f"  lexicon expanded to: {', '.join(sorted(expanded))}")
    total = sum(len(v) for v in buckets.values())
    if total == 0:
        print("  no matches. If this is a real miss, add a synonym to "
              "knowledge/_consult-lexicon.json (one lexicon, both doors) — "
              "curation is part of the job.")
        return
    if not _graph_edges.available():
        print(f"  ({_graph_edges.unavailable_notice()})")
    for kind in KIND_ORDER:
        rows = buckets.get(kind, [])
        if not rows:
            continue
        print("\n" + core.group_header(KIND_LABEL[kind], len(rows),
                                       totals.get(kind, len(rows)), all_results))
        for r in rows:
            print(f"  [{r['id']}] {r['head'][:120]}")
            print(f"      source: {r['file']}:{r['line']}  (stage 2: --fetch {r['id']})")
            # #115 step 3 (MARK-ONLY) — printed before step 1's neighbour lines so a
            # supersession reads first; neither line changes this row's position.
            for line in r.get("_graph_superseded", []):
                print(f"      {line}")
            # #115 step 1 (ADVISORY)
            for line in r.get("_graph_neighbours", []):
                print(f"      {line}")
            # #115 observation recorder — logs DISPLAYED marks only (post-cap), the
            # evidence base for the demote ruling. Loud on write failure, never raises.
            notice = _graph_edges.record_observation("memento", query, r)
            if notice:
                print(f"      {notice}")


def print_fetch(index, record_id):
    record, err = core.fetch(index["records"], record_id)
    if err:
        print(err)
        return 1
    print(f"[{record['id']}] kind={record['kind']}")
    print(f"source: {record['file']}:{record['line']}")
    print()
    print(record.get("text", "").rstrip())
    return 0


# ------------------------------------------------------------------ selftest
# Known-answer regression pins (the DS-door pattern): each query MUST surface its
# record. Fix the lexicon or ranking on a miss — never special-case the query string.
SELFTEST_CASES = [
    ("band table amber threshold remaining budget",
     {"runbook:context-gauge:the-floor-is-measured-never-assumed-gm-d9"}),
    ("lane routing check blocking records",
     {"lane:lane-1-memento"}),
    ("retirement receipts proxy promoted blocking",
     {"ledger:23-section-usage-instrumentation-enacted-lane-1-step-2-2026"}),
    ("dream pass weekly sunday unattended fire",
     {"lane:lane-dream-pass"}),
]


def run_selftest(index, lexicon):
    ok = True
    for query, expect_ids in SELFTEST_CASES:
        buckets, _, _, _ = search(query, index, lexicon, all_results=True)
        found = set()
        for rows in buckets.values():
            found |= {r["id"] for r in rows}
        missing = expect_ids - found
        status = "OK" if not missing else "FAIL"
        print(f"[{status}] \"{query}\" — expected {sorted(expect_ids)}, "
              f"missing {sorted(missing) if missing else 'none'}")
        if missing:
            ok = False
    # two-stage bites, both directions
    record, err = core.fetch(index["records"], "lane:lane-1-memento")
    hit = record is not None and err is None and record.get("text")
    print(f"[{'OK' if hit else 'FAIL'}] --fetch lane:lane-1-memento returns the record verbatim")
    ok = ok and bool(hit)
    record, err = core.fetch(index["records"], "lane:no-such-lane")
    refused = record is None and err and "REFUSING" in err
    print(f"[{'OK' if refused else 'FAIL'}] --fetch unknown id REFUSES with near-misses")
    ok = ok and bool(refused)
    # #115 steps 1+3: edge-attachment bites, on synthetic state so they can FAIL
    # independent of whatever's on disk right now (a mutation-test posture, not a
    # green-by-construction one). Real state is saved/restored around the probe.
    saved = dict(_graph_edges._state)
    try:
        _graph_edges._state.update({
            "loaded": True,
            "graph": {"nodes": {"ADR-X": {}, "ADR-Y": {}},
                      "edges": [{"from": "ADR-Y", "type": "supersedes", "to": "ADR-X"}]},
            "reverse": {"gm:HIT": ["ADR-X"]},
        })
        no_mention = _graph_edges.neighbour_lines({"id": "gm:NOWHERE"})
        bite_a = no_mention == []
        print(f"[{'OK' if bite_a else 'FAIL'}] edge attach: record with no mention gets no attachment")
        ok = ok and bite_a
        hit_lines = _graph_edges.neighbour_lines({"id": "gm:HIT"})
        bite_b = "⌁ ADR-X superseded-by ADR-Y" in hit_lines
        print(f"[{'OK' if bite_b else 'FAIL'}] edge attach: injected fabricated edge appears for a mentioning record")
        ok = ok and bite_b
        mark_lines = _graph_edges.superseded_lines({"id": "gm:HIT"})
        bite_c = mark_lines == ["⛔ SUPERSEDED by ADR-Y"]
        print(f"[{'OK' if bite_c else 'FAIL'}] step 3 mark: target-of-supersedes record gets the ⛔ line")
        ok = ok and bite_c
        bite_d = _graph_edges.superseded_lines({"id": "gm:NOWHERE"}) == []
        print(f"[{'OK' if bite_d else 'FAIL'}] step 3 mark: non-mentioning record gets no mark")
        ok = ok and bite_d
    finally:
        _graph_edges._state.clear()
        _graph_edges._state.update(saved)
    if ok:
        print("selftest OK — the memento corpus answers its known questions, and fetch "
              "refuses the unknown.")
    else:
        print("selftest FAILED — a known-answer record was not retrieved. Fix the lexicon "
              "or ranking (or a slug moved — re-pin from the rebuilt index), never "
              "special-case the query.")
    return 0 if ok else 1


def main():
    args = sys.argv[1:]
    index = core.load_records_or_refuse(INDEX_PATH, "memento-search (Memento door)")
    lexicon = load_lexicon()

    if args and args[0] == "--selftest":
        return run_selftest(index, lexicon)

    if "--fetch" in args:
        i = args.index("--fetch")
        if i + 1 >= len(args):
            print("--fetch needs a record id. Usage: python3 knowledge/_memento_search.py "
                  "--fetch <id>")
            return 1
        return print_fetch(index, args[i + 1])

    if not args:
        print(__doc__)
        return 1

    as_json = "--json" in args
    all_results = "--all" in args
    query_parts = [a for a in args if not a.startswith("--")]
    if not query_parts:
        print("no query given. Usage: python3 knowledge/_memento_search.py \"<query>\" "
              "[--all] [--json] | --fetch <id>")
        return 1
    query = " ".join(query_parts)

    buckets, totals, original, expanded = search(query, index, lexicon, all_results=all_results)

    if as_json:
        payload = {
            "query": query,
            "lexicon_expansion": sorted(expanded),
            "totals": {KIND_LABEL[k]: v for k, v in totals.items()},
            "results": {KIND_LABEL[k]: buckets.get(k, []) for k in KIND_ORDER},
        }
        print(json.dumps(payload, indent=2, ensure_ascii=False))
        return 0

    print_human(buckets, totals, query, expanded, all_results)
    return 0


if __name__ == "__main__":
    sys.exit(main())
