#!/usr/bin/env python3
"""
_validate_advisory.py — ADVISORY signals: recorded prose rules, made executable.

Entry path per ADR-0005 §5: new check classes (heuristics, CX, content) enter at the
ADVISORY tier — they annotate, they never block. A check earns promotion to blocking
only by being bite-tested (see _tests/test_advisory.py) and surviving real use.

First three checks are distilled from RECORDED prose rules (G5, north-star mock;
"the fluff bites" — 2026-07-02):

  A. all-caps labels — house rule (test brief v2 §4: "avoid ALL-CAPS labels — overrides
     any styling convention that wants caps"). Flags text-transform:uppercase in CSS and
     multi-word ALL-CAPS runs in visible text.
  B. placeholder-as-label — recorded anti-pattern (text-input meta): an <input> carrying
     a placeholder with no matching <label for=…>.
  C. unmasked number runs — safety pattern (charter §2: masked sort/account numbers).
     Flags 8+ consecutive digits or a XX-XX-XX sort-code shape in visible text.

Scans <root>/snippets/*.reference.html and <root>/_fitness-test/*.canon.html.
Writes <root>/_ADVISORY-SIGNALS.md. ALWAYS exits 0 — advisory annotates, never blocks.

Usage: python3 _validate_advisory.py [--root DIR]   (--root exists for bite-tests)
"""
import glob, os, re, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
if "--root" in sys.argv:
    ROOT = os.path.abspath(sys.argv[sys.argv.index("--root") + 1])

CAPS_CSS = re.compile(r'text-transform\s*:\s*uppercase', re.I)
CAPS_TEXT = re.compile(r'\b[A-Z]{2,}(?: [A-Z]{2,})+\b')
DIGIT_RUN = re.compile(r'\d{8,}')
SORT_CODE = re.compile(r'\b\d{2}[-–]\d{2}[-–]\d{2}\b')
INPUT_TAG = re.compile(r'<input\b[^>]*>', re.I)


def visible_text(html):
    t = re.sub(r'<script.*?</script>', ' ', html, flags=re.S | re.I)
    t = re.sub(r'<style.*?</style>', ' ', t, flags=re.S | re.I)
    t = re.sub(r'<!--.*?-->', ' ', t, flags=re.S)
    return re.sub(r'<[^>]+>', ' ', t)


def check(path):
    html = open(path).read()
    name = os.path.basename(path)
    text = visible_text(html)
    signals = []

    # A — all-caps labels (house rule)
    for m in CAPS_CSS.finditer(html):
        signals.append(("all-caps", "text-transform:uppercase in CSS — house rule: no all-caps labels"))
    for m in set(CAPS_TEXT.findall(text)):
        signals.append(("all-caps", f'ALL-CAPS text run "{m}" — house rule: no all-caps labels'))

    # B — placeholder-as-label (recorded anti-pattern: placeholder as the ONLY accessible
    #     name). aria-label / aria-labelledby count as a name, so they don't signal.
    for tag in INPUT_TAG.findall(html):
        if re.search(r'\bplaceholder\s*=', tag, re.I):
            if re.search(r'\baria-label(ledby)?\s*=', tag, re.I):
                continue
            idm = re.search(r'\bid\s*=\s*["\']([^"\']+)["\']', tag)
            has_label = bool(idm) and bool(
                re.search(r'<label\b[^>]*\bfor\s*=\s*["\']%s["\']' % re.escape(idm.group(1)), html, re.I))
            if not has_label:
                signals.append(("placeholder-as-label", f"input with placeholder and no accessible name: {tag[:60]}…"))

    # C — unmasked number runs (safety pattern)
    for m in set(DIGIT_RUN.findall(text)):
        signals.append(("unmasked-digits", f'digit run "{m}" — account refs last-4 only, sort codes fully masked'))
    for m in set(SORT_CODE.findall(text)):
        signals.append(("unmasked-digits", f'sort-code shape "{m}" — sort codes are fully masked'))

    return name, signals


def main():
    targets = sorted(glob.glob(os.path.join(ROOT, "snippets", "*.reference.html"))) + \
              sorted(glob.glob(os.path.join(ROOT, "_fitness-test", "*.canon.html")))
    rows = [check(p) for p in targets]
    total = sum(len(s) for _, s in rows)

    lines = ["# Advisory signals — prose rules (ADVISORY, non-gating)", "",
             "*Auto-generated by `_validate_advisory.py`. Checks distilled from recorded prose rules "
             "(house rules, anti-patterns, safety patterns). Signals annotate — they never block. "
             "Promotion to blocking requires bite-tests + a Dave ruling (ADR-0005 §5).*", "",
             f"**{len(rows)} file(s) scanned · {total} signal(s).**", ""]
    for name, signals in rows:
        if signals:
            lines.append(f"## {name} — {len(signals)} signal(s)")
            lines += [f"- **{kind}** — {msg}" for kind, msg in signals]
            lines.append("")
    if total == 0:
        lines.append("_No signals._")
    open(os.path.join(ROOT, "_ADVISORY-SIGNALS.md"), "w").write("\n".join(lines) + "\n")

    print(f"advisory signals: {len(rows)} file(s), {total} signal(s) — see _ADVISORY-SIGNALS.md (non-gating)")
    sys.exit(0)  # advisory: never blocks


if __name__ == "__main__":
    main()
