#!/usr/bin/env python3
"""gen_runbook_index.py — the runbook of runbooks. GENERATED, so it cannot drift.

Dave 2026-07-18: "maybe we have a runbook of runbooks ;) my brain is basically a
recursive magpie always building a nest."

WHY GENERATED AND NOT WRITTEN. A hand-maintained index of runbooks is precisely the
artefact that rots silently — someone adds a runbook and forgets the index, or rewrites
the index from scratch and drops an entry. That is the same failure that nearly killed
§A's standing instruction on 2026-07-18. This scans knowledge/_RUNBOOK-*.md and rebuilds
the list every build, so "what runbooks exist" is derived from the filesystem rather than
from anyone's memory of it.

It reads each runbook's H1 and its first italic purpose line / first paragraph, so the
description is owned by the runbook itself — one source of truth per runbook.

Usage:  python3 knowledge/gen_runbook_index.py    # writes knowledge/_RUNBOOKS.md
Wired into _build_all.py. Never hand-edit _RUNBOOKS.md.
"""
import os, re, glob, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "_RUNBOOKS.md")


def summarise(path):
    """Title from the H1; purpose from the first italic line or first real paragraph."""
    txt = open(path, encoding="utf-8").read()
    m = re.search(r"^#\s+(.+)$", txt, re.M)
    title = m.group(1).strip() if m else os.path.basename(path)
    body = txt[m.end():] if m else txt
    purpose = ""
    it = re.search(r"^\s*\*([^*].+?)\*\s*$", body, re.M | re.S)
    if it:
        purpose = it.group(1)
    else:
        for para in re.split(r"\n\s*\n", body):
            p = para.strip()
            if p and not p.startswith(("#", "```", ">", "|", "-", "*")):
                purpose = p
                break
    purpose = re.sub(r"\s+", " ", purpose).strip()
    if len(purpose) > 240:
        purpose = purpose[:237].rsplit(" ", 1)[0] + "…"
    return title, purpose


def build():
    paths = sorted(glob.glob(os.path.join(HERE, "_RUNBOOK-*.md")))
    lines = [
        "# Runbooks — the index",
        "",
        "*GENERATED by `knowledge/gen_runbook_index.py` — do not hand-edit; add a runbook and it appears.*",
        "",
        "Runbooks are **tattoos, not Polaroids** (see the Memento framing in `GOOD-MORNING.md` §A): the method",
        "written down so a cold agent can operate the engine without a human remembering how. A rule that lives",
        "only in the artefact it governs dies the first time that artefact is rewritten — so it lives here too.",
        "",
        "**This index is generated from the filesystem**, because a hand-maintained list of runbooks is exactly",
        "the thing that rots when someone adds the tenth one and forgets the list.",
        "",
        f"**{len(paths)} runbooks**, last generated {datetime.date.today().isoformat()}.",
        "",
    ]
    for p in paths:
        name = os.path.basename(p)
        title, purpose = summarise(p)
        lines.append(f"### `{name}`")
        lines.append(f"**{title}**")
        if purpose:
            lines.append("")
            lines.append(purpose)
        lines.append("")

    lines += [
        "---",
        "",
        "## Read these before acting",
        "",
        "- **Any git operation** → `_RUNBOOK-git-commit.md`. The sandbox delete-guard means git can create",
        "  `.git/*.lock` but never unlink it. Sequence is **clear → stage → clear → commit → clear**, using",
        "  `mv` and never `rm`. Getting this wrong wastes a turn every time.",
        "- **End of session** → `_RUNBOOK-capture-ritual.md`. Run it unasked.",
        "- **Building a component** → `_RUNBOOK-gated-component.md`, after surveying `snippets/` +",
        "  `components/*.meta.json` + the tranches. Skipping the survey duplicated Tab-bar and Stepper in T8.",
        "",
        "*Entry points: `GOOD-MORNING.md` §A (orientation) · `_LIVE-STATE.md` (live/dead/open) ·",
        "`AGENTS.md` (repo agent contract) · `guidelines/_rules-index.json` (the 465-rule spine).*",
        "",
    ]
    open(OUT, "w", encoding="utf-8").write("\n".join(lines))
    print(f"runbook index: {len(paths)} runbooks -> {os.path.relpath(OUT, HERE)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(build())
