#!/usr/bin/env python3
"""
gen_token_ramp.py — TOKEN-SET distribution into standalone files (s121-D1, #121).

The fourth injection type, symmetric with AUTO-PARTIAL (CSS), AUTO-BEHAVIOUR (JS) and
AUTO-MARKUP (HTML) in gen_component_partials.py: canon.css declares token-set source
atoms between `/* ===== TOKENS <set> START ... ===== */` markers; this generator
distributes them into standalone consumer files (snippets/*.reference.html,
_proforma/*.html) that reference the set's variables but cannot reach canon.css
(they are portable specimens with their own <style>). Closes the ds-018 C2 class:
a var() that resolves to NOTHING silently takes the property's INITIAL value.

Sets (s121-D1):
  alpha — the --alpha-04..96 opacity ramp (minted #99). Declarations, wrapped :root{}.
  marks — the per-status --mark map (--mark-error/-warning/-success/-info + carrier
          default). ⚠ PROVISIONAL values — Dave mints actual status × theme
          combinations soon; canon.css comments carry the flag. Declarations plus the
          mark-carriers rule atom (.is-error etc.).

Consumers get ONE generated block, injected directly after their first <style> tag:

  /* ===== AUTO-TOKENS START (gen_token_ramp.py) ===== */ ... /* ===== AUTO-TOKENS END ===== */

Idempotent; content-compared, never mtime. A file that stops referencing every set
gets its block REMOVED. Local declarations in a consumer keep winning (they come
later in the cascade) — Tranche-6/9's state-class --mark declarations are untouched.

⛔ HTML COMMENTS ARE NOT CSS, AND THIS GENERATOR NOW KNOWS THAT (#211, P-8's generator
cause). The original injection point was `re.search(r"<style[^>]*>", html)` over the RAW
text, so the first LITERAL `<style>` won — and in five files that literal sits inside a
prose comment (`<!-- TYPE-001 · … MUST come BEFORE the component <style> below … -->`).
The whole alpha ramp was appended INSIDE the comment: not CSS, silently dead, and
idempotent over its own defect so `--check` reported "in sync" forever. Both the
injection point AND the set-detector now read a COMMENT-MASKED copy, and render()
refuses (TokenRampError) if the block it just built would land inside a comment —
the post-condition is the gate, because a generator that cannot see comments will
re-make this exact hole the next time a consumer's prose mentions `<style>`.

Modes: (default) write · --check (exit 1 on any drift, for _build_all.py) · --selftest.
Failures are LOUD and NAMED (TokenRampError) — a parse helper that guesses is the
ds-025 defect.
"""
import os as _hg_os, sys as _hg_sys  # noqa: E402 - help gate (#158 write-by-default class)
_hg_d = _hg_os.path.dirname(_hg_os.path.abspath(__file__))
while _hg_d != "/" and not _hg_os.path.exists(_hg_os.path.join(_hg_d, "_helpgate.py")):
    _hg_d = _hg_os.path.dirname(_hg_d)
_hg_sys.path.insert(0, _hg_d)
from _helpgate import help_gate as _help_gate; _help_gate(__doc__, __name__, __file__)
import re, sys, json, tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
CANON = HERE / "canon" / "canon.css"
TARGET_GLOBS = [("snippets", "*.reference.html"), ("_proforma", "*.html")]

BEGIN = "/* ===== AUTO-TOKENS START (generated by gen_token_ramp.py from canon/canon.css — DO NOT EDIT; edit the TOKENS source atoms in canon.css and regenerate, s121-D1) ===== */"
END = "/* ===== AUTO-TOKENS END ===== */"

# set name -> (canon marker name, reference-detector regex, wrap declarations in :root{})
SETS = {
    "alpha": ("alpha", re.compile(r"var\(\s*--alpha-\d\d"), True),
    "marks": ("marks", re.compile(r"var\(\s*--mark[\s,)]"), True),
}
# rule atoms distributed WITH a set (not wrapped in :root)
RULE_ATOMS = {"marks": "mark-carriers"}


class TokenRampError(RuntimeError):
    pass


def canon_block(css, name):
    m = re.search(
        r"/\* ===== TOKENS " + re.escape(name) + r" START[^\n]*===== \*/\n(.*?)\n\s*/\* ===== TOKENS "
        + re.escape(name) + r" END ===== \*/", css, re.S)
    if not m:
        raise TokenRampError(
            f"canon.css has no `TOKENS {name} START/END` marker pair — refusing to guess (ds-025).")
    return m.group(1).rstrip()


def payload_for(css, sets_needed):
    parts = [BEGIN]
    for s in sorted(sets_needed):
        marker, _, wrap_root = SETS[s]
        body = canon_block(css, marker)
        if wrap_root:
            parts.append(":root{\n" + body + "\n}")
        else:
            parts.append(body)
        if s in RULE_ATOMS:
            parts.append(canon_block(css, RULE_ATOMS[s]))
    parts.append(END)
    return "\n".join(parts)


AUTO_RX = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.S)


def strip_block(html):
    return AUTO_RX.sub("", html)


COMMENT_OPEN, COMMENT_CLOSE = "<!--", "-->"


def mask_comments(html):
    """Blank every HTML comment's bytes, PRESERVING LENGTH and newlines (#211).

    Returned string is index-for-index aligned with the input, so an offset found in
    the mask addresses the same byte in the original. An UNTERMINATED `<!--` masks to
    EOF, which is what a browser does — a generator that stopped at the missing `-->`
    would be guessing (ds-025).
    """
    out = list(html)
    i = 0
    while True:
        a = html.find(COMMENT_OPEN, i)
        if a < 0:
            return "".join(out)
        b = html.find(COMMENT_CLOSE, a + len(COMMENT_OPEN))
        end = len(html) if b < 0 else b + len(COMMENT_CLOSE)
        for k in range(a, end):
            if out[k] != "\n":
                out[k] = " "
        i = end


def in_comment(html, offset):
    """True if `offset` falls inside an HTML comment — the post-condition's question."""
    return mask_comments(html)[offset] != html[offset]


def sets_referenced(html_without_block):
    """⛔ Asked of a COMMENT-MASKED copy: a var() named only in prose is not a reference."""
    masked = mask_comments(html_without_block)
    return {s for s, (_, rx, _) in SETS.items() if rx.search(masked)}


def render(html, css):
    """Return the file as it SHOULD be (pure — no I/O)."""
    bare = strip_block(html)
    need = sets_referenced(bare)
    if not need:
        return bare
    # ⛔ the injection point is found in the MASKED copy: a literal `<style>` written
    # inside a prose comment is not a style tag (#211 — P-8's generator cause).
    m = re.search(r"<style[^>]*>\n?", mask_comments(bare))
    if not m:
        raise TokenRampError(
            "file references a token set but has no <style> tag to inject into "
            "OUTSIDE AN HTML COMMENT — refusing to guess (ds-025).")
    block = payload_for(css, need)
    out = bare[: m.end()] + block + "\n" + bare[m.end():]
    # POST-CONDITION, not a comment: the block we just wrote must be live CSS.
    if in_comment(out, out.index(BEGIN)):
        raise TokenRampError(
            "the AUTO-TOKENS block would land INSIDE an HTML comment — that is dead CSS "
            "and it is the #211 defect; refusing to write it (s121-D1).")
    return out


def targets():
    out = []
    for d, g in TARGET_GLOBS:
        out.extend(sorted((HERE / d).glob(g)))
    if not out:
        raise TokenRampError("no target files found under snippets/ or _proforma/ — wrong cwd?")
    return out


def run(write):
    css = CANON.read_text()
    for name in list(dict.fromkeys([v[0] for v in SETS.values()] + list(RULE_ATOMS.values()))):
        canon_block(css, name)  # fail loud up front if any atom is missing
    drift, injected, removed, untouched = [], 0, 0, 0
    for p in targets():
        html = p.read_text()
        want = render(html, css)
        if want != html:
            drift.append(str(p.relative_to(HERE)))
            if write:
                p.write_text(want)
            if AUTO_RX.search(want) or BEGIN in want:
                injected += 1
            else:
                removed += 1
        else:
            untouched += 1
    verb = "synced" if write else "DRIFTED"
    print(f"gen_token_ramp: {len(drift)} file(s) {verb} ({injected} with block, {removed} block-removed), "
          f"{untouched} already in sync.")
    for f in drift[:10]:
        print(f"   {'✏' if write else '❌'} {f}")
    if len(drift) > 10:
        print(f"   … and {len(drift) - 10} more")
    if drift and not write:
        print("   run: python3 knowledge/gen_token_ramp.py")
        return 1
    return 0


def selftest():
    fails = []
    css = ("x{}\n/* ===== TOKENS alpha START ===== */\n  --alpha-60: 0.6;\n/* ===== TOKENS alpha END ===== */\n"
           "/* ===== TOKENS marks START ===== */\n  --mark-error: #FFF;\n  --mark: var(--mark-error);\n/* ===== TOKENS marks END ===== */\n"
           "/* ===== TOKENS mark-carriers START ===== */\n.is-error{--mark:var(--mark-error);}\n/* ===== TOKENS mark-carriers END ===== */\n")
    consumer = "<html><style>\n.a{opacity:var(--alpha-60);}\n</style></html>"
    # 1. injection happens and is idempotent
    once = render(consumer, css)
    if ":root{" not in once or "--alpha-60: 0.6;" not in once:
        fails.append("alpha set not injected")
    if render(once, css) != once:
        fails.append("injection not idempotent on re-render")
    # 2. tampered source atom has teeth
    if render(once, css.replace("0.6", "0.61")) == once:
        fails.append("tampered canon atom produced identical injection (no teeth)")
    # 3. marks set brings its carrier rule atom
    two = render("<html><style>\n.i{fill:var(--mark);}\n</style></html>", css)
    if ".is-error{--mark:var(--mark-error);}" not in two:
        fails.append("marks set injected without its mark-carriers rule atom")
    # 4. non-referencing file gets NO block; a stale block is removed
    plain = "<html><style>\n.b{color:red;}\n</style></html>"
    if render(plain, css) != plain:
        fails.append("non-referencing file was injected")
    stale = plain.replace(".b{", BEGIN + "\nold\n" + END + "\n.b{")
    if render(stale, css) != plain:
        fails.append("stale block on a non-referencing file was not removed")
    # 5. missing marker + missing <style> fail LOUD and NAMED
    for bad_css, bad_html, tag in ((css.replace("TOKENS alpha", "TOKENS nope"), consumer, "missing canon marker"),
                                   (css, "<html>no style " + "var(--alpha-60)", "missing <style>")):
        try:
            render(bad_html, bad_css)
            fails.append(f"{tag} did not raise")
        except TokenRampError:
            pass
    # 6. ⛔ #211 — a literal `<style>` written inside a PROSE COMMENT is not a style tag.
    #    This is the exact shape of Button.reference.html:45, which put the whole alpha
    #    ramp inside `<!-- … MUST come BEFORE the component <style> … -->` and stayed
    #    "in sync" forever because the generator was idempotent over its own defect.
    shadowed = ("<html>\n<!-- NOTE: this must come BEFORE the component <style> below. -->\n"
                "<style>\n.a{opacity:var(--alpha-60);}\n</style></html>")
    try:
        out6 = render(shadowed, css)
    except TokenRampError as e:
        # a crash is not a fail [[a-crash-is-not-a-fail]] — name it and keep the rc honest
        out6 = None
        fails.append("#211 comment-shadowed <style>: render REFUSED (%s)" % e)
    if out6 is not None:
        if BEGIN not in out6:
            fails.append("#211 comment-shadowed <style>: no block injected at all")
        elif in_comment(out6, out6.index(BEGIN)):
            fails.append("#211 comment-shadowed <style>: block landed INSIDE the HTML comment (dead CSS)")
        if out6.count("<!-- NOTE: this must come BEFORE the component <style> below. -->") != 1:
            fails.append("#211 comment-shadowed <style>: the prose comment was severed, not preserved")
        try:
            if render(out6, css) != out6:
                fails.append("#211 comment-shadowed <style>: not idempotent on re-render")
        except TokenRampError as e:
            fails.append("#211 comment-shadowed <style>: re-render REFUSED (%s)" % e)
    # 7. a file whose ONLY `<style>` text is inside a comment must REFUSE, loud and named.
    try:
        render("<html><!-- <style> --> .a{opacity:var(--alpha-60);}</html>", css)
        fails.append("#211 comment-only <style> did not raise")
    except TokenRampError:
        pass
    # 8. the set DETECTOR is comment-masked too: a var() named only in prose is not a reference.
    prose_only = "<html>\n<!-- we deliberately do NOT use var(--alpha-60) here -->\n<style>\n.b{color:red;}\n</style></html>"
    if render(prose_only, css) != prose_only:
        fails.append("#211 a var() named only inside a comment triggered an injection")
    # 9. an UNTERMINATED `<!--` comments out the rest of the file, exactly as a browser
    #    reads it — so nothing after it is CSS and the file must come back UNCHANGED.
    unterm = "<html>\n<!-- oops, never closed … <style>\n.a{opacity:var(--alpha-60);}\n</style></html>"
    try:
        if render(unterm, css) != unterm:
            fails.append("#211 unterminated <!-- : text after it was treated as live CSS")
    except TokenRampError as e:
        fails.append("#211 unterminated <!-- : render REFUSED instead of leaving the file alone (%s)" % e)
    if fails:
        print("gen_token_ramp selftest: FAIL")
        for f in fails:
            print("   ❌ " + f)
        return 1
    print("gen_token_ramp selftest: 6 bites GREEN + 4 comment bites (#211) GREEN")
    return 0


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(selftest())
    sys.exit(run(write="--check" not in sys.argv))
