#!/usr/bin/env python3
"""
Generate a canon gallery — every reviewed component exercised with its OWN snippet markup,
wrapped in its .cn-<slug> scope, consuming canon.css. Zero hand-authoring: each section is the
snippet's demo body (script + demo-controls stripped), so it renders exactly like the gated
snippet. Output is gated by _validate_screen.py (icon-source + a11y + state-contrast + compose).
"""
import os as _hg_os, sys as _hg_sys  # noqa: E402 - help gate (#158 write-by-default class)
_hg_d = _hg_os.path.dirname(_hg_os.path.abspath(__file__))
while _hg_d != "/" and not _hg_os.path.exists(_hg_os.path.join(_hg_d, "_helpgate.py")):
    _hg_d = _hg_os.path.dirname(_hg_d)
_hg_sys.path.insert(0, _hg_d)
from _helpgate import help_gate as _help_gate; _help_gate(__doc__, __name__, __file__)
import os, re, glob

SNIP = os.path.join(os.path.dirname(os.path.abspath(__file__)), "snippets")
OUT  = os.path.join(os.path.dirname(os.path.abspath(__file__)), "_fitness-test", "canon-gallery.canon.html")

def slug(n): return re.sub(r"[^a-z0-9]+", "-", n.lower()).strip("-")

def remove_div_by_class(html, cls):
    """Remove <div class="...cls...">...</div> with balanced nesting."""
    out, i = [], 0
    pat = re.compile(r'<div[^>]*class="[^"]*\b' + re.escape(cls) + r'\b[^"]*"[^>]*>')
    while True:
        m = pat.search(html, i)
        if not m: out.append(html[i:]); break
        out.append(html[i:m.start()])
        depth, j = 1, m.end()
        while j < len(html) and depth:
            nd = html.find("<div", j); cd = html.find("</div>", j)
            if cd == -1: break
            if nd != -1 and nd < cd: depth += 1; j = nd + 4
            else: depth -= 1; j = cd + 6
        i = j
    return "".join(out)

def extract_sprite(body):
    """Pull an inline <svg ...position:absolute...> sprite out; return (body_without, sprite)."""
    m = re.search(r'<svg[^>]*position:absolute[^>]*>.*?</svg>', body, re.S)
    if not m: return body, ""
    return body[:m.start()] + body[m.end():], m.group(0)

ORDER = ["Button","List-items","Cards","Headers","Navigations","Notifications","Modals","Input-fields",
 "Progress-tracker","Badge","Links","Tags","Status-indicator","Avatar","Divider","Table","Tabs",
 "Selection-controls","Search-field","Breadcrumbs","Pagination","Accordion","Tooltip","Quick-actions",
 "Dropdown","Hero","Slider","Reorder","Countdown-timer","View-options","Video-player","Loading-indicator"]

sections, symbols = [], {}
# curated order first, then any newer snippets (e.g. reviewed gap-patterns) auto-appended
_all = sorted(os.path.basename(p).replace(".reference.html", "") for p in glob.glob(os.path.join(SNIP, "*.reference.html")))
_order = ORDER + [n for n in _all if n not in ORDER]
for nm in _order:
    f = os.path.join(SNIP, nm + ".reference.html")
    if not os.path.exists(f): continue
    html = open(f).read()
    body = re.search(r"<body[^>]*>(.*?)</body>", html, re.S).group(1)
    body = re.sub(r"<script.*?</script>", "", body, flags=re.S)
    body = remove_div_by_class(body, "demo-controls")
    body, sprite = extract_sprite(body)
    for sm in re.findall(r'<symbol id="([^"]+)"[^>]*>.*?</symbol>', sprite, re.S):
        pass
    for sm in re.finditer(r'<symbol id="([^"]+)".*?</symbol>', sprite, re.S):
        symbols[sm.group(1)] = sm.group(0)
    sc = "cn-" + slug(nm)
    sections.append(f'<section class="g-item">\n  <h2 class="g-name">{nm}</h2>\n  <div class="{sc}">{body.strip()}</div>\n</section>')

sprite_block = ('<svg width="0" height="0" style="position:absolute" aria-hidden="true">\n  '
                + "\n  ".join(symbols.values()) + "\n</svg>") if symbols else ""

doc = f"""<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Canon component gallery — all reviewed components composed from canon.css</title>
<!-- GENERATED by gen_gallery.py. Each section is a reviewed snippet's own demo markup wrapped in its
     .cn-<slug> scope, consuming knowledge/canon/canon.css. Gated by _validate_screen.py. -->
<link rel="stylesheet" href="../canon/canon.css">
<style>
  body{{ margin:0; padding:24px; background:var(--page); color:var(--text); font-family:var(--font); }}
  .g-bar{{ position:fixed; top:10px; right:10px; z-index:50; }}
  .g-bar button{{ font:inherit; font-size:13px; padding:6px 12px; border:1px solid var(--border); background:var(--surface); color:var(--text); cursor:pointer; }}
  .g-item{{ max-width:840px; margin:0 auto 40px; padding-bottom:28px; border-bottom:1px solid var(--divider-soft); }}
  .g-name{{ font:500 12px/1 var(--font); /* sentence case — type26-019 sweep (Dave 2026-07-02) */ color:var(--muted); margin:0 0 16px; }}
  /* Review gallery: render interactive components in a representative SHOWN state (no per-snippet JS).
     A real screen drives these with the component's own script; here we just reveal them for review. */
  .cn-modals .overlay{{ position:static !important; inset:auto; visibility:visible !important; opacity:1 !important; padding:0; background:transparent; display:block; }}
  .cn-modals .overlay .dialog{{ transform:none !important; opacity:1 !important; box-shadow:0 0 0 1px var(--border); }}
  .cn-tooltip .tip{{ opacity:1 !important; pointer-events:auto; }}
</style>
</head>
<body class="canon">
  <div class="g-bar"><button id="t" type="button">◐ Theme</button></div>
  {sprite_block}
  {"".join(sections)}
  <script>
    document.getElementById('t').addEventListener('click',()=>{{const h=document.documentElement;h.setAttribute('data-theme',h.getAttribute('data-theme')==='dark'?'light':'dark');}});
    // input-modality: prominent keyboard focus ring for keyboard users only (suppressed on pointer)
    const _root=document.documentElement;
    addEventListener('keydown',e=>{{if(e.key==='Tab')_root.dataset.modality='keyboard';}});
    addEventListener('mousedown',()=>_root.dataset.modality='pointer');
    addEventListener('touchstart',()=>_root.dataset.modality='pointer',{{passive:true}});
    // reveal interactive components in a representative state for review
    function showInteractive(){{
      document.querySelectorAll('.cn-dropdown .menu').forEach(m=>m.setAttribute('data-open','true'));
      document.querySelectorAll('.cn-dropdown .trigger').forEach(t=>t.setAttribute('aria-expanded','true'));
      const acc=document.querySelector('.cn-accordion');
      if(acc){{const h=acc.querySelector('.head'); if(h){{h.setAttribute('aria-expanded','true'); const it=h.closest('.item')||acc; const p=it.querySelector('.panel'); if(p) p.style.maxHeight='260px';}}}}
      document.querySelectorAll('.cn-tabs .tablist').forEach(tl=>{{const s=tl.querySelector('[aria-selected="true"]')||tl.querySelector('.tab'); const ind=tl.querySelector('.indicator'); if(s&&ind){{ind.style.left=s.offsetLeft+'px';ind.style.width=s.offsetWidth+'px';ind.style.opacity='1';}}}});
      document.querySelectorAll('.cn-tab-bar .seg').forEach(seg=>{{const a=seg.querySelector('.seg__item[aria-current="page"]'); const ind=seg.querySelector('.ind'); if(a&&ind){{ind.style.left=a.offsetLeft+'px';ind.style.width=a.offsetWidth+'px';}}}});
    }}
    showInteractive();
  </script>
</body>
</html>"""
open(OUT, "w").write(doc)
print(f"gallery: {len(sections)} components, {len(symbols)} sprite symbols -> {OUT}")
