#!/usr/bin/env python3
"""
gen_token_ramp.py — TOKEN-SET distribution into standalone files (s121-D1, #121).

The fourth injection type, symmetric with AUTO-PARTIAL (CSS), AUTO-BEHAVIOUR (JS) and
AUTO-MARKUP (HTML) in gen_component_partials.py: canon.css declares token-set source
atoms between `/* ===== TOKENS <set> START ... ===== */` markers; this generator
distributes them into standalone consumer files (snippets/*.reference.html,
_proforma/*.html) that reference the set's variables but cannot reach canon.css
(they are portable specimens with their own <style>). Closes the ds-018 C2 class:
a var() that resolves to NOTHING silently takes the property's INITIAL value.

Sets (s121-D1):
  alpha — the --alpha-04..96 opacity ramp (minted #99). Declarations, wrapped :root{}.
  marks — the per-status --mark map (--mark-error/-warning/-success/-info + carrier
          default). ⚠ PROVISIONAL values — Dave mints actual status × theme
          combinations soon; canon.css comments carry the flag. Declarations plus the
          mark-carriers rule atom (.is-error etc.).

Consumers get ONE generated block, injected directly after their first <style> tag:

  /* ===== AUTO-TOKENS START (gen_token_ramp.py) ===== */ ... /* ===== AUTO-TOKENS END ===== */

Idempotent; content-compared, never mtime. A file that stops referencing every set
gets its block REMOVED. Local declarations in a consumer keep winning (they come
later in the cascade) — Tranche-6/9's state-class --mark declarations are untouched.

Modes: (default) write · --check (exit 1 on any drift, for _build_all.py) · --selftest.
Failures are LOUD and NAMED (TokenRampError) — a parse helper that guesses is the
ds-025 defect.
"""
import os as _hg_os, sys as _hg_sys  # noqa: E402 - help gate (#158 write-by-default class)
_hg_d = _hg_os.path.dirname(_hg_os.path.abspath(__file__))
while _hg_d != "/" and not _hg_os.path.exists(_hg_os.path.join(_hg_d, "_helpgate.py")):
    _hg_d = _hg_os.path.dirname(_hg_d)
_hg_sys.path.insert(0, _hg_d)
from _helpgate import help_gate as _help_gate; _help_gate(__doc__, __name__, __file__)
import re, sys, json, tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
CANON = HERE / "canon" / "canon.css"
TARGET_GLOBS = [("snippets", "*.reference.html"), ("_proforma", "*.html")]

BEGIN = "/* ===== AUTO-TOKENS START (generated by gen_token_ramp.py from canon/canon.css — DO NOT EDIT; edit the TOKENS source atoms in canon.css and regenerate, s121-D1) ===== */"
END = "/* ===== AUTO-TOKENS END ===== */"

# set name -> (canon marker name, reference-detector regex, wrap declarations in :root{})
SETS = {
    "alpha": ("alpha", re.compile(r"var\(\s*--alpha-\d\d"), True),
    "marks": ("marks", re.compile(r"var\(\s*--mark[\s,)]"), True),
}
# rule atoms distributed WITH a set (not wrapped in :root)
RULE_ATOMS = {"marks": "mark-carriers"}


class TokenRampError(RuntimeError):
    pass


def canon_block(css, name):
    m = re.search(
        r"/\* ===== TOKENS " + re.escape(name) + r" START[^\n]*===== \*/\n(.*?)\n\s*/\* ===== TOKENS "
        + re.escape(name) + r" END ===== \*/", css, re.S)
    if not m:
        raise TokenRampError(
            f"canon.css has no `TOKENS {name} START/END` marker pair — refusing to guess (ds-025).")
    return m.group(1).rstrip()


def payload_for(css, sets_needed):
    parts = [BEGIN]
    for s in sorted(sets_needed):
        marker, _, wrap_root = SETS[s]
        body = canon_block(css, marker)
        if wrap_root:
            parts.append(":root{\n" + body + "\n}")
        else:
            parts.append(body)
        if s in RULE_ATOMS:
            parts.append(canon_block(css, RULE_ATOMS[s]))
    parts.append(END)
    return "\n".join(parts)


AUTO_RX = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.S)


def strip_block(html):
    return AUTO_RX.sub("", html)


def sets_referenced(html_without_block):
    return {s for s, (_, rx, _) in SETS.items() if rx.search(html_without_block)}


def render(html, css):
    """Return the file as it SHOULD be (pure — no I/O)."""
    bare = strip_block(html)
    need = sets_referenced(bare)
    if not need:
        return bare
    m = re.search(r"<style[^>]*>\n?", bare)
    if not m:
        raise TokenRampError(
            "file references a token set but has no <style> tag to inject into — refusing to guess (ds-025).")
    block = payload_for(css, need)
    return bare[: m.end()] + block + "\n" + bare[m.end():]


def targets():
    out = []
    for d, g in TARGET_GLOBS:
        out.extend(sorted((HERE / d).glob(g)))
    if not out:
        raise TokenRampError("no target files found under snippets/ or _proforma/ — wrong cwd?")
    return out


def run(write):
    css = CANON.read_text()
    for name in list(dict.fromkeys([v[0] for v in SETS.values()] + list(RULE_ATOMS.values()))):
        canon_block(css, name)  # fail loud up front if any atom is missing
    drift, injected, removed, untouched = [], 0, 0, 0
    for p in targets():
        html = p.read_text()
        want = render(html, css)
        if want != html:
            drift.append(str(p.relative_to(HERE)))
            if write:
                p.write_text(want)
            if AUTO_RX.search(want) or BEGIN in want:
                injected += 1
            else:
                removed += 1
        else:
            untouched += 1
    verb = "synced" if write else "DRIFTED"
    print(f"gen_token_ramp: {len(drift)} file(s) {verb} ({injected} with block, {removed} block-removed), "
          f"{untouched} already in sync.")
    for f in drift[:10]:
        print(f"   {'✏' if write else '❌'} {f}")
    if len(drift) > 10:
        print(f"   … and {len(drift) - 10} more")
    if drift and not write:
        print("   run: python3 knowledge/gen_token_ramp.py")
        return 1
    return 0


def selftest():
    fails = []
    css = ("x{}\n/* ===== TOKENS alpha START ===== */\n  --alpha-60: 0.6;\n/* ===== TOKENS alpha END ===== */\n"
           "/* ===== TOKENS marks START ===== */\n  --mark-error: #FFF;\n  --mark: var(--mark-error);\n/* ===== TOKENS marks END ===== */\n"
           "/* ===== TOKENS mark-carriers START ===== */\n.is-error{--mark:var(--mark-error);}\n/* ===== TOKENS mark-carriers END ===== */\n")
    consumer = "<html><style>\n.a{opacity:var(--alpha-60);}\n</style></html>"
    # 1. injection happens and is idempotent
    once = render(consumer, css)
    if ":root{" not in once or "--alpha-60: 0.6;" not in once:
        fails.append("alpha set not injected")
    if render(once, css) != once:
        fails.append("injection not idempotent on re-render")
    # 2. tampered source atom has teeth
    if render(once, css.replace("0.6", "0.61")) == once:
        fails.append("tampered canon atom produced identical injection (no teeth)")
    # 3. marks set brings its carrier rule atom
    two = render("<html><style>\n.i{fill:var(--mark);}\n</style></html>", css)
    if ".is-error{--mark:var(--mark-error);}" not in two:
        fails.append("marks set injected without its mark-carriers rule atom")
    # 4. non-referencing file gets NO block; a stale block is removed
    plain = "<html><style>\n.b{color:red;}\n</style></html>"
    if render(plain, css) != plain:
        fails.append("non-referencing file was injected")
    stale = plain.replace(".b{", BEGIN + "\nold\n" + END + "\n.b{")
    if render(stale, css) != plain:
        fails.append("stale block on a non-referencing file was not removed")
    # 5. missing marker + missing <style> fail LOUD and NAMED
    for bad_css, bad_html, tag in ((css.replace("TOKENS alpha", "TOKENS nope"), consumer, "missing canon marker"),
                                   (css, "<html>no style " + "var(--alpha-60)", "missing <style>")):
        try:
            render(bad_html, bad_css)
            fails.append(f"{tag} did not raise")
        except TokenRampError:
            pass
    if fails:
        print("gen_token_ramp selftest: FAIL")
        for f in fails:
            print("   ❌ " + f)
        return 1
    print("gen_token_ramp selftest: 6 bites GREEN")
    return 0


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(selftest())
    sys.exit(run(write="--check" not in sys.argv))
