#!/usr/bin/env python3
"""Generate guidelines/_rules-index.json — the KG-addressable rule inventory.

Contract (decided 2026-07-02, Dave):
  * Every enforcement-destiny-tagged rule in guidelines/*.md carries a stable ID:
    the anchor `{#prefix-nnn}` placed immediately after the closing `]` of its
    destiny tag. IDs are identifiers, not ordinals — never renumber.
  * Destiny tags: [BLOCKING…] [ADVISORY…] [TASTE…] [REVIEW…] (free text after the
    keyword allowed; multi-line tags allowed).
  * NON-INDEXED tags (BLESSED by Dave 2026-07-03): [RECORDED…] out-of-engine
    channels (print/SMS/social/internal-comms/sound) · [PROCESS…] workflow
    guidance · [IN FORCE…] operative framing. Deliberately invisible to this
    generator — no index entries, no gate failures; they keep completeness and
    delta-mapping without polluting the enforcement register. Rules under them
    still carry stable {#ids}.
  * This generator FAILS the build (exit 1) on: duplicate IDs anywhere; a tagged
    rule with no ID; a malformed ID. A tag is only exempt in the file header
    (before the first `## `) and on heading lines — those are format docs.
  * Legacy guideline files with no destiny tags produce no entries and no
    failures — they migrate to the engine-era format when re-ingested
    (see _INGESTION-QUEUE.md).

Consumers: the advisory judge (G5 at scale) cites rule IDs; the promotion queue
tracks a rule's advisory→blocking journey by ID; xref links guidelines to gates.
"""
import json, re, sys, pathlib

HERE = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).parent
TAG = re.compile(r'\[(BLOCKING|ADVISORY|TASTE|REVIEW)[^\]]*\]')
ANCHOR = re.compile(r'^\s*\{#([A-Za-z0-9-]+)\}')
ID_SHAPE = re.compile(r'^[a-z0-9]+(?:-[a-z0-9]+)*-\d{3}$')

def rule_text(txt: str, tag_start: int) -> str:
    """Walk back to the start of the containing bullet or paragraph."""
    start = 0
    for m in re.finditer(r'\n(?=- )|\n(?=\d+\. )|\n\s*\n', txt[:tag_start]):
        start = m.end()
    chunk = txt[start:tag_start]
    chunk = re.sub(r'\s+', ' ', chunk).strip()
    chunk = re.sub(r'^(\-|\d+\.)\s*', '', chunk)
    chunk = chunk.replace('**', '')
    return chunk[:500]

def main() -> int:
    rules, errors, seen = [], [], {}
    for p in sorted(HERE.glob('*.md')):
        if p.name.startswith('_') or p.name == 'README.md':
            continue
        txt = p.read_text(encoding='utf-8')
        if '\n## ' not in txt:
            continue
        body_start = txt.index('\n## ')
        for m in TAG.finditer(txt):
            if m.start() < body_start:
                continue
            line_start = txt.rfind('\n', 0, m.start()) + 1
            if txt[line_start:line_start + 1] == '#':
                continue
            am = ANCHOR.match(txt[m.end():m.end() + 40])
            where = f'{p.name}: “{m.group(0)[:50]}…”'
            if not am:
                errors.append(f'tagged rule missing {{#id}} — {where}')
                continue
            rid = am.group(1)
            if not ID_SHAPE.match(rid):
                errors.append(f'malformed id {{#{rid}}} — {p.name}')
                continue
            if rid in seen:
                errors.append(f'duplicate id {{#{rid}}} in {p.name} (first: {seen[rid]})')
                continue
            seen[rid] = p.name
            destiny = m.group(0).strip('[]').split('—')[0].split(';')[0].strip()
            rules.append({
                'id': rid,
                'file': p.name,
                'destiny': m.group(1),
                'destinyFull': re.sub(r'\s+', ' ', destiny)[:120],
                'rule': rule_text(txt, m.start()),
            })
    if errors:
        print('❌ rules-index gate failed:')
        for e in errors:
            print('   -', e)
        return 1
    rules.sort(key=lambda r: r['id'])
    by = {}
    for r in rules:
        by[r['destiny']] = by.get(r['destiny'], 0) + 1
    out = {
        '$description': 'GENERATED by gen_rules_index.py — do not hand-edit. '
                        'Stable rule IDs for gates, advisory judge, promotion queue.',
        'count': len(rules),
        'byDestiny': dict(sorted(by.items())),
        'rules': rules,
    }
    (HERE / '_rules-index.json').write_text(
        json.dumps(out, indent=1, ensure_ascii=False) + '\n', encoding='utf-8')

    # Reconciliation register — every [REVIEW] rule is an unreconciled contradiction,
    # source tension, or pending ruling. Generated so it can't drift (Dave, 2026-07-02).
    reviews = [r for r in rules if r['destiny'] == 'REVIEW']
    lines = [
        '# Reconciliation register — open contradictions and pending rulings',
        '',
        '*GENERATED by `gen_rules_index.py` from every `[REVIEW]`-tagged rule in',
        '`guidelines/` — do not hand-edit; edit the rule in its guideline file. Context:',
        'the 2026 brand refresh is IN DEVELOPMENT — standards and approved components may',
        'both move in short order, and component approvals already embed Dave\'s knowledge',
        'of the unpublished update. Reconcile each item when its standard settles, or when',
        'Dave rules.*',
        '',
    ]
    by_file = {}
    for r in reviews:
        by_file.setdefault(r['file'], []).append(r)
    for fn in sorted(by_file):
        lines.append(f'## {fn}')
        lines.append('')
        for r in by_file[fn]:
            lines.append(f'- **{r["id"]}** — {r["rule"]}')
        lines.append('')
    lines.append(f'_{len(reviews)} open item(s)._')
    (HERE / '_RECONCILIATION.md').write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'rules index: {len(rules)} rules from '
          f'{len(set(r["file"] for r in rules))} engine-era files — {by}')
    return 0

if __name__ == '__main__':
    sys.exit(main())
