# #303 wrap seat - the names every #303 wrap script shares. Modelled on #302's names_302.py.
SLUG = 'the-deck-was-finished-for-friday-and-apollo-mcp-was-asked-for'
HO = '_HANDOFF-154-the-deck-was-finished-for-friday-and-apollo-mcp-was-asked-for.md'
HO_PREV = '_HANDOFF-153-the-deck-grew-a-slide-and-the-ask-went-to-his-colleagues.md'
DOS = '_DECISION-HISTORY/2026-09-24-303-the-deck-was-finished-for-friday-and-apollo-mcp-was-asked-for.md'
BRIEF = 'notes/_lanes/303/WRAP-BRIEF.md'
HOOK = 'notes/_lanes/303/WRAP-MEMORY-HOOK.md'
HOOK_PREV = 'notes/_lanes/302/WRAP-MEMORY-HOOK.md'
REPP = 'notes/_subreports/2026-09-24-303-P-press-animation.md'
REPG1 = 'notes/_subreports/2026-09-26-303-G1-genui-archaeology.md'
REPG2 = 'notes/_subreports/2026-09-26-303-G2-agent-ui-landscape.md'
REPW = 'notes/_subreports/2026-09-26-303-W-wrap.md'
PROMPT = 'notes/_lanes/303/DEMO-PROMPT-2026-09-25-hsbc-ceo-common.md'
DECK = 'notes/_DEMO-SLIDES-apollo-2026-09-22-v14-plain.html'
DECK17 = 'notes/_DEMO-SLIDES-apollo-2026-09-24-v14-plain-with-slide-11.html'
DECK_SRC = 'notes/_lanes/296/C/v14-plain-before-c.html'
BUILD = 'notes/_lanes/296/C/build_c.py'
PRESS = 'notes/_lanes/303/P/press.html'
KG = 'notes/_KG-EXPLORER.html'
VISION = 'notes/_VISION-contextual-dashboard_2026-06-29.md'
ZIP = 'notes/_lanes/303/Apollo-Friday-2026-09-25.zip'
ZIP_SMALL = 'notes/_lanes/303/Apollo-Friday-2026-09-25-without-pack.zip'
TRANSCRIPT = '/root/.claude/projects/-home-claude/2164dd10-ba27-5634-8eac-5cf4c44aa5e4.jsonl'
NEXT_TITLE = 'Apollo - #304: the Apollo-MCP proposal page'
RENAME = 'Apollo - #303: the deck was finished for Friday, and Apollo-MCP was asked for'
HEADLINE = 'THE DECK WAS FINISHED FOR FRIDAY, AND APOLLO-MCP WAS ASKED FOR'
SHA1 = '6c881313'
SHA2 = '683f4cca'
RUN1 = '36035716214'
RUN2 = '36036092619'
Q1537 = "we should use the Common theme rather than supercharge and maybe ask it to be liberal with data visualisations"
Q1546 = "these are observations that we will role into the graph at some point"
Q1551 = "cool ill test it later."
Q1557 = "Ditch the large title 'The twelve types of entity in the judgement layer.'"
Q1712 = "BETA to Enterprise Capability"
Q1814 = "so it looks like 6 items actually."
Q1329 = "Can I have this as a page, do you think we could create our own MCP-UI -- Apollo-MCP maybe or something that has the same capabilities as  Google's A2UI and MCP-UI. I think we have to come up with a proposal for this, we also did some work around Gen-UI earlier in the year, I think its time to pull these ideas together, maybe do a bit more research and get this doc together"
QWRAP = "wrap up :)"
