#!/usr/bin/env python3
"""#284 wrap, 4b — the FORWARD title into GOOD-MORNING.md, GENERATED by
`python3 knowledge/_gen_titles.py --session 284` (receipt `knowledge/_gen_titles_receipt.json`).

⚠ MEASURED DISAGREEMENT, PUBLISHED RATHER THAN SMOOTHED: the #284 wrap brief DECLARES
`Apollo - #285: the routing line and the boot experiment`; the generator — which derives
NEXT-TITLE from the first ⬛ bullet's bolded clause on the residual pointer line, and whose
`title_generation_check()` is BLOCKING — produces the line below. The GENERATED line is the
one written, because 4b says generate; the declared one is recorded in this wrap's report.
⛔ The RENAME line is delivered IN CHAT and is never written into this file (ruled #28).
"""
import sys
from run_ops import run

OLD = "> **TITLE THE NEXT CHAT →** `Apollo - #284: the logo masters, at last`"
NEW = "> **TITLE THE NEXT CHAT →** `Apollo - #285: the delegation lapse — everything is delegated`"

OPS = [{"op": "replace", "file": "GOOD-MORNING.md", "find": [OLD], "replace": [NEW]}]

if __name__ == "__main__":
    sys.exit(run("title", OPS, write="--write" in sys.argv, min_bytes=100))
